### ISSUE TITLE
Lỗi crop hình ảnh luôn ở 100px

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#101]
Bị tương tự như lỗi crop hình của news.
https://github.com/nukeviet/nukeviet/issues/544

**Comment by tungkiet** [comment]
Không biết đã ai fix cái này chưa nhỉ

**Comment by anhyeuviolet** [comment]
Cấu hình trong 
/admin/index.php?language=vi&nv=upload&op=thumbconfig

Rồi up lại các hình xem có bị ko bạn :|

**Comment by tungkiet** [comment]
yeah! thks u!
