### ISSUE TITLE
Lỗi link phần " Hãng sản xuất" khi xem chi tiết SP

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#102]
KO biết có ai báo chưa.
Trong detail.tpl của shops có đoạn sau

<! -- BEGIN: source -->
<div >
	{LANG.detail_source} : 
	<a href="{divnk_source}" title="{LANG.detail_source_search}">{ source }</a></div >

Thì href="{divnk_source}" thay vì
 href="{link_source}"

**Comment by hongoctrien** [comment]
Mình không tìm thấy đoạn này ta :S

**Comment by anhyeuviolet** [comment]
:dancers: Hình  như shop bản cập nhật đã loại bỏ phần này rồi nên ko thấy nữa đó bạn.
