### ISSUE TITLE
Thêm mã giảm giá bị lỗi

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/module-shops#105]
Khi nhập mỗi Tên + Mã + Số tiền giảm submit bị lỗi:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/module-shops/commit/8f0488ac7d87985132df37ada73f8936e69c958c)
