### ISSUE TITLE
[SEO] Nên cho tag description được tự do nhập nội dung

### ISSUE THREAD

**Issue by thangvn** [nukeviet/module-shops#106]
Mình thấy phần tag description của module SHOP hạn chế ở điểm : không được tự do nhập phần MÔ TẢ ( description)
Với từ khoá dễ thì NK lên rất nhanh nhưng với từ khoá khó thì rất chậm ( hầu như không biết thứ hạng) .

Minh quan sát và nghiên cứu 1 số website về cạnh tranh từ khoá khó ( so NK với website khác) thì thấy để cạnh tranh từ khoá khó,thì tag description rất quan trọng ( bên cạnh nội dung ).

Như chúng ta đã biết thì với module Shop không như module Tin Tức, nội dung Shop rất hạn chế,không cầu kì và nhiều chữ.

Mình góp ý như sau :

- Hiện tại,tag description NK 4 sử dụng mặc định đó là lấy tên sản phẩm.Vì vậy,nên cho 1 textbox hiển thị nội dung text này trong phần QUẢN TRỊ để nếu ADMIN(users) không đồng ý với nội dung tag này thì có thể thay đổi theo chiều hướng có lợi cho SEO ( giống như textbox LIÊN KẾT TĨNH,để ta có thể thay đổi link)

**Comment by anhyeuviolet** [comment]
Shop hình như có phần 
Giới thiệu ngắn gọn (*) (Hiển thị đối với mọi đối tượng)

Cái này được lấy làm thẻ meta description mà.
