### ISSUE TITLE
Lỗi khi lưu thay đổi Mã giảm giá trong admin

### ISSUE THREAD

**Issue by kimchan0205** [nukeviet/module-shops#108]
mình vào :
http://localhost/nukeviet-develop/admin/index.php?language=vi&nv=shops&op=coupons
thấy có thông báo lỗi như thế này : ( nhưng vẫn lưu được )
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/module-shops/commit/8f0488ac7d87985132df37ada73f8936e69c958c)
