### ISSUE TITLE
Lỗi trong đơn hàng vận chuyển 

### ISSUE THREAD

**Issue by kimchan0205** [nukeviet/module-shops#110]
khi nhập cấu hình nhà vận chuyển thì ở thêm chi tiết cấu hình thì mục cấu hình khối lượng không lưu lại được tất cả dữ liệu đã nhập mà chỉ lưa được một phần, phải nhập lại vài lần mới lưu được

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/module-shops/commit/bf0c3d54af74f4cc4e3ec773358fd4d165ec6ded)
