### ISSUE TITLE
lỗi khi đăng sản phẩm

### ISSUE THREAD

**Issue by nguyenhuemdc** [nukeviet/module-shops#115]
khi thêm sản phẩm và điền đầy đủ các thông tin bắt buộc mà không thể lưu được sản phẩm chỉ thấy hiện ra phần này và 1 trang trắng 
http://hue.mangvn.org:88/admin/index.php?nv=shops&op=content&catid=4&parentid=0
có thể do quá nhiều kí tự, lỗi chỉ xảy ra khi thêm mới sản phẩm, còn khi sửa thì vẫn lưu được:
đoạn thêm trong 
"Giới thiệu ngắn gọn (*) (Hiển thị đối với mọi đối tượng)"
xảy ra lỗi
Thành phần 

Nước, oxit titan, Cyclopentasiloxane, ethylhexyl methoxycinnamate, cyclohexasiloxane, alkyl benzoate (C12-15), BG, oxit sắt, para-methoxy cinnamic axit isoamyl salicylate ethylhexyl, lauryl PEG-9 polydimethylsiloxyethyl dimethicone , dicaprylyl carbonate, Ceresin, bis ethylhexyl metoxyphenyl triazin, Na clorua, tơ hồng chiết xuất nhau thai văn hóa, chiết xuất dầu Zegna, chiết xuất lá bạc hà, chiết xuất hoa anh thảo ngựa, Hagoromogusa chiết xuất,

**Comment by hongoctrien** [comment]
Tải bản mới nhất về cài đặt nhé, có thể CSDL bạn chưa được cập nhật.
