### ISSUE TITLE
Lỗi phần hiển thị giới thiệu ngắn gọn khi xem chi tiết sản phẩm

### ISSUE THREAD

**Issue by thangvn** [nukeviet/module-shops#121]
![6](https://cloud.githubusercontent.com/assets/6823461/6002685/1b26bfae-ab28-11e4-820c-bd9794673820.jpg)

Lỗi này là lỗi sơ sót,đúng ra khi check thì có nghĩa là hiển thị nhưng nó lại không hiển thị phần giới thiệu chi tiết về sản phẩm.Khi không check nó lại hiển thị phần giới thiệu chi tiết sản phẩm

![7](https://cloud.githubusercontent.com/assets/6823461/6002759/baaea9f6-ab28-11e4-93df-3e292b1a5fd1.jpg)

Module shops phiên bản 4.0(được tải cách đây gần 3 tuần)

**Comment by hongoctrien** [comment]
Cái đó bật tắt hometext (giới thiệu ngắn gọn) ở chổ thông tin bên trên (giá, tên, mã,...) ý bạn, chứ ko phải chổ đó.

**Comment by thangvn** [comment]
cám ơn bạn hongngoctrien.Do mình chưa xoá cache nên nhầm
