### ISSUE TITLE
Lỗi cài đặt bản mới nhất

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-shops#125]
Bản develop mới nhất của shop down về khi bấm cài đặt trong admin thì tự động nhảy ra lại trang chủ admin. click vào modules shops thì ra trang trắng...

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/module-shops/commit/0fae3a54fd984c4ce11b3c7479521d68ef45e6b8)
