### ISSUE TITLE
Lỗi bản develop mới nhất

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-shops#127]
Lỗi thêm nhóm mới ra trang trắng. Bấm f5 thì tạo được nhóm, nhưng khi thêm sản phẩm mới không hiện tên nhóm để chọn, CSS admin bị lỗi khi thêm sản phẩm mới: cột giữa mình thấy định dạng là .col-md-9 width: 37.5%;. nên nó quá nhỏ nên nó không bung ra hết màn hình...

**Comment by hongoctrien** [comment]
[Fix lỗi trang trắng thêm nhóm sản phẩm](https://github.com/nukeviet/module-shops/commit/fbc7fb46f502fc82b3a1114d6ed01ada9cbd2c6e), cài lại module giúp mình nếu chưa có dữ liệu nhé.

**Comment by anhutbeo** [comment]
Đã cài mới, lỗi trang trắng ok. còn css trong phần thêm sản phẩm vẫn còn. Phần tùy chọn nhóm sản phẩm khi đăng sản phẩm mới vẫn chưa fix để chọn. đăng sản phẩm mới ra trang trắng

**Comment by hongoctrien** [comment]
>cột giữa mình thấy định dạng là .col-md-9 width: 37.5%;. nên nó quá nhỏ nên nó không bung ra hết màn hình...

Phần này bạn nói rõ hơn giúp mình ạ, có thể gửi lên 1 cái ảnh cho dễ hình dung

Bạn download code mới, up đè vào rồi cài lại luôn xem sao.

**Comment by anhutbeo** [comment]
![loi](https://cloud.githubusercontent.com/assets/10916826/6144107/b34b4e42-b205-11e4-9ad3-53ab315a269c.png)

Nó đây bạn. mình đã xóa và cài đặt mới toàn bộ từ code nukeviet và modules shops

**Comment by anhutbeo** [comment]
(https://cloud.githubusercontent.com/assets/10916826/6144119/df9fa056-b205-11e4-8904-bfd8b6ab96f2.png)

https://cloud.githubusercontent.com/assets/10916826/6144119/df9fa056-b205-11e4-8904-bfd8b6ab96f2.png

**Comment by hongoctrien** [comment]
Bạn đang dùng nukeviet bản develop mới nhất phải không?
NukeViet develop mới nhất có thay đổi tỉ lệ cột từ 12 cột lên 24 cột. Mình chưa kịp cập nhật lại cho shops develop. Bạn cài NukeViet 4.0.10 cùng shops develop để test nhé.

**Comment by anhutbeo** [comment]
À thì ra là thế. để mình dùng bản 4.0.10 để test thử xem sao? :)) thanks Cậu

**Comment by anhutbeo** [comment]
![loi4 0](https://cloud.githubusercontent.com/assets/10916826/6144220/489ae948-b207-11e4-8ea0-5af70d35873f.png)

Dùng 4.0.10 thì hết css, nhưng phần tùy chọn để thêm nhóm sản phẩm khi thêm mới thì không hiển thị để chọn. bạn xem thử ...

**Comment by hongoctrien** [comment]
Bạn lưu ý, khi thêm nhóm sản phẩm, có phần **Của loại sản phẩm**, bạn chọn nhóm nào thì khi vào thêm sản phẩm bạn chọn đúng nhóm đó thì nhóm sp mới hiển thi.

**Comment by anhutbeo** [comment]
![loi4 0](https://cloud.githubusercontent.com/assets/10916826/6144381/76dfbf66-b209-11e4-8e5b-30b9aeb552de.png)

Mình thử như bạn nói, thì thấy như trên hình, làm thế nào để chọn 1 trong 2 cái đó vậy ?

**Comment by hongoctrien** [comment]
OK, cái này còn một ràng buộc là "nếu không có nhóm con thì không hiển thị ra ở đó", mình sẽ bổ sung thêm sau.

Bạn quay lại Quản lý nhóm sản phẩm, thêm nhóm con cho nó nhé.
Ví dụ: 
* Loại hoa
  * Bó hoa tươi
  * Giỏ hoa tươi
* Xuất xứ
  * Đà Lạt
  * Phan Thiết

**Comment by anhutbeo** [comment]
À ra là thế, để mình như bạn nói xem thử thế nào

**Comment by hongoctrien** [comment]
Có mấy chức năng mới phát triển nên khả năng có lỗi.
Có gì bạn báo lên giúp mình nhé.
Cảm ơn bạn

**Comment by anhutbeo** [comment]
Đã ok, có chi test tiếp có lỗi mình báo sau. Cảm ơn bạn

**Comment by anhutbeo** [comment]
![loi](https://cloud.githubusercontent.com/assets/10916826/6146796/fb533bd8-b222-11e4-88df-9ad97d27dd7a.png)
Không hiện nội dung toolip khi có kí tự đặc biệt như dấu ngoặc " " . 
![loi2](https://cloud.githubusercontent.com/assets/10916826/6146817/49e8f4ea-b223-11e4-9292-d3cf19173756.png)
Phần giảm giá nó hiện cái nội dung mình khoanh tròn đó không biết là ý gì. vì cái đó là trong phần setting của giảm giá. từ sản phẩm số 1 đến số 5 là giảm giá 20%

**Comment by hongoctrien** [comment]
Cái đó tính giá theo số lượng đó bạn.
Mua càng nhiều giá càng thấp.
