### ISSUE TITLE
Lỗi trắng trang khi viết nhiều kí tự ở phần giới thiệu ngắn gọn khi đăng sản phẩm

### ISSUE THREAD

**Issue by dxluan1986** [nukeviet/module-shops#130]
Lỗi trắng trang khi viết nhiều kí tự ở phần giới thiệu ngắn gọn khi đăng sản phẩm, phải giảm bớt kí tự thì đăng bình thường

**Comment by anhutbeo** [comment]
Cái này mình test thử thì thấy bình thường. thêm khá dài cũng không thấy như lỗi bạn mô tả

**Comment by hongoctrien** [comment]
Dài ở đây là khoảng bao nhiêu ký tụ @dxluan1986

**Comment by anhutbeo** [comment]
@hongoctrien nếu không phải là thành viên mà đặt hàng thì bị lỗi trang trắng, nhưng trong admin vẫn nhận được đơn đặt hàng đó. link trang trắng có dạng: demo010115/index.php?language=vi&nv=shops&op=payment&order_id=2&checkss=cfe0a0ca8d98d0f6fd7405e9df3424a5

**Comment by hongoctrien** [comment]
>@hongoctrien nếu không phải là thành viên mà đặt hàng thì bị lỗi trang trắng, nhưng trong admin vẫn nhận được đơn đặt hàng đó. link trang trắng có dạng: demo010115/index.php?language=vi&nv=shops&op=payment&order_id=2&checkss=cfe0a0ca8d98d0f6fd7405e9df3424a5

[Fixed](https://github.com/nukeviet/module-shops/commit/769cc82711af9c328c0847e6c181c3602df47332). Mỗi vấn đề tạo 1 issue giúp mình nhé.

**Comment by hongoctrien** [comment]
@dxluan1986 bạn test giúp mình khoảng bao nhiêu ký tự là bị ạ?
Trường này kiểu text nên cho phép số ký tự khá lớn.

**Comment by hongoctrien** [comment]
Do không thấy @dxluan1986 phản hổi, và mình kiểm tra hiện tại không thấy lỗi này, nên sẽ đóng issues này.

**Comment by dxluan1986** [comment]
sory vì ko quen làm việc trên github nên mình ko comment trả lời các bạn được, mình vẫn bị lỗi đấy, mình dùng bản nuke 4.10, trong admin modul shop lúc thêm sản phẩm phần giới thiệu ngắn gọn viết dài ví dụ như dài chừng này là bị :" Là dòng chuột có độ bền cao, thích hợp cho dân văn phòng và game thủ" cụ thể thì các bạn có thể team view để kiểm chứng
