### ISSUE TITLE
Không hiện nội dung toolip khi có kí tự đặc biệt như dấu ngoặc " " 

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-shops#132]
![fb533bd8-b222-11e4-88df-9ad97d27dd7a](https://cloud.githubusercontent.com/assets/10916826/6182595/aefee0fe-b379-11e4-8cf0-2738d8c33a5c.png)

Không hiện nội dung toolip khi có kí tự đặc biệt như dấu ngoặc " "

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/module-shops/commit/ac2b24c2c747d8849889d8a5ed7e6a772c8431aa)
