### ISSUE TITLE
Không cập nhật tiền khi dùng mã giảm giá khi thanh toán

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-shops#137]
Khi đưa mã giảm giá
![capnhat](https://cloud.githubusercontent.com/assets/10916826/6208882/ed40f008-b5f1-11e4-8404-890e7cf82642.png)

Khi đặt hàng thành công
![dat](https://cloud.githubusercontent.com/assets/10916826/6208889/019dcc60-b5f2-11e4-8bb4-0f41f4f53b21.png)

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/module-shops/commit/ba859651720d1b68975b41c5b73a179d75af6753)
