### ISSUE TITLE
Lỗi code khi chọn giảm giá sản phẩm

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-shops#138]
Khi chọn giảm giá cho sản phẩm bên ngoài site sẽ xuất hiện như hình bên dưới. Cái chữ "giảm giá" đó là trong admin 

![giamgia](https://cloud.githubusercontent.com/assets/10916826/6209042/7d7acd5a-b5f3-11e4-82a3-8dbe26daf650.png)

**Comment by hongoctrien** [comment]
Phần hiển thị giảm giá này thấy không cần thiết nên mình bỏ luôn rồi bạn nhé, sẽ cho nó hiển thị ở một vị trí khác, sẽ cập nhật thêm sau.
