### ISSUE TITLE
Nhóm sản phẩm theo danh mục không có nút chọn khi đăng sản phẩm

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/module-shops#141]

**Comment by hongoctrien** [comment]
Quy trình sử dụng cái này như sau:
1. Quản lý nhóm sản phẩm, thêm nhóm, chọn Loại sản phẩm cho nhóm (bắt buộc)
2. Thêm sản phẩm, chọn Loại sản phẩm (Ứng với mỗi loại sẽ có các nhóm sản phẩm khác nhau, các nhóm liên quan hiển thị cuối trang - bên trên nút "Đăng sản phẩm")
