### ISSUE TITLE
Lỗi đặt hàng và điểm tích lũy

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#152]
Mình cài module trên localhost thấy khi thanh toán bị lỗi trắng trang nhưng khi vào admin thì hàng vẫn đặt thành công.

Bên cạnh đó phần điểm tích lũy khi đã xác nhận đơn đặt hàng nhưng điểm tích lũy vẫn không được cộng vào thành viên.

**Comment by hongoctrien** [comment]
@motcaiten bạn đã sử dụng shops + nukeviet mới nhất chưa ạ?
Bạn download lại mã nguồn và test lại giúp mình nhé.
Mình không thấy lỗi này.

**Comment by motcaiten** [comment]
Cả hai đều tải về lúc tối. Để mình tải bản mới nhất về xem.

**Comment by hongoctrien** [comment]
Mình đang online, nếu vẫn lỗi thì pm ID teamview giúp mình nhé.
https://www.facebook.com/hntrien

**Comment by motcaiten** [comment]
@hongoctrien  ok anh.

**Comment by hongoctrien** [comment]
Sao rồi @motcaiten nhỉ?

**Comment by motcaiten** [comment]
@hongoctrien Mấy hôm bận quá nên chưa test được.

Hôm nay rãnh nên lên test cái shops mới nhất vừa update cách đây 1h thì thấy có lỗi này không thể nào đặt hàng được.

Nhấn vào gửi thông tin phiếu đặt hàng là nó ra. Khi nào tắt trang thì mới ok.

![capture](https://cloud.githubusercontent.com/assets/8292355/6642792/158213d4-c9da-11e4-9def-71f1ffa8055c.JPG)

**Comment by hongoctrien** [comment]
@motcaiten thử ở trình duyệt khác hoặc máy khác giúp mình. Mình nghĩ lỗi này không liên quan đến NukeViet.
