### ISSUE TITLE
Bị lỗi không gửi Ý kiến comment (HỎi đáp) được khi xem sản phẩm

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/module-shops#159]
Mình download dùng bản mới nhất của module shop
- Nuke deverlope mới nhất 4.x

nó hiện ra thông báo này khi mình view 1 sản phẩm có 3 tab: chi tiết - hỏi đáp - Đánh giá phản hồi
thì khi viết vào phẩn hỏi đáp nó ra báo lỗi như này
![shop](https://cloud.githubusercontent.com/assets/6945379/6632971/72474098-c972-11e4-9743-773565d450fb.PNG)
- Vấn đề thứ 2 là : khi post thêm ảnh vào mục sản phẩm, nếu mà mình chọn ảnh to quá -->ra ngoài site view -"hình ảnh khác" thì ảnh đó không hiện hết - mình góp ý là nên tự động thu nhỏ hình lại --> hoặc là khi post ảnh to quá vượt màn hình thì khi kéo xuống thì phải xem được tất cả hình --> ở đây khi ảnh to quá kéo xuống là nó vẫn đứng im chỉ xem được phần ngọn nó thôi.
chân thành cảm ơn anh em

**Comment by hongoctrien** [comment]
@nethoabinh 
Vấn đề 1: Bạn download lại NukeViet 4 bản develop mới nhất rồi test lại giúp mình nhé, test cả trên bài viết của news nữa.

Vấn đề 2: Mặc định ảnh sẽ không tự động co dãn, nếu ảnh lớn hơn khung người dùng có thể cầm chuột giữ ảnh và kéo về các góc cần xem.
Bạn có thể thay thế chế độ tự động chỉnh kích thước ảnh bằng cách, mở file **modules/shops/theme.php** tìm chữ **drag** thay bằng chữ **none**
