### ISSUE TITLE
lỗi đặt hàng

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/module-shops#160]
không đặt hàng được khi hiện theo loại sản phẩm trên trang chủ
không đặt hàng được xem chi tiết
-------------------
Khi đặt hàng xong, phần chi tiết thống kê còn bao nhiêu sản phẩm ko hoạt động

**Comment by hongoctrien** [comment]
>không đặt hàng được khi hiện theo loại sản phẩm trên trang chủ

[Fixed](https://github.com/nukeviet/module-shops/commit/99f0875c105486ae1220af99ee31ac7de3a11eea)

>không đặt hàng được xem chi tiết
>Khi đặt hàng xong, phần chi tiết thống kê còn bao nhiêu sản phẩm ko hoạt động

Lỗi này cụ thể ra sao bạn, mình test vẫn thấy bình thường a
