### ISSUE TITLE
Tính năng size sản phẩm nên có hỗ trợ phần Số lượng theo từng Size

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/module-shops#162]
Tính năng size sản phẩm nên có hỗ trợ phần Số lượng theo từng Size. Ví dụ:
Size M: hết hàng
Size: S: 2 cái
Size: L: 4 cái

**Comment by vuthao** [comment]
Tính năng này đã làm xong rồi đúng không @hongoctrien, Nếu xong rồi đóng nó lại nhé
