### ISSUE TITLE
[Hỏi] Chức năng trường tuỳ biến cho Shop 

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#163]
Xin chào !
Mình mới tải bản shop Dev về, hiện mới kiểm tra chức năng trường tuỳ biến nhưng khi thêm trường mới thì ko thấy kq gì.
Xin hỏi chức năng này đã hoàn chỉnh chưa và dùng như nào ạ ?

**Comment by hongoctrien** [comment]
@anhyeuviolet bạn down lại code tại thời điểm này,  rồi cài đặt lại nhé https://github.com/nukeviet/module-shops/archive/develop.zip

## Hướng dẫn nhanh chức năng tùy biến trường dữ liệu
1. Sử dụng tài khoản quản trị tối cao, truy cập menu **Tùy biến trường dữ liệu**
2. Tạo nhóm dữ liệu. Ví dụ: Form thông tin quần áo
3. Truy cập menu **Trường dữ liệu**, tạo ra cá trường dữ liệu thuộc Form vừa tạo bên trên. Ví dụ: Chất liệu, xuất xứ,......
4. Truy cập khu vực quản lý **Loại sản phẩm**. Sửa hoặc thêm sản phẩm. Tại ô **Dữ liệu tùy biến**, chọn tên form vừa tạo bên trên. Lưu lại.
5. Sửa / Thêm 1 sản phẩm. Chọn chủ đề (Mỗi chủ để sẽ ứng với form vừa được chọn ở bước 4. Sau khi chọn loại sản phẩm, kéo xuống dưới trang, sẽ xuất hiện form thông tin quần áo để bạn nhập thông tin.
6. Xem kết quả ở trang chi tiết sản phẩm (bên dưới giới thiệu ngắn gọn)

**Comment by dtsoncntt** [comment]
Có cách nào khác mà không cần phải cài đặt lại không @hongoctrien shop đang bình thường cài đặt lại phải làm lại từ đầu @@

**Comment by hongoctrien** [comment]
Đang dùng bản nào đó @dtsoncntt

**Comment by dtsoncntt** [comment]
@hongoctrien  à mình sử dụng đc rồi . tuy nhiên là nó chỉ hiện ở loại sản phẩm cấp 1, còn ở loại sản phẩm dạng cấp 2 / 3 thì không thấy hiện ???

**Comment by dtsoncntt** [comment]
Có 1 điều là sao nó xuất dữ liệu ra ngoài giao diện nó không tách ra từng bảng mà nó xuất luôn ra cả 1 nhóm {CUSTOM_DATA} ?? @hongoctrien

**Comment by hongoctrien** [comment]
Đúng ý @dtsoncntt . Hiện tại nó hiển thị thành 1 list, chứ chưa cho nó nằm nhiều vị trí khác nhau.

**Comment by dtsoncntt** [comment]
Vậy có thể tách ra để việc bố cục giao diện nó phù hợp hơn và tùy biến hơn không @hongoctrien và cách làm như thế nào ?

**Comment by hongoctrien** [comment]
Cái này lúc code anh em đội code có thảo luận, nhưng vẫn chưa có tgian để tách nó ra dùng cho nhiều vị trí được. Và giờ mình cũng chưa có hướng gì để làm cái đó. Có lẽ là xử lý lại code hiển thị ở theme.php

**Comment by dtsoncntt** [comment]
Hi vọng sẽ sớm điều chỉnh , chứ để hiển thị 1 chỗ nó khá bất tiện , không được bố cục gọn gàng và nên mất mỹ quan rối tung lên @hongoctrien

**Comment by hongoctrien** [comment]
OK

**Comment by dtsoncntt** [comment]
Khi thêm trường dữ liệu / trình soạn thảo 
-> sau khi coppy hoặc nhập chữ vào ra ngoài site thì bị lỗi khoảng cách dòng rất là rộng , và khoảng cách dòng giữa text và table rất là rộng , sửa trong trình soạn thảo thì vô tác dụng
