### ISSUE TITLE
Lỗi không đặt hàng nhanh được và không xem được chi tiết sản phẩm

### ISSUE THREAD

**Issue by tienquynhnguyen** [nukeviet/module-shops#165]
Em có cài cái modules mới ở đây:http://forum.nukeviet.vn/viewtopic.php?f=3&t=35035#p167232
Cài trên bản 4.0 beta 10. Cài vào oke. thêm sản phẩm oke. 
Nhưng khi ra site để xem thì nó có hiện modules shop. Vô link domain/shops/ thì nó ra danh sách sản phẩm. Nhưng sao khi click đặt hàng nó hiện lên popup trong suốt không có nội dung. Bấm vô title để xem chi tiết thì lại ra trang web trắng trơn không có một cái gì hết.

**Comment by tienquynhnguyen** [comment]
![2015-03-16_22-12-00](https://cloud.githubusercontent.com/assets/11505077/6669228/5d757792-cc2a-11e4-81cc-811bd9a544e5.jpg)

**Comment by hongoctrien** [comment]
Chào bạn ạ.
Bạn down shops mới nhất và NukeViet 4 mới nhất nhé.
https://github.com/nukeviet/nukeviet/archive/develop.zip

**Comment by tienquynhnguyen** [comment]
Mình cài như bác nói rồi. Nhưng bản nuke mới bác cho không có phần cài đặt thêm modules bác ơi
![2015-03-17_10-10-02](https://cloud.githubusercontent.com/assets/11505077/6680758/f2178332-cc8d-11e4-8609-df44e508ea78.jpg)

**Comment by hongoctrien** [comment]
NukeViet 4 mới nhất có khác về cách cài đặt themes, module, block.
Bạn cài thủ công nhé. 
1. Download và cài đặt NukeViet 4
2. Download shops mới, giải nén và copy vào thư mục tương ứng của NukeViet
3. ACP / Quản lý module / Cài đặt module mới.
4. Thiết lập module shops như các phiên bản trước.

**Comment by tienquynhnguyen** [comment]
Cảm ơn bạn nha. 
Mình cũng nghĩ chắc do cài auto hay lỗi cấu trúc nên bắt cài thủ công. 

À cho góp ý chút là cái mục điểm tích lũy trong modules hình như không hoạt động, mình kích vào ko thấy ra gì. 

Mà cái ảnh khi xem chi tiết sản phẩm, ở tab hình ảnh khác. khi click vào xem lớn thì nó phóng đúng kích thước gốc ảnh luôn, bị tràn màn hình mà lại không scroll chiều nào thêm để xem được nên bị mất ảnh

Trong phần đặt hàng khi khách chọn vận chuyển thì có phần chọn địa điểm theo khu vực xong thì mình nghĩ nên có trường bắt buộc để nhập địa chỉ chi tiết, chứ nhập khu vực mà không bắt buộc nhập địa chỉ chi tiết mà cho option thì nhiều khách họ không nhập thì không có thông tin giao hàng..

Mà hình như trên localhost không tự gửi mail đơn hàng cho khách hàng khi order xong được đúng không bạn. Hay cho phần gửi mail đơn hàng cho khách bị lỗi

Trên đây là ý kiến cá nhân, có gì không phải bỏ qua cho :)

**Comment by hongoctrien** [comment]
Vâng ạ. Những vấn đề bạn nêu mình sẽ kiểm tra lại.

> Mà cái ảnh khi xem chi tiết sản phẩm, ở tab hình ảnh khác. khi click vào xem lớn thì nó phóng đúng kích thước gốc ảnh luôn, bị tràn màn hình mà lại không scroll chiều nào thêm để xem được nên bị mất ảnh

Cái này bạn cầm chuột xong kéo ảnh về các gốc nhé.

> Mà hình như trên localhost không tự gửi mail đơn hàng cho khách hàng khi order xong được đúng không bạn. Hay cho phần gửi mail đơn hàng cho khách bị lỗi

Đươc bạn ạ. Bạn cấu hình lại sever gửi mail cho đúng.

**Comment by tienquynhnguyen** [comment]
Cảm ơn bạn nhiều. Chúc nukeviet ra bản hoàn chỉnh nhé
