### ISSUE TITLE
Thêm trang thông tin xem chi tiết sản sản phẩm trong ACP

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/module-shops#166]
Tạo 1 trang **tổng hợp tất cả các thông tin của một sản phẩm**, giúp quản trị xem được tổng quát hơn về trạng thái sản phẩm.
* Thông tin sản phẩm
* Lịch sử nhập kho
* Chi tiết đánh giá
* Danh sách người đã mua

........
Thể hiện ở dạng tab

**Comment by vuthao** [comment]
Chức Năng ngày xem trực tiếp ở ngoài site nhé
