### ISSUE TITLE
Lỗi chọn nhóm sản phẩm khi đăng sản phẩm

### ISSUE THREAD

**Issue by vietkhanghcm** [nukeviet/module-shops#167]
Mình mới quay lại test thử cái này nhưng có 1 cái này ko rõ là lỗi hay là do mình làm ko đúng.
Khi mình thêm nhóm sản phẩm thì mình chọn danh mục A đã xong.
Khi thêm sản phẩm ở danh mục A thì có 1 danh sách nhóm, nhưng ko thể chọn nhóm đc. 
Cho dù mình nhấp chuột vào tên nhóm hay ctrl + click như khi thêm nhóm mới cũng ko đc
![1](https://cloud.githubusercontent.com/assets/11548992/6723817/e661737a-ce1f-11e4-881f-5774d374da5d.png)
.

Cấu hình máy chủ (cái này là cấu hình trên Host nhưng mình làm cả ở Host và Localhost đề bị bản mới nhất mình thử là 8h 19/03/2015)
Phiên bản NukeViet	4.0.10Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.3.28
Giao thức giữa máy chủ và PHP	LiteSpeed, litespeed
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.5.42-cll

Nếu ko phải là lỗi thì mong các bạn giúp mình hiểu về cách nhập 1 sản phẩm vào nhóm.

**Comment by hongoctrien** [comment]
Có vẻ bạn chỉ nhập cấp 1 của nhóm. Nhóm phải có 2 cấp mới chọn dc.
Ví dụ:
* Hoa
 * Hoa hồng
 * Hoa huệ

* Quần áo
 * Áo nam
 * Áo nữ

**Comment by vietkhanghcm** [comment]
Mình test thì mới tạo 1 danh mục thì đâu có sub

**Comment by vietkhanghcm** [comment]
Mình mới test lại như bạn nói thì khi thêm nhóm không có hiện sub mà chỉ hiện danh mục cấp 1. (mình tạo danh mục A và 1 danh mục B bên trong A, nhưng chỉ hiện A)
![2](https://cloud.githubusercontent.com/assets/11548992/6724774/9c8a911c-ce30-11e4-9108-492f23eb8a54.png)

Và khi mình đăng sản phẩm trong mục A hay B đều hiện nhóm nhưng ko chọn đc nhóm.

**Comment by hongoctrien** [comment]
Ý mình là sub của nhóm ý bạn. Chứ chủ đề ko cần sub cũng dc.
Riêng nhóm phải có sub, như ví dụ của mình ý.

**Comment by vietkhanghcm** [comment]
oh hiểu rồi cảm ơn bạn, khác với bản cũ quá (-_-).

**Comment by hongoctrien** [comment]
:D. Bạn test qua có lỗi gì báo lên đây nhé.
