### ISSUE TITLE
Đặt hàng ở trang chủ bản Develop tải lúc 9:30 PM - 19/03/2015

### ISSUE THREAD

**Issue by crangtenten** [nukeviet/module-shops#168]
Mình sử dụng code NukeViet 4.0 Close Beta 11 , Sử dụng code shop develop  tải lúc 9:30 PM - 19/03/2015. Khi đặt hàng ở trang chủ thì nhấn vào nút đặt hàng không có chạy, nhấn hoài nó cũng vậy. Trước đây 1 tuần mình sử dụng Nukeviet 4.0 Close Beta 10 và tải bản shop develop mới nhất lúc đó thì cũng bi lỗi này. Mong bạn fix sớm

Link hình : http://i.imgur.com/KlASThK.png

**Comment by crangtenten** [comment]
Mình bổ sung là ở view cat đặt hàng cũng không được luôn nhé. Chỉ có ở detail thì nút thêm vào giỏ và mua ngày đều work.

**Comment by hongoctrien** [comment]
@crangtenten bạn xóa hết những gì đã cài và cài lại NukeViet 4.0.11 và shops develop bản mới nhất giúp mình nhé.
Nếu vẫn còn lỗi trên vui lòng cung cấp giúp mình chi tiết điều kiện test của bạn (hệ điều hành, phiên bản php,....) để mình kiểm tra kỹ hơn.
Cảm ơn bạn ạ.

**Comment by crangtenten** [comment]
mình đã cài lại vẫn bị lỗi bạn ơi. hệ điều hành centos 5.6 và php 5.2

**Comment by hongoctrien** [comment]
Không hiểu sao php 5.2 bạn vẫn cài NukeViet 4.0.11 được,  NukeViet 4.0.11 bắt buộc php > 5.3.7 bạn nhé. Không biết bạn cài đúng phiên bản không?

**Comment by crangtenten** [comment]
Bạn check lại nhé, vì mình cái nukeviet bản 4.0.11 không thấy yêu cầu PHP 5.3, mà mình cũng đang muốn nâng cấp php lên 5.3 nhưng chưa biết nâng cấp như thế nào :(

**Comment by hongoctrien** [comment]
@crangtenten :D. Xác định đúng là lỗi như bạn nói.
Mình đã fix, cảm ơn bạn nhiều nhé!
