### ISSUE TITLE
Lỗi Block Module Block Filter Product CAT, và hiển thị nhóm ở trang Detail

### ISSUE THREAD

**Issue by kollersi** [nukeviet/module-shops#170]
- Mình sử dụng Server Centos 5.6
PHP : 5.3

1. Mình sử dụng block  Module Block Filter Product CAT để filter khi chọn select thì lúc được lúc không, đa phần là không được

2. Và ở phần post sản phẩm trong ACP mình có chọn nhóm sản phẩm Sup Group, nhưng ở trang detail bên ngoài thì nó hiện o selectbox và lựa cái Main Group, chứ ko phải sub group mình chọn.

Bạn xem fix 2 lỗi này nhé, mình thấy modules shop của bạn khá ok rồi.

**Comment by hongoctrien** [comment]
Chào @kollersi 
Mình có thấy lỗi nhưng không rõ có phải lỗi bạn nói không.
Mình có [fix](https://github.com/nukeviet/module-shops/commit/66eadb44498e974a556552b5348f2dbf2f606648) lỗi của block này. Bạn down lại mã nguồn mới nhất về test lại giúp mình nhé.
Nếu vẫn còn lỗi bạn mô tả chi tiết hơn giúp mình ạ.
Cảm ơn bạn!

**Comment by kollersi** [comment]
@hongoctrien 
Cái này không phải lỗi đâu ban ạ. Sup group bạn chọn trong ACP là chọn các thuộc tính có thể có của sản phẩm. Còn selectbox hiển thị ở trang xem chi tiết là để khách hàng chọn thuộc tính để mua.
-----------------------------------------------

Cám ơn trien đã trả lời nhé, Nhưng cho mình hỏi cái group mục đích của nó để làm gì vậy. Mình đang sử dụng nó để group lại những sản phẩm 2 CAT khác nhau mà cùng tính năng.
VD: CAT1 : LG , CAT 2: Samsung
Main Group: Loại Màn hình
Sup Group: Màn hình Led

Để người xem shop có thêm chức năng là ngoài xem theo hãng ( CAT ) còn có thể xem theo loại.

Ở đây là 1 cái website họ sử dụng module group giống ý mình : http://www.roboterwelt.de/roboter/saugroboter/

**Comment by hongoctrien** [comment]
Chào @kollersi, xin lỗi vì bây giờ mới trả lời bạn.
Mục đích của nhóm ở đây là thế này nhé, mình lấy ví dụ thế này cho dễ hiểu.
Shop mình bán áo quần, thì mỗi cái áo có 1 thuộc tính riêng.
Khi khách chọn thì chọn thuộc tính thì cừa hàng mới căn cứ vào để chuyển hàng.
![selection_159](https://cloud.githubusercontent.com/assets/6407361/6966992/c7a147c2-d986-11e4-9c5f-bc69590516ef.png)
