### ISSUE TITLE
Chức năng point bị chuyển về trang chủ của shop trong admin panel

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#172]
Như tiêu đề, khi click vào 
http://localhost/nv/admin/index.php?language=vi&nv=shops&op=point

Thì nó trả về 
http://localhost/bike/admin/index.php?language=vi&nv=shops

điều này xảy ra khi mà tắt chức năng cộng điểm trong setting. 
Nếu thế, khi tắt chức năng này thì có nên cấu hình để menu của admin cũng được vô hiệu hoá ( ẩn ) phần này đi ?

**Comment by hongoctrien** [comment]
[Fixed[(https://github.com/hongoctrien/module-shops/commit/63c3843f26311fed4aab3df29071b1d4b82f1198)
