### ISSUE TITLE
Block global.block_product_center

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#174]
Block này hiện giá giảm ở modules shop, nhưng khi xem từ modules news thì chỉ có giá chưa giảm, đồng thời có thông báo lỗi.
Nên chú ý Nên chú ý: Undefined offset: 3 in file /modules/shops/site.functions.php on line 157

Nên chú ý Nên chú ý: Undefined offset: 3 in file /modules/shops/site.functions.php on line 172

Nên chú ý Nên chú ý: Undefined offset: 1 in file /modules/shops/site.functions.php on line 255

Xampp 1.8.3, Shop Dev mới nhất từ Git.

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/module-shops/commit/fa473a912b5fe6a4a424deb8ba323c9748d15071)
