### ISSUE TITLE
Lỗi trang trắng khi xem lịch sử nhập kho trong admin

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/module-shops#175]
Khi mà chưa có nhập kho thì vào rất oke. Nhưng khi có thông tin nhập kho rồi thì vào bị trang trắng

Môi trường test: nukeviet 4.0.11 closa beta

HDH : centos 5.10
apache : 2.2
mysql 5.5
php 5.5

![trang-trang-khi-xem-nhap-kho](https://cloud.githubusercontent.com/assets/8604866/6841890/9dcc7890-d3c3-11e4-8e97-2a44d327bb16.jpg)

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/7bf8f5e5b6bc54f1680053d35beb57ac32e51c6e
