### ISSUE TITLE
tùy biến dữ liệu vẫn còn tên nhóm tồn tại trong loại sản phẩm

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/module-shops#176]
![danh-sach-tuy-bien-du-lieu-shop](https://cloud.githubusercontent.com/assets/8604866/6843022/2849648a-d3d1-11e4-91f8-ea0670fe4fe5.png)

Đây là danh sách nhóm tùy biến đã khai báo, trong đó có khai báo bao_hanh, và wifi. nhưng 2 nhóm này đã xóa. Tuy nhiên khi thêm vào loại sản phẩm thì 2 cái bao_hanh và wifi vẫn tồn tại

![xoa-nhom-tuy-bien-du-lieu](https://cloud.githubusercontent.com/assets/8604866/6843059/97c9b8aa-d3d1-11e4-89f0-ac9d1345e1c9.jpg)

**Comment by motcaiten** [comment]
Trong phần tùy biến dữ liệu. Khi thay đổi thứ tự rồi nhưng ra trang sản phẩm thì nó vẫn hiện theo thứ tự thêm .

Ví dụ : Em thêm lần lượt là tên khoa học, họ, tên phổ thông, nhưng ra trang chủ muốn hiện theo thứ tự là tên phổ thông, tên khoa học, ho. Khi thay đổi thứ tự vậy trong admin nhưng ra trang sản phẩm thì thứ tự vẫn như cũ.

![capture](https://cloud.githubusercontent.com/assets/8292355/6843371/ba5d261a-d3d4-11e4-8ea1-4e2c4f622da4.JPG)

**Comment by webvangvn** [comment]
![them tuy bi n d ng selected box thi b trang tr ng khi xem chi ti t s n ph m ngoai site](https://cloud.githubusercontent.com/assets/8604866/6843628/669aefaa-d3d7-11e4-974c-0e28850beda4.jpg)

lỗi trang trắng tiếp

**Comment by hongoctrien** [comment]
Mỗi vấn đề tạo 1 issue giúp em nhé @webvangvn

**Comment by hongoctrien** [comment]
> Đây là danh sách nhóm tùy biến đã khai báo, trong đó có khai báo bao_hanh, và wifi. nhưng 2 nhóm này đã xóa. Tuy nhiên khi thêm vào loại sản phẩm thì 2 cái bao_hanh và wifi vẫn tồn tại

[Fixed](https://github.com/nukeviet/module-shops/commit/77bbb69e7f249fa085b1ac186d7fa8bf96e47503)

**Comment by webvangvn** [comment]
http://shop.hangnhatban.com/vi/shops/Modem-Router-Wifi-Modem-3G/Wireless-G-Airstation-High-Speed-Router-Buffalo-WHR-G125-1.html  link đây em ,

**Comment by webvangvn** [comment]
vận không tự xóa được file (NV_ROOTDIR . "/themes/admin_default/modules/" . $module_file . "/cat_form_" . preg_replace( "/[-]/", "_", $template['alias'] ) . ".tpl)

Khi tạo nhóm tùy biến thì sẽ tạo file. tuy nhiên khi xóa nhóm tùy biến thì file không xóa, các file tùy biến khi tạo sẽ được gán quyền của user apache(48), user hostting không có quyền hạn xóa file do apache tạo file.

môi trường test

centos 5.10
apache 2.2
php 5.5
mysql 5.5
cpanel : koloxo

**Comment by hongoctrien** [comment]
Điền thông tin cấu hình fpt xem có giải quyết được vấn đề không @webvangvn

**Comment by hongoctrien** [comment]
> Trong phần tùy biến dữ liệu. Khi thay đổi thứ tự rồi nhưng ra trang sản phẩm thì nó vẫn hiện theo thứ tự thêm .
Ví dụ : Em thêm lần lượt là tên khoa học, họ, tên phổ thông, nhưng ra trang chủ muốn hiện theo thứ tự là tên phổ thông, tên khoa học, ho. Khi thay đổi thứ tự vậy trong admin nhưng ra trang sản phẩm thì thứ tự vẫn như cũ.

Fixed: https://github.com/nukeviet/module-shops/commit/228a4fd7fa255d795ea2e97567f79adea3396a90
