### ISSUE TITLE
Đề xuất thêm tab Thông số kỹ thuật cho sản phẩm

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/module-shops#178]
Cái tùy biến dữ liệu đang thiết kế hiện thị bên trên khung tên sản phẩm, giá cả...

mình đề xuất mở thêm bản tùy biến dữ liệu nữa nhưng cho vào tab gọi là thông số kỹ thuật của sản phẩm( để nằm cạnh tab chi tiết sản phẩm), tại vì chi tiết thông số nổi bật của sản phẩm không để lên trên được nhiều, do vậy để trong tab sẽ trình bày đẹp hơn. Mặc dù có khung chi tiết sản phẩm nhưng cứ phải đi tạo bảng thông tin kỹ thuật thì lâu lắm. mỗi sản phẩm không giống nhau. copy lại bảng rồi lại ngồi xóa từng dong chữ thì lâu. mình đã có tùy biến dữ liệu thì nên có thêm phần này cho người dùng tiện lợi hơn

**Comment by vuthao** [comment]
Đội code đã làm 1 cái đã chết vật với nó rồi bạn, ghờ bạn lại để nghị thêm cái nữa chắc chết.

Đùa vậy thôi, chứu để làm tính năng này, chúng tôi dự định sẽ sửa template cho các giao diện đó.

**Comment by hongoctrien** [comment]
Shops 4.0.15 đã thêm quản lý tabs, có quản lý thông tin từ tùy chỉnh dữ liệu, @webvangvn test lại nhé.
