### ISSUE TITLE
Không edit được số lượng tồn trong kho trong admin

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/module-shops#181]
Nếu có chức năng nhập kho thì thêm chức năng xuất kho, để còn kiểm soát số lượng tồn kho. Hoặc cho phép edit số tồn kho. Hiện nay module shop chưa cho phép điều đó, muốn giảm số tồn kho phải giải quyết băng cách đặt hàng giả thì kho mới giảm được

**Comment by vuthao** [comment]
Chức năng này là chức năng nâng cao không có trong bản mặc định của module shop
