### ISSUE TITLE
Lỗi CSS trong admin khi thêm sản phẩm

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#187]
-Các khung chọn khi thêm sản phẩm chồng nhau, không tương thích với các chế độ màn hình.
![shop](https://cloud.githubusercontent.com/assets/11238423/6892943/db15cac6-d6f2-11e4-966b-333b94b06737.png)
![don](https://cloud.githubusercontent.com/assets/11238423/6893072/007c27d2-d6f4-11e4-8806-77b0b6a6b013.png)

**Comment by vuthao** [comment]
Hiện tại mình kiểm tra lỗi này đã được fix
