### ISSUE TITLE
[Hỏi] HIển thị phần nhóm SP tại trang SP chi tiết

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#188]
Hiện phần này đang hiển thị dạng dropdown. 
Quả tình từ mấy bản trước mình thấy nó rồi, nhưng ko rõ hiện ra phần chi tiết, sao để dropdown làm gì, vì khi thử click thì ko thấy có hiệu quả hay biến chuyển gì. @.@

**Comment by hongoctrien** [comment]
Cái đó quan trọng lắm chứ @anhyeuviolet 
Nó là thuộc tính của sản phẩm mà....
VD bán một cái áo thì cần có những thông tin này cho khách chọn. Chọn đủ mới cho phép đặt hàng.

![selection_159](https://cloud.githubusercontent.com/assets/6407361/6959061/af22579c-d93e-11e4-958f-1807b8d4bd3f.png)
