### ISSUE TITLE
Thêm trường title tùy chỉnh cho chủ đề

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-shops#195]
Chủ đề shops, ngoài trường title ra cần bổ sung thêm trường title_custom để điều chỉnh tiêu đề cho SEO.

Tương tự của news /admin/index.php?language=vi&nv=news&op=cat

**Comment by ThinhNguyenVB** [comment]
Như này cũng được, nếu như để seo dùng title_custom seo hiển thị lên trên tab trình duyệt vào thẻ title
còn title mặc định của hệ thống sẽ cho vào thẻ h1 của sản phẩm, nhưng vậy tuân thủ quy định tránh nhầm lẫn nhưng trường hợp 1 site có quá nhiều sản phẩm mỗi sản phẩm lại la lá nhau mà viết tiêu đề với tiêu đề seo sẽ ra sao nhỉ?

**Comment by ThinhNguyenVB** [comment]
@hongoctrien đợi nhé, xong local rồi, đã test ok, mai đưa lên một thể :dart:

**Comment by ThinhNguyenVB** [comment]
@hongoctrien giống với cái này https://github.com/nukeviet/module-shops/issues/253 đóng vợi vào nhé
