### ISSUE TITLE
Trắng trang khi sửa "Thuộc chủ đề" của loại sản phẩm

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#197]
Bản NV 4.0.10 trên NV 4.0 Open Beta
XAMPP mới nhất.

Khi sửa chuyên mục thành chuyên mục con or từ chuyên mục con ra chuyên mục chính bị trắng trang.
Chỉ bị khi sửa phân cấp của loại SP, ko bị khi sửa các thông tin khác.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/65aff20a1bcb30cb290d88d5cb58b6905b8792cc
