### ISSUE TITLE
Không hiển thị SP trong loại SP cấp 2 trở đi ra trang chủ

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#198]
Các SP thuộc mục con thì ko được hiển thị ra trang chủ.
Ví dụ có 
+ Hàng nhập khẩu > ++ Điện thoại ++ Máy tính
+ Hàng xách tay >  ++ Điện thoại ++ Máy tính

Thì chỉ có phần hàng NK và xách tay là hiện ra. Nhưng nếu phân loại sâu hơn thì ko được. Block hiện tại cũng chưa có cơ chế lấy SP theo loại mà chỉ có theo block, cái này khá bất tiện khi chọn lựa phương án hiển thị cho trang chủ.

**Comment by anhyeuviolet** [comment]
Khi xem nhóm SP chính, nếu ko cho hiển thị ra các SP thì có thể cho hiển thị danh sách các loại SP nhỏ bên trong. :D Ý kiến thôi.

**Comment by hongoctrien** [comment]
> Block hiện tại cũng chưa có cơ chế lấy SP theo loại mà chỉ có theo block, cái này khá bất tiện khi chọn lựa phương án hiển thị cho trang chủ.

Thích là nhích thôi ^^. Có ý gì cứ issue nhé.
https://github.com/nukeviet/module-shops/issues/214

**Comment by hongoctrien** [comment]
> Các SP thuộc mục con thì ko được hiển thị ra trang chủ.

> Khi xem nhóm SP chính, nếu ko cho hiển thị ra các SP thì có thể cho hiển thị danh sách các loại SP nhỏ bên trong. :D Ý kiến thôi.

Cái này ý tưởng đã là như thế. Hiện mình test vẫn thấy nó hiển thị đúng - hiển thị cả sản phẩm của chủ đề con ra trang chủ.

@anhyeuviolet mỗi vấn đề thì tạo 1 issue cho dễ giải quyết nhé.
