### ISSUE TITLE
[Góp ý] Cơ chế giảm giá nên linh hoạt hơn

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#199]
Hiện giảm giá có sự linh hoạt nhất định là cho phép chọn theo từng SP or theo cấu hình giảm giá.
Tuy vậy ở bản hiện tại thì khi giảm giá mà ko điền khoảng SP thì ko áp dụng được mức giảm giá đó. Nhưng đôi khi ta ko nhập kho SP, theo thói quen thì ko điền số lượng vào => giảm giá ko hiệu lực.
Liệu có thể cho phép chọn giảm giá or tự điền, kiểu kiểu như dòng sự kiện của news được hay ko ?
Điều này giúp linh hoạt hơn chút ít khi cấu hình giảm giá cho SP.

**Comment by vuthao** [comment]
Tính năng này đã có rồi đúng không @hongoctrien, Cấu hình giảm giá cho từng sản phẩm theo số lượng.

**Comment by hongoctrien** [comment]
Cái này chưa có a. Ý bạn ấy là ở chổ chọn cấu hình giảm giá (lúc thêm/sửa sản phẩm), ngoài việc lựa chọn cấu hình ra thì có thể nhập luôn % giảm giá (như ở shops 3).
Phải không @anhyeuviolet ?

**Comment by hongoctrien** [comment]
@anhyeuviolet hiện đã có tùy chọn nhập kho hay không, nên cái này có thể tạo ra các gói giảm giá để chọn.
Từ sản phẩm 1 -> 99999999999 giảm giá 10% :v
