### ISSUE TITLE
Lỗi cảnh báo khi xem sản phẩm theo nhóm

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#200]
Phát sinh khi xem theo nhóm, ví dụ
localhost/nv413/group/xuat-xu/
Hoặc
http://localhost/413/group/NHAP-KHAU/

Trong đó nhóm Nhập khẩu là nhóm con của Xuất xứ.
Ở nhóm xuất xứ ko hiển thị SP, phải vào nhóm Nhập khẩu mới hiển thị SP. Vậy nếu ko hiện danh sách sản phẩm thì sao khi truy cập nhóm chính, ta ko cho nó xuất hiện danh sách các nhóm con thuộc nó, sẽ tốt hơn.

Lỗi cảnh báo Lỗi cảnh báo: Missing argument 3 for viewcat_page_list() in file /modules/shops/theme.php on line 1034

Lỗi cảnh báo Lỗi cảnh báo: Missing argument 5 for viewcat_page_list() in file /modules/shops/theme.php on line 1034

Nên chú ý Nên chú ý: Undefined variable: pages in file /modules/shops/theme.php on line 1226

**Comment by anhyeuviolet** [comment]
Khi xem ở dạng lưới, có các báo lỗi 

Lỗi cảnh báo Lỗi cảnh báo: Missing argument 3 for viewcat_page_gird() in file /modules/shops/theme.php on line 812

Lỗi cảnh báo Lỗi cảnh báo: Missing argument 5 for viewcat_page_gird() in file /modules/shops/theme.php on line 812

Nên chú ý Nên chú ý: Undefined index: promotional in file /modules/shops/theme.php on line 886

Nên chú ý Nên chú ý: Undefined index: promotional in file /modules/shops/theme.php on line 886

Nên chú ý Nên chú ý: Undefined index: promotional in file /modules/shops/theme.php on line 886

Nên chú ý Nên chú ý: Undefined index: promotional in file /modules/shops/theme.php on line 886

Nên chú ý Nên chú ý: Undefined index: promotional in file /modules/shops/theme.php on line 886

Nên chú ý Nên chú ý: Undefined variable: pages in file /modules/shops/theme.php on line 1019

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/4fffa266e2a7737b5f020edcc7475f797baff793
