### ISSUE TITLE
Lỗi hiển thị giảm giá theo số tiền ra trang chủ

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#209]
![capture](https://cloud.githubusercontent.com/assets/6290970/7023602/b3f06662-dd60-11e4-8f8f-bfe2b69b4de6.PNG)
Khi cấu hình giảm giá theo số tiền nhất định, ví dụ 2.000.000 VND, thì trang chủ hiện giá được giá đã trừ 2tr.
Nhưng ô thông báo giảm giá thì ghi là - 2.000.000%
@.@ Giảm thế này thì phải cho thêm tiền khách mất.
Shop bản 4.0.10 mới nhất.

**Comment by hongoctrien** [comment]
@anhyeuviolet gửi lên giúp mình cái bảng thông số cấu hình của bạn với.
Mình cũng thiết đặt nhưng chẳng thấy lỗi ý.

**Comment by anhyeuviolet** [comment]
![2mil](https://cloud.githubusercontent.com/assets/6290970/7085459/0fbac0cc-dfa1-11e4-9150-a68e46eb3708.PNG) Đây nè @hongoctrien 
:D Mình chả hiểu sao nữa.

**Comment by hongoctrien** [comment]
Ai chà chà

![selection_169](https://cloud.githubusercontent.com/assets/6407361/7086013/84f68d8a-dfa6-11e4-819d-2fecb57c5e97.png)
![selection_168](https://cloud.githubusercontent.com/assets/6407361/7086014/85204774-dfa6-11e4-9899-486e0ae39145.png)

**Comment by anhyeuviolet** [comment]
Ca này khó. Thử đi thử lại mà vẫn lỗi :((

**Comment by hongoctrien** [comment]
Teamview nha.
Pm vào đây luôn với https://www.facebook.com/hntrien

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/cfd6927eb21af57512b80edee8173b1d7123b043
