### ISSUE TITLE
Lỗi thêm sản phẩm

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#211]
Mình tải bản mới nhất về thấy mấy lỗi sau : 
Thứ 1 : Lúc thêm sản phầm mới không có trường số lượng sản phẩm để nhập số lượng vào. 

Thứ 2 : Tuy để giá là liên hệ nhưng khi ra xem chi tiết sản phẩm vẫn xuất hiện số lượng sản phẩm.

Thứ 3 : Trong tùy biến dữ liệu khi add nhóm dữ liệu vào loại sản phẩm. Khi thêm sản phẩm nếu không ghi vào các trường dữ liệu thì ra trang chi tiết sản phẩm nó vẫn hiện.

![1](https://cloud.githubusercontent.com/assets/8292355/7042854/103edf58-de0f-11e4-859e-85888faf2b45.PNG)
![2](https://cloud.githubusercontent.com/assets/8292355/7042855/1045036a-de0f-11e4-8acd-25feb02f8495.PNG)

**Comment by anhyeuviolet** [comment]
2 cái sau thì ko biết. Còn cái số 1 thì phải thông qua chức năng nhập kho bạn ạ.

**Comment by motcaiten** [comment]
Chức năng nhập kho bị trắng trang thì sao nhập được bác ơi.

**Comment by hongoctrien** [comment]
> Thứ 1 : Lúc thêm sản phầm mới không có trường số lượng sản phẩm để nhập số lượng vào.

Cái này như @anhyeuviolet nói, mình sẽ thêm tùy chọn sau để có thể nhập số lượng không cần qua nhập kho.

> Thứ 2 : Tuy để giá là liên hệ nhưng khi ra xem chi tiết sản phẩm vẫn xuất hiện số lượng sản phẩm.

Fixed: https://github.com/nukeviet/module-shops/commit/621f2f5cec79007bb40ed403729a8a3696d48405

> Thứ 3 : Trong tùy biến dữ liệu khi add nhóm dữ liệu vào loại sản phẩm. Khi thêm sản phẩm nếu không ghi vào các trường dữ liệu thì ra trang chi tiết sản phẩm nó vẫn hiện.

Fixed: https://github.com/nukeviet/module-shops/commit/9fab27d8e66bcc6d187686ce5fce23b9372a7ec3
