### ISSUE TITLE
Lổi không hiển thi sản phẩm  Theo nhóm sản phẩm

### ISSUE THREAD

**Issue by lttin2011** [nukeviet/module-shops#217]
Lổi Module Shops 4.0.10 Dùng cho NukeViet 4 Openbeta.
Lúc chọn hiển thị theo nhóm sản phẩm nukeviet thì xem ngoài site nó trắng trơn ko có một sản phẩm. Mặc dù đả Thêm nhóm sản phẩm và đả thêm sản phẩm đầy đủ.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/4fffa266e2a7737b5f020edcc7475f797baff793
