### ISSUE TITLE
Lỗi nhập kho

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#218]
Nhấn vào nhập kho hay lịch sử nhập kho ra trang trắng.

**Comment by vuthao** [comment]
@motcaiten Vui lòng xem lại quy định báo lỗi. 

Không phải chúng tôi đặt ra quy định giở hơi đâu. Muốn kiểm tra đươck lỗi thì chúng tôi cần có môi trường thử nghiệm giống bạn, chứ lúc làm chúng tôi đã  kiểm tra chán rồi.
