### ISSUE TITLE
Block product_center bị đơ trên mobile

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-shops#220]
Block này bị đơ trên mobile, chạm vào nó không chạy ra link, nhưng chạm và giữ giống như bấm chuột phải trên windows thì ok, demo http://utbeo.com

**Comment by anhutbeo** [comment]
Mình test trên cả IOS và Adroid, kể cái cái slide tin tức được code từ block product_center cũng bị

**Comment by vuthao** [comment]
@anhutbeo Vui lòng xem lại quy định báo lỗi.

Không phải chúng tôi đặt ra quy định giở hơi đâu. Muốn kiểm tra đươck lỗi thì chúng tôi cần có môi trường thử nghiệm giống bạn, chứ lúc làm chúng tôi đã kiểm tra chán rồi.
