### ISSUE TITLE
Thiếu group của sản phẩm module shop

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#221]
Hiện tại khi đăng không thấy có group, vào kiểm tra sản phẩm trong phpmyadmin ko có trường đó để thực hiện việc cho sản phẩm vào nhóm nếu cần
-> cần bổ sung nhóm sản phẩm khi đăng sản phẩm

**Comment by hongoctrien** [comment]
Quy trình thêm nhóm sản phẩm:
1. Quản lý nhóm sản phẩm, thêm nhóm mới, chú ý phần **"Của loại sản phẩm"**
2. Thêm sản phẩm mới (hoặc sửa), chọn Loại sản phẩm (ứng với mỗi loại sản phẩm sẽ hiển thị các nhóm tương ứng cấu hình khi thêm nhóm), các nhóm hiển thị ở cuối trang, phía dưới ô **Khuyến mại**
