### ISSUE TITLE
Lỗi nhập kho

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#224]
Khi chọn nhập kho và lịch sử nhập kho đều ra trang trắng

Môi trường thử Nghiệm: hosting
+ Phiên bản shop : 4.0.11
+ Hệ điều hành: Linux
+ Trình duyệt web: chrome, firefox
+ Công cụ quản lý hosting:  DirectAdmin 1.47.0
+ PHP phiên bản 5.3.29
+ Mysql 5.5.31
+ Apache 2.2.29

**Comment by hongoctrien** [comment]
Không biết bạn cài shops 4.0.11 cùng phiên bản NukeViet bao nhiêu ạ?
Bạn cài Shops 4.0.11 cùng NukeViet 4.0.14 rồi test lại lỗi này giúp mình nhé.

**Comment by motcaiten** [comment]
Em cài nukeviet bản mới nhất rồi đó anh.
