### ISSUE TITLE
Về cơ chế đặt hàng trên shop 4.0.11

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#226]
Các mô tả sau nói về Modules shop 4.0.11 chạy trên NukeViet 4.0.14, máy chủ XAMPP 1.8.3

+++ Cơ chế để đặt hàng hiện hoạt động cùng với điều kiện hiển thị giá. 
Hiện shops có 2 cơ chế cấu hình hiển thị giá. 1 trong modules và 1 trong sp chi tiết, phần tính năng mở rộng. Nếu phần hiển thị giá trong chi tiết sp uncheck thì khi ra trang chủ sẽ không đặt hàng được (không thấy nút đặt hàng).

+++ Về chọn nhóm sp để đặt hàng.
Cá nhân mình thấy cách hiển thị như cũ ( dropdown box ) khá hay vì nó tiết kiểm không gian hơn. Dạng label hiển tại nhìn đẹp nhưng nếu 1 sp có nhiều thuộc tính tuỳ chọn thì nó sẽ rất bừa bãi, vì bên trên lại còn phần link đến các group chứa nữa.

**Comment by hongoctrien** [comment]
> Hiện shops có 2 cơ chế cấu hình hiển thị giá. 1 trong modules và 1 trong sp chi tiết, phần tính năng mở rộng. Nếu phần hiển thị giá trong chi tiết sp uncheck thì khi ra trang chủ sẽ không đặt hàng được (không thấy nút đặt hàng).

Ý tưởng của cái này là như thế, nếu không hiển thị giá thì đồng nghĩa với việc khách tư liên hệ (Dùng có các website giới thiệu sản phẩm, chứ không phải là thương mại).

> Cá nhân mình thấy cách hiển thị như cũ ( dropdown box ) khá hay vì nó tiết kiểm không gian hơn. Dạng label hiển tại nhìn đẹp nhưng nếu 1 sp có nhiều thuộc tính tuỳ chọn thì nó sẽ rất bừa bãi, vì bên trên lại còn phần link đến các group chứa nữa.

Việc thay đổi lại kiểu label hiện tại mình có suy đi tính lại. Dùng combobox hạn chế tầm nhìn của khach hàng đối với tất cả các nhóm. Dùng label hiện tại nó hiển thị ra hết, dễ nhìn và chọn hơn.

**Comment by anhyeuviolet** [comment]
Cơ chế để đặt hàng hiện hoạt động cùng với điều kiện hiển thị giá. 
Về phần cái này, ý là mình muốn khi ko hiển thị giá thì KH vẫn có 1 nút gọi là " Yêu cầu báo giá". Khi đó thì người bán hàng vẫn nhận được yêu cầu và gửi báo giá cho KH. 
Hiện tại thì ẩn luôn, KH sẽ liên hệ qua đt, nhưng trong vài trường hợp nó ko tiện cho lắm.

**Comment by hongoctrien** [comment]
ak :D. Thế thì tạo giúp mình 1 issue yêu cầu thêm nút "Yêu cầu báo giá" nhé.
Cái này chắc cũng là một chức năng chính luôn chứ chẳng phải là phụ.
Nói thế luôn cho nó nhanh ^^
