### ISSUE TITLE
Lỗi trắng trang khi xem nhóm SP

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#227]
Các mô tả sau nói về Modules shop 4.0.11 chạy trên NukeViet 4.0.14, máy chủ XAMPP 1.8.3

Khi click vào nhóm SP ( trong trang chi tiết ) thì bị trắng trang.
Link có dạng http://localhost/414/shops/group/2-nguoi/

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/19a4a293c0f648477e46689a39b0d12e10802d58
