### ISSUE TITLE
Về cơ chế nhập kho trên shop 4.0.11

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#228]
Hiện mình thấy chức năng này là khá cần thiết đối với các trang bán hàng là SP. Nhưng nếu trang cung cấp dịch vụ thì ko ổn lắm. Vì mấy cái đó ko cần nhập kho. Đôi khi chỉ cần lấy thông tin yêu cầu của KH để liên hệ lấy giá là đủ.

**Comment by hongoctrien** [comment]
Sẽ thêm cấu hình sử dụng nhập kho.

**Comment by vanthangnd254** [comment]
Mình thấy chức năng này có thể chọn ngay ở mục thêm sản phẩm thì hay hơn, chứ thấy bản shop 4 phải làm thêm 1 bước nhập kho ở ngoài nữa làm mất thời gian mà rườm rà hơn

**Comment by hongoctrien** [comment]
Cái này đã thêm tùy chọn rồi nhé. Các bạn download bản đang phát triển về dùng thử.
Có thể bật / tắt nhập kho ở Cấu hình module.
Khi bật nhập kho thì phải chọn nhập kho ở ngoài, ngược lại có thể nhập số lượng sản phẩm khi thêm sản phẩm, như các bản cũ.
