### ISSUE TITLE
Về cơ chế phí vẫn chuyển trên shop 4.0.11

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#229]
Trước đây mình có ý kiến là nếu chức năng nào bị vô hiệu quá trong modules setting thì menu bên phải liệu có thể ẩn luôn menu đó được hay ko ? Tương ứng đối với phần chi tiết sp khi thêm SP mới.
Vì hiện khi thêm sp, các khoản mục khá dàn trải, nếu ko dùng đến nhưng nó vẫn nằm đó thì khá là ... phiền.
Hy vọng cái này có thể tối ưu hơn trong phiên bản tiếp theo.

**Comment by hongoctrien** [comment]
Hiện mình đã thêm cấu hình (on/off) cho chức năng nhận quà tặng https://github.com/nukeviet/module-shops/commit/0599dc7e30de29a61c03e47012c61dedcf3a7c39, ẩn group https://github.com/nukeviet/module-shops/commit/e26d15e5399e2dfe2bd538d9276e96f2d6fa0478 nếu không sử dụng.
Còn chổ nào @anhyeuviolet góp ý thêm nhé.
