### ISSUE TITLE
Không tự động redirect khi xóa giỏ hàng

### ISSUE THREAD

**Issue by tuanchung24** [nukeviet/module-shops#230]
Tại File "module-shops/modules/shops/funcs/remove.php"
Mình thấy đang "echo $id;" nên khi bỏ ra khỏi giỏ hàng thì sẽ k redirect mà in ra ID

**Comment by hongoctrien** [comment]
File nó chỉ dùng để xử lý gửi từ ajax, nên giá trị in ra nó không hiển thị.
Ý bạn là khi xóa hết hàng đi sẽ redirect về trang chủ?

**Comment by tuanchung24** [comment]
Hôm trước mình test code thấy nó k tự redirect bạn ạ :D

**Comment by hongoctrien** [comment]
>  k tự redirect bạn ạ

Là sao bạn? Mô tả rõ chổ này mình với.
