### ISSUE TITLE
[góp ý]ảnh hưởng việc xếp hạng do bị khóa 1 số file JS

### ISSUE THREAD

**Issue by thangvn** [nukeviet/module-shops#236]
Mình vào Google webmaster tools , trong phần Blocked resource thì thấy báo là có 50 trang được quét nhưng phát hiện có file bị chặn ( nghĩa là không quét được những file này trong trang này)

Mình kiểm tra thì thấy đó là các file user.js,tabresponsive.js.

Nó nằm thuộc trong các module shop/js,contact/js

Google nói rằng nên chỉnh lại file robot.txt để cho truy cập các file này,điếu đó tốt hơn cho việc xếp hạng.

Đây là link Google nói về việc này : https://support.google.com/webmasters/answer/6153277

Mong ban quản trị sửa lại file robot.txt để cho phép truy cập các file này.

**Comment by anhyeuviolet** [comment]
Xác nhận.
Hiện nay Bot Google đã render được hầu như toàn bộ CSS và JS.
Do đó không nhất thiết phải chặn trong robots nữa, sẽ ảnh hưởng đến kết quả khi bot Google quét qua.

**Comment by hongoctrien** [comment]
Cái này là sao anh @vuthao

**Comment by vuthao** [comment]
NukeViet 4 đã cung cấp sẵn tính năng này rồi nhé; admin/index.php?language=vi&nv=seotools&op=robots.

Muốn chặn hay mở các bạn tự cầu hình cho site mình. Khi cài đặt chúng tôi đã thiết lập chuẩn cho cái này. Tốt nhất là không cho nó vào trong đó.
