### ISSUE TITLE
Đề xuất , Block filter theo tính năng

### ISSUE THREAD

**Issue by kollersi** [nukeviet/module-shops#239]
Hiện tại mình thấy modules shop còn thiếu filter theo tính năng, hoặc chất liệu. Ví dụ vào MAIN CAT Áo Nam mình tạo 1 Group là ( Ao Jean, Áo Thun, Áo Vải..)  Qua MAIN CAT Áo nữ lại lặp lại các mục đó, mình thấy nó tương tự cái chức năng nhóm hiện có, nhưng chức năng nhóm hiện có nhưng khi order nó lại hiện ra để chọn order thì ko phù hợp lắm.

**Comment by hongoctrien** [comment]
Chào bạn ạ.
Vấn đề của bạn, shops đã có cấu hình, song chưa phát hành chính thức nên chưa có tài liệu hướng dẫn chi tiết.
Bạn vào Quản lý Nhóm sản phẩm, nếu không muốn nhóm hiển thị khi đặt hàng thì "Hiển thị khi đặt hàng" bạn chọn là "Không"

**Comment by kollersi** [comment]
@hongoctrien Ý mình là tính năng đặt hàng theo  nhóm của bạn đang tao cũng rất hay. Có thể tạo thêm 1 nhóm mới nữa không. vì 2 tính năng khác nhau. Ví dụ :  trang này : http://www.roboterwelt.de/roboter/saugroboter/ bạn chú ý bên menu trái. Bạn có thể cho mình số dt , hoặc skype hay viber whatsapp được không để nói cho bạn dễ hiểu hơn : DT cua minh 0909 996 119

**Comment by hongoctrien** [comment]
Bạn cũng có thể tạo thêm nhiều nhóm mới mà?
