### ISSUE TITLE
Đặt hàng ngoài trang chủ, hủy bỏ bằng esc. Click chuột đặt hàng lại thì không được nữa

### ISSUE THREAD

**Issue by aothunit** [nukeviet/module-shops#241]
Module shop sau khi khách đặt hàng mà k mua , nhấn Esc . Sau đó load lại trang web thì không đặt được hàng ở ngoài trang chủ nữa a ơi, admin phải dọn lại hệ thống mới đặt được bt

**Comment by hongoctrien** [comment]
Bạn mô tả rõ hơn chổ này giúp mình với ạ?

**Comment by hongoctrien** [comment]
@aothunit mình có test y như bạn mô tả. Nhưng không thấy lỗi. 
Bạn download code mới nhất về test lại giúp mình nhé. Nếu vẫn còn lỗi thì pm lại teamview mình kiểm tra luôn xem sao.
Cảm ơn bạn!

**Comment by dtsoncntt** [comment]
của mình cũng bị lỗi y như thế này . bản Open beta 1

**Comment by hongoctrien** [comment]
Lỗi này đã fix trong bản tới nhé.
