### ISSUE TITLE
Bổ sung dữ liệu module shop

### ISSUE THREAD

**Issue by dtsoncntt** [nukeviet/module-shops#243]
thêm 1 trường để nhập thông tin chính sách bảo hảnh / đổi / trả / điều kiện đổi trả ở trong giao diện admin đăng sản phẩm,.tương tự bodytext hoặc hometext . Vì mỗi mặt hàng có chính sách bảo hành, điều kiện ... khác nhau nên cái này rất cần cho module shop.
Cấu hình hiển thị thêm 1 tab cạnh chi tiết sản phẩm

**Comment by vuthao** [comment]
cái này dùng tùy biến dữ liệu đi các bác.

**Comment by dtsoncntt** [comment]
Nhưng mà bác có bài hướng dẫn tùy biến dữ liệu cho bọn em nhanh đi . cả làng thắc mắc cái tùy biến dữ liệu là cái gì , dùng để làm gì , sử dụng ra sao kia kìa @vuthao

**Comment by hongoctrien** [comment]
Bạn xem issue này nhé, mình có trả lời qua đó.
https://github.com/nukeviet/module-shops/issues/163
