### ISSUE TITLE
global block_catalogs đang bị lỗi và cần nâng cấp

### ISSUE THREAD

**Issue by vanthangnd254** [nukeviet/module-shops#252]
Thứ nhất: Như tiêu đề khi sử dụng global block_catalogs thì bị lỗi khi có menu con mà mình rê chuột vào thì nó bị nhảy nhìn rất xấu.
Thứ hai: Nếu được thì global block_catalogs này nên chia ra làm 2 kiểu hiển thị
   -  1 là khi rê chuột vào menu cha thì menu con sẽ xuất hiện ở dưới menu cha.
   -  2 là khi rê chuột vào menu cha thì menu con sẽ xuất hiện ở bên phải menu cha.
Mình thấy trong đó có 2 kiểu hiển thị là vertical và horizontal, nếu mỗi kiểu hiển thị theo như yêu cầu số 2 của mình thì khỏi chê.
Mong đội code sẽ sớm chỉnh sửa và nâng cấp lên bản hoàn thiện cho tiện người dùng.
Xin cám ơn.

**Comment by hongoctrien** [comment]
Menu này thiết kế cho theme dedault. Nếu ban dùng theme khác thì phải chỉnh sửa lại cho phù hợp với theme nhé.

**Comment by vanthangnd254** [comment]
mình cũng sử dụng theme default mà, bạn coi fix lại giùm nha, để cho phien bản sau hoàn chỉnh hơn.
Thanks
