### ISSUE TITLE
Lỗi thêm tag

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/module-shops#259]
Khi dùng đa ngôn ngữ, thêm tag ở tiếng việt => tự động thêm tag ở tiếng anh, nhưng là tag rỗng nội dung. Thêm tag tiếp ở tiếng việt sẽ không thêm được.

**Comment by vuthao** [comment]
Hiện tại đã tách riêng phần tag riêng cho mỗi ngôn ngữ.
