### ISSUE TITLE
Lỗi vỡ hình

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-shops#260]
Khi thêm sản phẩm thứ 2 trở lên thì bị lỗi hiển thị như hình, nếu 1 sản phẩm thì nó không bị
![loi](https://cloud.githubusercontent.com/assets/10916826/7786481/d5e0ff82-01fc-11e5-94f6-f8946f94d4e5.png)

Môi trường thử Nghiệm
- Phiên bản NukeViet: 4.0.16 đến bản mới nhất đều bị
- Phiên bản shop: Mới nhất
- Hệ điều hành: win 8 64 bit
- Trình duyệt web: Chroom
- Máy chủ web: Wamsever
- Apache/2.4.4 (Win32) PHP/5.4.16

**Comment by anhutbeo** [comment]
Khi xem chi tiết sản phẩm nó cũng bị
![2015-05-24_101629](https://cloud.githubusercontent.com/assets/10916826/7786501/03710ce8-01fe-11e5-9256-ab868ce60c94.png)

**Comment by hongoctrien** [comment]
@anhutbeo 
Cho mình xin dòng tiêu đề, mô tả sản phẩm bạn nhập vào với.

**Comment by anhutbeo** [comment]
Sản phẩm thứ 1 tiêu đề là:
Sweet love
Mô tả là:
Sweet love được thiết kế với tông màu ngọt ngào của hồng đỏ, của cúc hồng, mõm sói hồng và nhấn nhá thêm một chiếc nơ xinh xắn sẽ là món quà ngọt ngào dành cho những người mà bạn yêu thương.

Sản phẩm thứ 2 tiêu đề là:
 Memory Of Love
Mô tả là:
Memory Of Love - bó hoa của những dịu dàng, những ngây thơ và cả những hoài niệm về giây phút đầu gặp gỡ. Memory Of Love cứ tự nhiên và đằm thắm mà gợi nên biết bao xúc cảm trong lòng người nhận, và rồi, cũng tự nhiên như thế, nụ cười của hạnh phúc bất chợt nở trên môi.

 Sản phẩm thứ 3 tiêu đề là:
 Hồng Phấn
Mô tả là:
Bao nét đẹp của hoa Hồng Phấn đã được bộc lộ hết qua mẫu thiết kế này. Sự nhẹ nhàng, dịu dàng của bông hoa cũng chính như hình ảnh của người nhận vậy.

**Comment by hongoctrien** [comment]
Fixed https://github.com/nukeviet/module-shops/commit/8bd2bf5d6616e5f4df45ca73ddfb57d62e4a7aa4
