### ISSUE TITLE
Lỗi tìm kiếm modules shop ở themes modern

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/module-shops#262]
- Phiên bản NukeViet: 4.0.16
    - Môi trường thử Nghiệm: Localhost
    - Hệ điều hành: windows 7 64 bits
    - Trình duyệt web: Mozilla Firefox 38.0.1, Google Crome 43.0.2357.65 m
    - Máy chủ web: XAMPP for windows 1.8.3 )
    - Tên gói giao diện Modern
Khi thực hiện tìm kiếm sản phẩm thì website báo lỗi trang không tồn tại
![image](https://cloud.githubusercontent.com/assets/10495040/7791024/3e887d10-02c2-11e5-9479-ff9081bc7ea2.png)

**Comment by vuthao** [comment]
Hiện tại chúng tôi đã dừng phát triển  themes modern
