### ISSUE TITLE
Lỗi trang đặt hàng

### ISSUE THREAD

**Issue by macsoftnet** [nukeviet/module-shops#268]
![loi-dat-hang](https://cloud.githubusercontent.com/assets/7893100/7799940/ecac8fee-033f-11e5-9ed7-a0eb8a742889.png)

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/42291a367c1c422ae38abb429c6078a279ce42a7

Bạn cấu hình trước khi sử dụng dịch vụ vận chuyển nhé.
