### ISSUE TITLE
Lỗi block sản phẩm

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#274]
Khi vào phần block sản phẩm để thêm 1 sản phẩm vào block thì bị load về http://domain.com/admin/index.php

**Comment by hongoctrien** [comment]
![selection_308](https://cloud.githubusercontent.com/assets/6407361/7904709/372d2ac4-0831-11e5-904f-51e492ba522a.png)

Phải chổ này không @motcaiten 
Nếu phải thì cho mình các thông số theo như yêu cầu tại https://github.com/nukeviet/module-shops/blob/develop/CONTRIBUTING.md
Mình test ở đây không thấy lỗi.

**Comment by motcaiten** [comment]
Hiện tại đã ok. Nhờ anh đóng issues này lại.
