### ISSUE TITLE
Đề xuất cho shops

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-shops#276]
+ Trong phần đăng sản phẩm có đơn vị Khối lượng. nên cho tùy chọn điền hoặc không điền vào khối lượng, hiện tại nó bắt buột phải điền. 
+ Trong phần "Nhóm sản phẩm" khi hiện thị ở ngoài site khi xem 1 sản phẩm nó hiện ở 2 nơi, nên xóa bớt và nên để link vào nhóm để xem nhóm sản phẩm đó cho tiện
+ Phần số lượng sản phẩm cũng nên có tùy chọn là "nhiều" hoặc không giới hạn sản phẩm.
Ý kiến cá nhân mình thôi :)))

![faststoneeditor](https://cloud.githubusercontent.com/assets/10916826/7828461/0055ed96-045e-11e5-97ea-7a6d6e025d09.png)

**Comment by hongoctrien** [comment]
>Trong phần đăng sản phẩm có đơn vị Khối lượng. nên cho tùy chọn điền hoặc không điền vào khối lượng, hiện tại nó bắt buột phải điền.

Khi bật chức năng vận chuyển thì bắt buộc điển khối lượng, tắt vận chuyển đi thì không cần điền.

>Trong phần "Nhóm sản phẩm" khi hiện thị ở ngoài site khi xem 1 sản phẩm nó hiện ở 2 nơi, nên xóa bớt và nên để link vào nhóm để xem nhóm sản phẩm đó cho tiện

Trong quản lý nhóm sản phẩm, 
- "Hiển thị cùng sản phẩm" => Hiển thị ở vòng tròn bên trên
- "Hiển thị khi đặt hàng" => Hiển thị ở vòng bên dưới

>Phần số lượng sản phẩm cũng nên có tùy chọn là "nhiều" hoặc không giới hạn sản phẩm. Ý kiến cá nhân mình thôi :)))

Không cần thiết ạ. Trong cấu hình module có tùy chọn "Đăt hàng không giới hạn số lượng"
