### ISSUE TITLE
Module shops 4.0.14 lỗi trắng tinh 

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/module-shops#277]
Sau khi cài đặt Module shops 4.0.14 lỗi trắng tinh khi click Shops trong Admin. Hệ thống báo lỗi : Nên chú ý: Undefined index: use_shipping in file /modules/shops/admin.menu.php on line 23
Nên chú ý: Undefined index: review_active in file /modules/shops/admin.menu.php on line 30
Nên chú ý: Undefined index: active_warehouse in file /modules/shops/admin.menu.php on line 35
Nên chú ý: Undefined index: use_coupons in file /modules/shops/admin.menu.php on line 44
Nên chú ý: Undefined index: point_active in file /modules/shops/admin.menu.php on line 49

**Comment by vietnamxinchao** [comment]
Sau khi cài đặt tôi bị lỗi Stop!!!

**Comment by hongoctrien** [comment]
@duongGitHub @vietnamxinchao  pm teamview mình xem nhé.
https://www.facebook.com/hntrien

**Comment by duongGitHub** [comment]
Help me!

**Comment by hongoctrien** [comment]
Bạn download shops 4.0.14 + NukeViet 4.0.17 cài đặt mới xem bạn

**Comment by duongGitHub** [comment]
Thì mình cài module shops 4.0.14  và NukeViet 4.0.17 mới nhất ấy, Mình chưa hề thêm bớt hay xóa gì cả. Và cũng chưa cài thêm bất kỳ module nào khác. Bạn xem giúp

**Comment by hongoctrien** [comment]
Bạn gửi tamview mình xem thử

**Comment by duongGitHub** [comment]
Bạn hương dẫn giúp, bằng cách nào? Mình mở teamvieaw

**Comment by hongoctrien** [comment]
https://www.facebook.com/hntrien

**Comment by duongGitHub** [comment]
vô facebook rồi sao nữa, mình không rành?

**Comment by hongoctrien** [comment]
^^ gửi ID teamview vào tin nhắn facebook cho mình

**Comment by duongGitHub** [comment]
Mình đã xóa, bạn đợi 1 tí để mình cài lại module shop

**Comment by duongGitHub** [comment]
Ban check tin nhan

**Comment by hongoctrien** [comment]
Không thấy tin nhắn bạn?

**Comment by duongGitHub** [comment]
Roi ban, gui lai roi

**Comment by hongoctrien** [comment]
Bạn gửi ở đâu mình không thấy. Gửi lên đây cũng được.

**Comment by duongGitHub** [comment]
Mình gửi ở đây mà https://www.facebook.com/hntrien

**Comment by duongGitHub** [comment]
cho xin so di dong cua ban?

**Comment by hongoctrien** [comment]
Không biết nữa, mình không thấy tin nhắn trên face. Gửi lên dây cũng được bạn.

**Comment by duongGitHub** [comment]
Có an toàn không?

**Comment by duongGitHub** [comment]
Di dong của mình : 0905347172

**Comment by hongoctrien** [comment]
An toàn, ko sao đâu. Nhanh chứ mình còn làm việc. hix

**Comment by duongGitHub** [comment]
661 911 718
8733

**Comment by duongGitHub** [comment]
Thanks, bạn giỏi thật!

**Comment by hongoctrien** [comment]
Cái này thực ra là lỗi. Trên các phiên bản mysql khác nhau nó lỗi khác nhau. Như mysql mình dùng thì không bị lỗi này, của bạn thì bị :D.
