### ISSUE TITLE
Báo một số lỗi trong module shop

### ISSUE THREAD

**Issue by tkhuyenbk** [nukeviet/module-shops#281]
1. Sửa danh mục sản phẩm cụ thể từ danh mục đẩy vào danh mục con: lưu lại thì trắng xóa nhưng mở lại thì cũng đã sửa.
2. Đơn vị sản phẩm là chiếc, nhưng khi nhập sản phẩm cứ bắt nhập Khối lượng là bao nhiêu.

**Comment by hongoctrien** [comment]
>Sửa danh mục sản phẩm cụ thể từ danh mục đẩy vào danh mục con: lưu lại thì trắng xóa nhưng mở lại thì cũng đã sửa.

Bạn cung cấp giúp mình các thông tin liên quan
https://github.com/nukeviet/module-shops/blob/develop/CONTRIBUTING.md

>Đơn vị sản phẩm là chiếc, nhưng khi nhập sản phẩm cứ bắt nhập Khối lượng là bao nhiêu.

Khối lượng bắt buộc nhập khi kích hoạt chức năng vận chuyển. Bạn vào cấu hình module, bỏ check ở "Sử dụng dịch vụ vận chuyển"
