### ISSUE TITLE
Module shops 4.0.14 báo: Lỗi hệ thống không cập nhật được nội dung.

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/module-shops#282]
Khi đăng sản phẩm hệ thống báo: Lỗi hệ thống không cập nhật được nội dung. Mình dùng:
- Phiên bản NukeViet: 4.0.17
- Môi trường thử Nghiệm: Localhost
- Hệ điều hành: Win 7
- Trình duyệt web: Chrome
- Máy chủ web: VertrigoServ 231

**Comment by hongoctrien** [comment]
Gửi teamview luôn nhé, mình kiểm tra cho tiện.

**Comment by duongGitHub** [comment]
Ok làm phiền bạn 1 lần nữa
ID: 661 911 718
Pass: 6604

**Comment by duongGitHub** [comment]
Thanks nhieu!

**Comment by hongoctrien** [comment]
Fixed https://github.com/nukeviet/module-shops/commit/d1c925f8aa9f2611da726e0341f574e6d293af3c

**Comment by hongoctrien** [comment]
Lỗi không sửa dc menu bạn post lên forum hoặc face nhé.

**Comment by duongGitHub** [comment]
Ok thanks http://forum.nukeviet.vn/viewtopic.php?f=171&t=35597

**Comment by ccu1tn** [comment]
Các bạn ơi. Mình cũng bị như vậy. Tuần trước thì vẫn đăng sản phẩm bình thường. 
Hôm nay vô đăng tiếp thì bị lỗi 
![image](https://user-images.githubusercontent.com/43333942/69392042-a0b35800-0d0f-11ea-8746-28783f888654.png)
NukeViet version 4.3.05
Phiên bản PHP : 5.6.40 
Trình duyệt: Google chorme

Mọi người giúp mình với. thank cả nhà nhà

**Comment by hoaquynhtim99** [comment]
@ccu1tn đã có sửa lỗi ở đây bạn, đọc commet bên trên đi https://github.com/nukeviet/module-shops/commit/d1c925f8aa9f2611da726e0341f574e6d293af3c

**Comment by ccu1tn** [comment]
@hoaquynhtim99 bạn ơi. Mình sửa theo như trên hướng dẫn nhưng vẫn không được.
