### ISSUE TITLE
Góp ý về cấu hình shop

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#286]
Theo mình nên bỏ phần khối lượng sản phẩm. Nó không đáp ứng cho nhiều shop, phiền hà khi nhập liệu. Chả nhẽ 1 lẵng hoa tươi cũng phải nhập khối lượng? Hoặc thêm tùy chọn cho cấu hình này.

**Comment by hongoctrien** [comment]
Nếu bật chức năng vận chuyển, thì bắt buộc nhập khối lượng (Có khối lượng mới tính giá vận chuyển được).
Vào cấu hình chung, tắt chức năng vận chuyển đi nhé.
