### ISSUE TITLE
Ý kiến bổ sung cho shop khi xem chi tiết sản phẩm

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#290]
Mình xin bổ sung thêm chức năng hiển thị hình ảnh sản phẩm tiếp theo trong cùng một sản phẩm như hình bên dưới, mong đội code nghiên cứu bổ sung,
![zoom-hinh](https://cloud.githubusercontent.com/assets/11238423/7899972/c6375482-0765-11e5-8423-241d8ec6df69.png)

**Comment by hongoctrien** [comment]
Shops mặc định chỉ nên hiển thị hiệu ứng đơn giản như hiện tại. Những hiệu ứng như thế này các bạn tự điều chỉnh nhé.
