### ISSUE TITLE
cảnh báo khi chọn thêm module ảo

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/module-shops#296]
![image](https://cloud.githubusercontent.com/assets/10300770/7933373/e36a8918-0948-11e5-9035-77c95f1de859.png)

**Comment by hongoctrien** [comment]
@Cập nhật lại bản mới nhất nhé

**Comment by htuyen1994** [comment]
e pull mới rồi a

**Comment by hongoctrien** [comment]
Cài lại module chưa @htuyen1994

**Comment by vuthao** [comment]
lỗi hiện tại đã được sửa.
