### ISSUE TITLE
Lỗi tùy biến dữ liệu và quản lí dữ liệu

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#297]
Hiện tại khi thêm tùy biến dữ liệu thì được nhưng sau đó trang quản trị bị trắng trang. Trong chi tiết sản phẩm không hiện.

Test trên localhost thấy trong phần quản lí dữ liệu khi thêm dữ liệu vào đều bị báo là đường dẫn tin không hợp lệ.

Phiên bản NukeViet	4.0.17
Phiên bản Shop 4.0.14 (bản mới nhất)
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.6.8, apache2handler
Hệ điều hành máy chủ	WINDOWS NT
Phiên bản Database	mysql 5.6.24

**Comment by hongoctrien** [comment]
@motcaiten  kiểm tra lại trên bản mới nhất mình với nhé. Mình kiểm tra khong thấy lỗi.
