### ISSUE TITLE
Lỗi trang trắng

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/module-shops#298]
Hiệp tại mình cài bản mới nhất xuất hiện lỗi trang trắng khi click vào menu shops trong admin
file main.php
// Tong so luong binh luan
$number = $db->query( 'SELECT COUNT(*) FROM ' . NV_PREFIXLANG . '_comments WHERE module=' . $db->quote( $module_name ) )->fetchColumn();
$array_info[] = array(
	'title' => $lang_module['product_number_commet'],
	'value' => $number,
	'link' => NV_BASE_ADMINURL . 'index.php?' . NV_LANG_VARIABLE . '=' . NV_LANG_DATA . '&amp;' . NV_NAME_VARIABLE . '=comment&amp;module=' . $module_name,
	'unit' => $lang_module['product_comment']
);
-----------------
Lỗi mất bình luận

**Comment by vuthao** [comment]
Lỗi này hiện tại đã được sửa cho bản shop và Nukeviet hiện tại
