### ISSUE TITLE
Lỗi quà tặng của module shops

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#301]
Module shops hiện lỗi của phần quà tặng gift
gift_content in file /modules/shops/theme.php on line 509

**Comment by hongoctrien** [comment]
Sau anh gắng mô tả chi tiết hơn xí, cụ thể như khi vào đâu, trường hợp nào thì nó lỗi, để người fix dễ xác định lỗi hơn.

**Comment by hongoctrien** [comment]
@trinhthinhhp  test lại trên bản mới nhất xem nhé. Em không thấy lỗi này.
