### ISSUE TITLE
Lỗi khi chọn kích cỡ thì "thêm vào giỏ hàng" và "Mua ngay" không hoạt động được

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#304]
Khi click vào "đặt hàng" ngay trên trang chủ module shops và trang chi tiết thì bị lỗi thêm vào giỏ hàng và  đặt hàng bị làm mờ không cho click, click vào chọn kích thước thì lúc được lúc không được như hình sau
![untitled](https://cloud.githubusercontent.com/assets/6928431/8052475/1d14ae0a-0eb2-11e5-948b-dd8f781a43ed.png)

**Comment by hongoctrien** [comment]
Đây nhé https://github.com/nukeviet/module-shops/issues/313
