### ISSUE TITLE
Lỗi thêm sản phẩm vào giỏ hàng ko tính được "thành tiền"

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#305]
Khi thêm vào giỏ hàng thì tính thành tiền không có giá trị 
![untitled](https://cloud.githubusercontent.com/assets/6928431/8052524/771c6aa0-0eb2-11e5-86a5-62719da3815a.png)

**Comment by hongoctrien** [comment]
@trinhthinhhp  Anh nói rõ hơn em với.

**Comment by trinhthinhhp** [comment]
@hongoctrien  tức là ô số lượng lúc đợc lúc không, kho click sản phẩm cần mặc định nó là 1 thì sang phần này nó mới tính tiền được, a click vào 1 sản phẩm đặt số lượng là 3 nhưng sang đến cái này thì số lượng bị rỗng

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/11880e663d0276b736aeff93ed767c92ed2e82ab
