### ISSUE TITLE
Lỗi khi bật tính năng vận chuyển

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#306]
Khi  bật tính năng này và điền thông tin thì không cho hết vào bảng thông tin bên dưới và khi bấm nút "gửi thông tin phiếu đặt hàng" thì chuyển dữ liệu vào trong csdl mà vẫn đứng nguyên ở vị trí ban đầu như hình dưới
![untitled](https://cloud.githubusercontent.com/assets/6928431/8052926/2b7f0090-0eb6-11e5-9dca-9b40b9a78ddf.png)

**Comment by hongoctrien** [comment]
@trinhthinhhp cấu hình vận chuyển rồi chứ anh.
Như thế này http://mynukeviet.net/tai-lieu/module-shops/huong-dan-cau-hinh-dich-vu-van-chuyen-module-shops-4-8.html
