### ISSUE TITLE
Lỗi đặt hàng.

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#309]
Khi đặt hàng sản phẩm không load được số lượng đặt hàng.

![capture](https://cloud.githubusercontent.com/assets/8292355/8054872/0abf7578-0ec6-11e5-932f-3ffae761b26f.JPG)
![capture](https://cloud.githubusercontent.com/assets/8292355/8054891/1d2e20b0-0ec6-11e5-9e27-8a3640a00432.JPG)

**Comment by hongoctrien** [comment]
^^ không phải không load được mà nhiều cột quá nên cái textbox nó bị dồn, che mất cái số.
Vấn đề này do nhiều nhóm mặc định hiển thị quá, mình đã bỏ hết, mặc định không hiển thị nhóm nào ra đây cả. https://github.com/nukeviet/module-shops/issues/321
