### ISSUE TITLE
Lỗi khi click vào nhóm sản phẩm

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-shops#313]
Lỗi khi click vào nhóm sản phẩm thì xuất hiện hết hàng và "thêm vào giỏ hàng" và "mua ngay" bị làm mờ đi. 
![2015-06-12_085448](https://cloud.githubusercontent.com/assets/10916826/8122237/1b3175ce-10e1-11e5-8fe7-21deca91c33d.png)

Môi trường thử nghiệm
Apache/2.4.4 (Win32) PHP/5.4.16
Trình duyệt : Chroom

**Comment by hongoctrien** [comment]
Nếu bạn không sử dụng chức năng nhập kho, thì số lượng sản phẩm của mỗi nhóm thuộc tính ở đây sẽ bằng 0 => hết hàng => mờ ko cho đặt.

Để giải quyết vấn đề này, bạn vào quản lý nhóm sản phẩm, **Hiển thị khi đặt hàng** chọn là **Không** cho tất cả nhóm (mà sản phẩm thuộc nhóm đó).

Cái này không phải là lỗi ạ.
