### ISSUE TITLE
Ý kiến đóng góp cho phiên bản shop v4.0.15

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#314]
-Shop v4.0.15 đã có cấu hình màu sắc nhưng chỉ là demo và chiếm diện tích thôi chứ chức năng chưa làm tròn nhiệm vụ của việc load màu sản phẩm nên chăng bỏ nó đi vì khi click chọn màu thì các chức năng khác bị treo. (Cho vào giỏ;  Mua ngay)....Nếu đã làm chức năng chọn màu cho sản phẩm thì phải như lày: https://www.thegioididong.com/dtdd/samsung-galaxy-e5
Vã lại úp nhiều hình cho cùng 1 sản phẩm mà chỉ hiển thị chỉ có 1
- Việc sắp xếp cách hiển thị chi tiết khi xem sản phẩm chưa hợp lý và chưa có tính mỹ quan. (Vấn đề này tại shop v4.0.15 đã làm tốt)
+ Chưa pix:
![455](https://cloud.githubusercontent.com/assets/11238423/8146613/103d6c7a-126e-11e5-9ee6-be6a5463d70e.png)
+ Nên hiển thị theo kiểu này:
![678](https://cloud.githubusercontent.com/assets/11238423/8146614/242fb4f4-126e-11e5-9131-46a081249d73.png)

**Comment by hongoctrien** [comment]
> -Shop v4.0.15 đã có cấu hình màu sắc nhưng chỉ là demo và chiếm diện tích thôi chứ chức năng chưa làm tròn nhiệm vụ của việc load màu sản phẩm nên chăng bỏ nó đi vì khi click chọn màu thì các chức năng khác bị treo. (Cho vào giỏ; Mua ngay)....Nếu đã làm chức năng chọn màu cho sản phẩm thì phải như lày: https://www.thegioididong.com/dtdd/samsung-galaxy-e5

Chức năng hiển thị màu sắc ở đó sẽ được phát triển sau.

> Vã lại úp nhiều hình cho cùng 1 sản phẩm mà chỉ hiển thị chỉ có 1

Quản lý tabs và hiên thị tabs **Hình ảnh khác** ra

> Việc sắp xếp cách hiển thị chi tiết khi xem sản phẩm chưa hợp lý và chưa có tính mỹ quan. (Vấn đề này tại shop v4.0.15 đã làm tốt)

Cái này nếu bạn chọn giao diện là **Tự động** sẽ hiển thị như hình thứ 2 của bạn. Tính năng tùy chọn giao diện của NukeViet 4.0.18 vẫn chưa hoàn thiện, đang cập nhật trong các phiên bản tiếp nên việc hiển thị ảnh sản phẩm ở đây mình sẽ xem lại khi tùy chọn giao diện của NukeViet 4 hoàn chỉnh.
