### ISSUE TITLE
Báo lỗi thêm tài liệu ở phiên bản shop v4.0.15

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#315]
Khi thêm tài liệu cho sản phẩm thì báo lỗi: Đường dẫn không hợp lệ
![01](https://cloud.githubusercontent.com/assets/11238423/8146722/806c50d8-1273-11e5-984f-f8d4cde23312.png)

**Comment by hongoctrien** [comment]
Mình test không thấy lỗi này @hoanglongvnpt 
Bạn kiểm tra lại xem file có tồn tại không nhé.
