### ISSUE TITLE
Thông báo từ Hệ thống  file /modules/shops/funcs/order.php on line 74

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/module-shops#316]
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Undefined index: discount in file /modules/shops/funcs/order.php on line 74
Link: /shops/order/
Web chạy Nukeviet 4.0.18

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/5707880dd6c1ec4ef58cd509ea1d447761a1b1e8
