### ISSUE TITLE
[Payment] Lỗi khi thực hiện thanh toán với Bảo Kim và Paypal

### ISSUE THREAD

**Issue by nhsanga12** [nukeviet/module-shops#318]
B1 - Kích hoạt chức năng thanh toán với Bảo Kim và Paypal.
B2 - Nhập thông tin cấu hình trong phần cấu hình của từng cổng thanh toán.
B3 - Tiến hành đặt hàng và thanh toán.
1. Với Paypal: sau khi click nút THANH TOÁN thì hệ thống không làm gì, chỉ đứng yên tại trang hiện tại
2. Với Bảo Kim: chuyển đến trang order của Bảo Kim và báo lỗi 400. Chi tiết lỗi bên dưới:
400 - An Error Was Encountered
Xin lỗi, hành động của bạn không thể hoàn thành vì:
business phải có giá trị.
order_id phải có giá trị.
total_amount phải có giá trị.
merchant_id phải có giá trị.
checksum phải có giá trị.

Vui lòng fix và kiểm tra lại.
Cảm ơn!

**Comment by hongoctrien** [comment]
Hiện tại đã fix cho paypal https://github.com/nukeviet/module-shops/commit/b83afe2c701ec4feb1367860b5f04b8236cb007b
Baokim đội code vẫn đang xem xét.

**Comment by hoaquynhtim99** [comment]
Bỏ qua vì shops đã chuyển sang thanh toán bằng wallet
