### ISSUE TITLE
[Góp ý] về data Demo cho shops

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#320]
Cái này khá hay cho Shop. Tuy nhiên mình góp ý là chỉ cần dùng 1 ảnh duy nhất cho tất cả các sp thôi có lẽ là đủ. Điều này giảm bớt kích thước gói modules xuống phần nào.

**Comment by vuthao** [comment]
@hongoctrien  sửa lại dữ liệu demo theo hướng này luôn nhé.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/f6211abbd44ab1e4feb005ff26c776b76dfa9346
