### ISSUE TITLE
Sửa tính năng di chuyển vào tab bình luận sau khi chuyển link yêu cầu đăng nhập 

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/module-shops#325]
Link khi tab bình luận yêu cầu đăng nhập thành viên
Link khi tab tài liệu yêu cầu đăng nhập thành viên

**Comment by vuthao** [comment]
@PhamQuocTien132  đã sửa ở đây rồi đúng ko.
https://github.com/nukeviet/module-shops/commit/efd87e99eb465afb84ad8368234f472508d1be46
Nếu đúng đóng issues lại nhé
