### ISSUE TITLE
Bỏ “Sắp xếp” trong "Quản lý giảm giá", không cần thiết.

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/module-shops#329]
Bỏ luôn “Hiển thị bảng giá”, cái này hiện không sử dụng.

**Comment by hongoctrien** [comment]
Bỏ luôn “Hiển thị bảng giá”, cái này hiện không sử dụng.

**Comment by vuthao** [comment]
Theo anh cái này vẫn dữ lại chứ nhỉ.

**Comment by hongoctrien** [comment]
Cái này em thấy lâu lâu mới cập nhật một lần, cập nhật cái này thì cái trước đã hết hạn (Nên trong danh sách chọn chỉ hiển thị những cái còn hạn). Với lại danh sách ở đây không cần phải sắp xếp thứ tự.

**Comment by hongoctrien** [comment]
Deleted: https://github.com/hongoctrien/module-shops/commit/26a2816abc907b6547ed62b5c5752c6019fbb45c
