### ISSUE TITLE
Lỗi khi sửa sản phẩm trung liên kết tĩnh.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/module-shops#330]
Lỗi khi sửa sản phẩm trung liên kết tĩnh, bị trang trắng.

Lỗi khi thêm sản phẩm trung liên kết tĩnh, báo lỗi không rõ ràng:  Lỗi hệ thống không cập nhật được nội dung.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/09cba64b7ca0a8b8e69486cae1ff7bae2b1ffb14
