### ISSUE TITLE
Lỗi trắng trang ngoài site

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#331]
Sử dụng bản nukeviet mới nhất tới phần fix Mobile Detect và kết hợp module shops gây trắng trang tại module shops

**Comment by vuthao** [comment]
lỗi này do cài đặt dữ liệu, không liên quan ghì đến Mobile Detect nhé
https://github.com/nukeviet/module-shops/commit/7f3defc6432bac88f15c80d25a4b0ebcefe1ddd7
