### ISSUE TITLE
Lỗi upload đường dẫn ảnh sản phẩm Module Shops 4.0.16

### ISSUE THREAD

**Issue by Kyodo-samurai** [nukeviet/module-shops#344]
Module Shops 4.0.16 lỗi ảnh

**Comment by vuthao** [comment]
Bạn vui lòng mô tả rõ lỗi như thế nào nhé, chứ thế này chúng tôi không tìm để sửa được đâu.

**Comment by Kyodo-samurai** [comment]
- Trong phần Danh sách sản phẩm thông báo từ hệ thống "Undefined variable: module_upload in file /modules/shops/admin/items.php" dòng 400, 401, 405

- Phần thêm sản phẩm tương tự biến module_upload Undefined dòng 26 & 983

- Lúc đầu khi thêm sản phẩm phần ảnh upload lại ko vào đường dẫn thư mục "uploads/shops" mà lại tạo 1 thư mục mới ra ngoài, vd: uploads/2015_07

- Chỉnh sửa lại sản phẩm vừa thêm vào thì đường dẫn lưu trong csdl lại là : http://tenmien.com/uploads//hops/2015_05/demo5.jpg

- Phần đường dẫn hay bị cắt thiếu chữ, lúc thì là ..uploads//hops/2015_05/demo5.jpg

lúc sửa lại thì uploads//ops/2015_05/demo5.jpg

Ngay module khi tải về đường dẫn ảnh trong danh sách sản phẩm cũng ko hiển thị ra trước rồi

**Comment by hongoctrien** [comment]
@Kyodo-samurai Shops 4.0.16 bạn cài cùng phiên bản NukeViet >= 4.0.18 nhé.
