### ISSUE TITLE
Lỗi block global của module shops làm trắng trang

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#347]
Nếu bật global.block_product_center.php để ở cả các module khác thì sẽ bị trắng trang những module khác còn module shops thì nó hiện bình thường.

**Comment by trinhthinhhp** [comment]
Hôm nay check lại ko thấy mà phát sinh ra

Nên chú ý Nên chú ý: Undefined index: homewidth in file /modules/shops/blocks/global.block_product_center.php on line 199
Nên chú ý Nên chú ý: Undefined index: homewidth in file /modules/shops/blocks/global.block_relates_product.php on line 187

Sẽ update lại thông tin sau xem có bị sung đột với block khác hay không

**Comment by hongoctrien** [comment]
Chẳng biết block này nó đụng với block nào, lỗi cảnh báo em test cũng không thấy luôn.
