### ISSUE TITLE
Sai ngôn ngữ trong nhóm sản phẩm

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#348]
Hiện tại trong nhóm sản phẩm vẫn còn đang sử dụng chung ngôn ngữ với loại sản phẩm

![language-nhom-san-pham](https://cloud.githubusercontent.com/assets/6928431/8423282/0570924a-1f11-11e5-9a6d-a690c34c07d2.png)

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/954ac81d43143b4d1635c006f3193f52f977593a
