### ISSUE TITLE
Góp ý cần bỏ bắt buộc nhập nội dung chi tiết và giới thiệu

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#349]
Phần nội dung chi tiết và giới thiệu lên bỏ bắt buộc, vì trong quá trình làm site sản phẩm, người quản trị không muốn đăng nội dung chi tiết và giới thiệu. Ví dụ như site về cung cấp linh phụ kiện máy tính có dây nguồn, tấm lót chuột, ... chắc chắn là họ sẽ không viết nội dung chi tiết và giới thiệu mà chỉ đăng ảnh điền tên sản phẩm

**Comment by vuthao** [comment]
Việc này chỉ cho nhưng người  Lười, đăng sản phẩm lên làm ghì ? 
Có muốn bán hàng không mà đăng nội dung tùy tiện thế.
Có muốn khi tìm kiếm sản phẩm có trên google không.

Qua những câu hỏi đó bạn sẽ biết phải làm ghì.
