### ISSUE TITLE
Cần linh hoạt click chọn thông số của tùy biến dữ liệu khi đặt hàng 

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#350]
Hiện tại khi đàng ở popup sản phẩm  hay trang chi tiết sản phẩm ko mượt, khi click chọn 1 thông số thì hết hàng, F5 thì còn hàng click tiếp từng cái thì hết hàng, và cần phải click chọn sang cái tiếp theo để hiển thị trạng thái còn hay không còn thay vì lại phải F5 chọn lại cấu hình. Khi chọn 1 thông số và bấm vào mua ngay sẽ có hiện tượng thông số đó chưa được click chọn.
![sanpham](https://cloud.githubusercontent.com/assets/6928431/8426239/6eb6e4a8-1f38-11e5-8c81-0eee410d7adf.png)

![muangay](https://cloud.githubusercontent.com/assets/6928431/8426273/b80290ee-1f38-11e5-97be-8e1e1c4073e5.png)

**Comment by hongoctrien** [comment]
> Hiện tại khi đàng ở popup sản phẩm hay trang chi tiết sản phẩm ko mượt, khi click chọn 1 thông số thì hết hàng

Nếu đặt hàng có nhóm sản phẩm thì phải nhập kho cho các nhóm đó đã mới đặt hàng được, còn không thì nút đặt sẽ mờ đi. Cái này không phải lỗi.

> Khi chọn 1 thông số và bấm vào mua ngay sẽ có hiện tượng thông số đó chưa được click chọn.
Fixed: https://github.com/nukeviet/module-shops/commit/7423a30181bc81db14a5a535ef5399be0fc125ec
