### ISSUE TITLE
Không hiển thị hình ảnh sản phẩm khi nhấn nút Đặt hàng

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#351]
Hiện mình gặp phải lỗi khi nhấn nút đặt hàng ở trang chủ shop bản v4.0.15 nó không hiển thị hình ảnh sản phẩm.
![1](https://cloud.githubusercontent.com/assets/11238423/8445467/c67b29e4-1fc7-11e5-9d8c-a73912651f21.png)

**Comment by hongoctrien** [comment]
@hoanglongvnpt cung cấp giúp mình thông tin về trình duyệt + độ phân giải màn hình ạ.

**Comment by hoanglongvnpt** [comment]
Ở file: bootstrap.non-responsive.css

có đoạn code này:
.modal-dialog {
  position: relative;
  width: auto;
  margin: 10px;
}
.modal-dialog {
    width: 600px;
    margin: 30px auto;
  }
Có thể bị trùng không nhỉ?
Mình thử xóa đoạn:
modal-dialog {
    width: 600px;
    margin: 30px auto;
  }
thì ok!
Text ở đọ phân giải: 1280 x 1024 trên trình duyệt google chrom Phiên bản 43.0.2357.130 m

**Comment by mynukeviet** [comment]
@hoanglongvnpt test lại giúp mình trên NukeViet 4.0.23 xem hết lỗi chưa nhé.

**Comment by mynukeviet** [comment]
Có lẽ cái này đã ổn. Không thấy ai báo lỗi cái này nữa cả.
