### ISSUE TITLE
Điểm tích lũy

### ISSUE THREAD

**Issue by sutuem** [nukeviet/module-shops#359]
Mình thấy Khách hàng chưa biết số điểm tích lũy được (Dựa vào tổng số tiền đã đặt hàng và thanh toán) giống kiểu siêu thị. Ví dụ tổng số tiền đặt hàng là 5tr tương ứn sẽ tặng khách hàng thêm bao nhiêu điểm (tương ứng với số tiền) để kích thích khách hàng mua lần sau

**Comment by hongoctrien** [comment]
Bạn xem qua tài liệu này nhé http://wiki.nukeviet.vn/nukeviet4:admin:shops:point
