### ISSUE TITLE
Lỗi Module Shops 4.0.x gửi phiếu đặt hàng cho quản trị có nội dung Array .

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/module-shops#360]
Tôi đã kiểm tra Module Shops 4.0.13, 4.0.14, 4.0.15, 4.0.16 (Các phiên bản trước thì không để ý nên không rõ) khi đặt hàng trên website thành công thì email gửi thông tin phiếu đặt hàng cho email của quản trị không có nội dung của đơn hàng mà chỉ có 1 từ duy nhất là: Array.
Còn email của người khách đặt hàng thì vẫn nhận được đầy đủ thông tin của đơn hàng.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/f6fd0f57dd44142e2d7ef552e858784b04fac63b

**Comment by NukeVietCMS** [comment]
Làm theo Fixed: hongoctrien@f6fd0f5  này thì email quản trị không nhân được đơn hàng luôn. Chỉ có nguoi đặc hàng nhận được email mà thôi.
Cần là làm sao người quản trị có thể nhận được email mỗi khi có đơn hàng mới, hoặc thay đổi , xác nhận của đơn hàng.
