### ISSUE TITLE
Trong giỏ hàng, đặt hàng không có địa chỉ nhận hàng.

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/module-shops#361]
Khi thực hiện đặt hàng thì trong phần /order/ đặt hàng không có chỗ ghi địa chỉ nhận hàng. 
Giá trị order_address này không có trong CSDL hệ thống của module shops. Phần này đáng ra phải có trong phần cài đặt mật định của modules nhưng tôi đã kiểm tra mà không thấy. 
Modules shops 4.0.13,4.0.14, 4.0.16 Chạy trên NukeViet 4.0.18, 4.0.19.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/82e30e35eb217cb4b611e616d14a7a6a86b72bf4
