### ISSUE TITLE
Không upload được hình minh họa cho sản phẩm

### ISSUE THREAD

**Issue by phucdaiduong** [nukeviet/module-shops#363]
mình đang test thử NukeViet 4.0 Open Beta 6  và Module Shops 4.0.15. khi up thử sản phẩm mới thì không thêm được hình minh họa.

**Comment by hongoctrien** [comment]
**Không thêm được** cụ thể là thế nào bạn?

**Comment by phucdaiduong** [comment]
Mình đang sử dụng host arvixe dành cho nukeviet. Chạy thử Nukeviet 4.0.18 & module shops 4.0.15 (sau đó là 4.0.16) bị lỗ up ảnh như ở dưới đây.

Trong thư mục: "/public_html/suanoidianhat.com/uploads/shops" có các thư mục con:
![image](https://cloud.githubusercontent.com/assets/11764488/8586127/a1991e16-2615-11e5-9fa9-73fa224d9b36.png)

Khi thêm hình minh họa thì chỉ thấy thư mục sau và không up được ảnh
![image](https://cloud.githubusercontent.com/assets/11764488/8586136/bc10e68e-2615-11e5-9b7d-81fd2ee7b814.png)

**Comment by hongoctrien** [comment]
Bạn giúp mình thế này nhé.

- Cấu hình / Cấu hình FPT và khai báo các thông số cấu hình ở đây. Ở cái hình thứ 2, click cái icon nhỏ ở góc dưới - trái xem có hiện mấy thư mục kia ra không nhé.

- Nếu vẫn không được, bạn dơwn NukeViet + Shops phiên bản mới nhất về test lại giúp mình với.

**Comment by phucdaiduong** [comment]
Sau khi làm theo hướng dẫn của bạn: "khai báo thông số  cấu hình FTP". chức năng hình minh họa đã hoạt động rồi. Cám ơn bạn hongoctrien.

**Comment by hongoctrien** [comment]
Ok ^^
