### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/module-shops#364]
[Notice(8): Undefined index: date_start] [FILE: /modules/shops/funcs/loadcart.php] [LINE: 56]
[Notice(8): Undefined index: type] [FILE: /modules/shops/funcs/loadcart.php] [LINE: 78]
[Notice(8): Undefined index: discount] [FILE: /modules/shops/funcs/loadcart.php] [LINE: 89]
[Notice(8): Undefined variable: total_old] [FILE: /modules/shops/funcs/loadcart.php] [LINE: 96]

**Comment by hongoctrien** [comment]
@dangdinhtu2014  Lỗi này xuất hiện khi nào anh?

**Comment by dangdinhtu2014** [comment]
đơn giản chỉ là $counpons rỗng do ko có mã giảm giá nào trowng csdl, và chú dùng tên biến sai chính tả nữa nhé :D

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/f85c54eb2148c36bdb88d06ca59bd602820960fa
