### ISSUE TITLE
Báo lỗi shop bản v4.0.15 cài trên Nukeviet v4.0.21

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#365]
Đội coder xem giúp lỗi này:
Mình làm theo HD ở đây: http://wiki.nukeviet.vn/nukeviet4:admin:shops:download
Nhưng khi thêm tài liệu thì báo: Đường dẫn tập tin không hợp lệ
(đang test tại local)

**Comment by vuthao** [comment]
Bạn cài trên kho ứng dụng nhé.

**Comment by hongoctrien** [comment]
Lỗi này đã fix. https://github.com/nukeviet/module-shops/commit/a195c4ccc7a48d76512dcb92adba12bb804fa92e
