### ISSUE TITLE
Lỗi Undefined index

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/module-shops#367]
Notice:  Undefined index: userid in modules\shops\funcs\order.php on line 30
Notice: Undefined index: full_name in modules\shops\funcs\order.php on line 31
Notice: Undefined index: email in modules\shops\funcs\order.php on line 32

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/93d09578408d8a7a65359168d63f8656294f766f
