### ISSUE TITLE
facebook like bị tab chi tiết đè lên khi ấn like

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/module-shops#369]
fix
.tabs {
	z-index: 0;
}

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/fd83b37f3e2ccb6d4fe563b6215a08f9ad273169
Cảm ơn @dangdinhtu2014

**Comment by ThinhNguyenVB** [comment]
@hongoctrien  close đi, cứ tưởng chưa fix nhảy vô thấy fix rồi

**Comment by mynukeviet** [comment]
Đợi @vuthao  chứ em ko close được.
