### ISSUE TITLE
Phần ảnh minh hoạ thêm cho sản phẩm không hiển thị?

### ISSUE THREAD

**Issue by levietpro** [nukeviet/module-shops#370]
Thêm ảnh minh hoạ khác cho sản phẩm nhưng khi ra xem sản phẩm thì không thấy hiển thị ảnh minh hoạ cho khác sản phẩm. Hình minh hoạ chính của sản phẩm bé xíu, dạng thumb. điều chỉnh nó như thế nào?

**Comment by hongoctrien** [comment]
Bạn phải vào quản lý tab, thêm tab mới là “Hình ảnh khác” nhé
