### ISSUE TITLE
Về chức năng tuỳ biến dữ liệu?

### ISSUE THREAD

**Issue by levietpro** [nukeviet/module-shops#371]
Chưa biết để làm gì , vì khi thêm trường dữ liệu mới ko biết nó có tác dụng ở phần nào trong shop?

**Comment by vuthao** [comment]
Của bạn đó: http://wiki.nukeviet.vn/nukeviet4:admin:shops:template

**Comment by hongoctrien** [comment]
Close cái này luôn @vuthao
