### ISSUE TITLE
Vấn đề danh mục trong shops

### ISSUE THREAD

**Issue by sutuem** [nukeviet/module-shops#372]
Mình thấy có 1 vấn đề là: Nhiều shops với 1 sản phẩm có thể thuộc nhiều chuyên mục. Nếu module shops có thể chọn được nhiều danh mục cho 1 sản phẩm thì sẽ OK hơn nhiều

**Comment by hongoctrien** [comment]
Vấn đề này đội code có xem qua, và quyết định tạm thời không phát triển thêm chức năng này trong phiên bản hiện tại.
