### ISSUE TITLE
Báo lỗi Shop bản v4.0.17 

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#373]
1. Tải code trên: Module shops 4.0.17: https://github.com/nukeviet/module-shop ... 4.0.17.zip
2. Tiến hành cài đặt: ok!
      +Vào: Cấu hình module / Quản lý Tab tiến hành thêm tab (Hình ảnh khác; Download tài liệu)
ra trang chủ không thấy 2 tab đó xuất hiện.
3.  “Quản lý tài liệu”. Tiến hành thực hiện như ở đây:         http://wiki.nukeviet.vn/nukeviet4:admin:shops:download
       Khi thêm tài liệu và nhấn nút thêm file: Báo lỗi đường dẫn file không hợp lệ.
* Chuyển sang cài đặt module trên tiện ích Quản lý ứng dụng trong ACP
Chọn cài đặt ứng dụng thấy chấp nhận kiểm tra các file đã có trên hệ thống. Lại được nhận thông báo: 
Lỗi: Ứng dụng này có cấu trúc không phù hợp và có thể gây nguy hại đến website. Để đảm bảo an toàn, hệ thống từ chối việc tiếp tục cài đặt ứng dụng này.

(Test Module shop mới nhất bản v4.0.17 trên hệ thống Nukeviet mới nhất v4.0.21)

**Comment by anhyeuviolet** [comment]
https://github.com/nukeviet/module-shops/pull/380
https://github.com/nukeviet/module-shops/pull/423
