### ISSUE TITLE
Chức năng tùy biến dữ liệu lỗi

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/module-shops#375]
- Đã cấu hình bật, đã add vào sản phẩm, đã active tabs Tùy biến dữ liệu
=> Phần detail sản phẩm vẫn không hoạt động

**Comment by hongoctrien** [comment]
Ở danh sách nhóm dữ liệu /admin/index.php?nv=shops&op=template
Bạn click vào tên nhóm, trong đây chọn các trường đươc hiển thị nhé.
