### ISSUE TITLE
Nhóm sản phẩm

### ISSUE THREAD

**Issue by vinhntgroup** [nukeviet/module-shops#377]
Chọn nhóm sản phẩm khi đặt hàng thì hệ thống báo hết hàng, và không thể sử dụng thêm vào giỏ hàng hoặc mua hàng nữa

**Comment by vinhntgroup** [comment]
Thiết lập nhóm sản phẩm thì phải sử dụng chức năng Nhập kho để thêm số lượng và giá thành :dancers:

**Comment by hongoctrien** [comment]
Đúng rồi ạ. Phải nhập kho mới có số lượng bạn nhé.
