### ISSUE TITLE
Góp ý chức năng nhập kho và đặt hàng k giới hạn số lượng !

### ISSUE THREAD

**Issue by ntanh2605** [nukeviet/module-shops#382]
Hiện nay khi kích hoạt đặt hàng k giới hạn, mà số lượng trong kho hết thì không thực hiện được. Vì vậy mình nghĩ nên để như các phiên bản cũ, khi chọn đặt hàng k giới hạn thì nó không kiểm tra số lượng trong kho nữa ! Đâu phải lúc nào mở shop bán thì cũng phải in stock hàng hóa đâu, cho nên việc kiểm tra tồn kho có lẽ k cần khi kích hoạt chức năng đặt hàng k giới hạn !

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/2d3048aca6ee6b0ddb893ceb040af403de22f87e
