### ISSUE TITLE
Lỗi hiển thị nhóm ở cart.tpl Module Shop 4

### ISSUE THREAD

**Issue by ntanh2605** [nukeviet/module-shops#383]
Nếu một sản phẩm có nhiều dữ liệu khác nhau trong cùng một nhóm, ví dụ nhiều màu A, B, C....
Khi chọn SP và load đến mục kiểm tra giỏ hàng, tức file cart.tpl. Phần code <code>// Group của sản phẩm</code> trong file theme của module luôn load thông tin cuối của sản phẩm. Ví dụ mình chọn màu B hoặc A. Thì khi xem ở giỏ hàng, cột thuộc tính nhóm "Màu sắc" luôn hiển thị C. 
Nhờ đội code kiểm tra lại ! Thank !

**Comment by ntanh2605** [comment]
@Fix: Mở theme.php trong module Shop
Tìm đến // Group của sản phẩm
Thay thế <code>if( $item['parentid'] == $group_main_id ) { ... } </code> bằng <code>						if( $item['parentid'] == $group_main_id )
						{
							foreach( $data_row['group'] as $groupid )
							{
					
								$items = $global_array_group[$groupid];
								if($items['title']==$item['title']) {
									$data['title'] = $item['title'];
									$data['link'] = $item['link'];	
								}
					
							}
	

							
						}
</code>

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/0e18e14ff3b951267a766a355922d638204a8f2f

Cái này các bạn chỉ nên cho hiển thị ra các thuộc tính có 1 lựa chọn thôi nhé (Thuộc tính nhiều lựa chọn cũng được, nhưng không hopwj lý lắm).
VD như Xuất xứ, nhà sản xuất. Còn như kích thước, màu sắc,... thì không nên cho nó hiển thị làm gì.
