### ISSUE TITLE
đặt hàng trùng sản phẩm & khác size

### ISSUE THREAD

**Issue by tongbao123** [nukeviet/module-shops#384]
khi đặt hàng cùng 1 sản phẩm mà nhiều hơn 2 size .. thì giỏ hàng chỉ hiện 1 size đầu tiên

**Comment by hongoctrien** [comment]
Chào bạn ạ. 
Không hiểu sao bạn đặt được 2 size ạ. 1 lúc chỉ chọn được một thuộc tính.
Bạn mô tả rõ hơn vấn đề này được chứ?

**Comment by ntanh2605** [comment]
Í bạn đấy là sau khi chọn sp A với thuộc tính Size M. Nguời ta lại chọn tiếp sp A với size L. Khi đó đơn hàng sẽ cộng dồn thành 2 sp A chứ k có phân biệt rõ là mỗi size 1 cái. Điều này cũng bị tương tự như khi chọn cùng sp nhưng khác màu hoặc kcác thuộc tính khác. Miễn là cùng id sp thì tất cả sẽ bị cộng dồn và đơn hàng chủi hiển thị thuộc tính đc chọn ở lần cuối!

**Comment by tongbao123** [comment]
bạn #ntanh2605 trả lời đúng đấy :) !! iu quá <3

**Comment by vuthao** [comment]
Trong phần cấu hình:      Nhóm sản phẩm, Sẽ có cấu hình: Hiển thị khi đặt hàng

**Comment by ntanh2605** [comment]
Phần hiển thị khi đặt hàng chỉ tắt mở hiển thị cho nhóm. Đâu có giải quyết đc vấn đề đâu bác?

**Comment by hongoctrien** [comment]
@vuthao em hiểu vấn đề này rồi anh. Mở cái cái này rồi em xử lý luôn.
