### ISSUE TITLE
Lỗi thiếu phần ghi chú

### ISSUE THREAD

**Issue by saurom1205** [nukeviet/module-shops#385]
Trông modules shop. 
1. Khi bạn nhập hàng vào kho không thấy có thông tin của nhà cung cấp 
2. Trong lúc nhập thì có trường ghi chú, Nhưng khi xem lại lịch sử nhập kho thì không thấy phần ghi chú đâu cả. ( điều này rất có ích cho người quản lý khi xem lại lịch sử và có ghi chú đầy đủ )

**Comment by hongoctrien** [comment]
1. Chúng tôi ghi nhận ý kiến của bạn, sẽ xem xét phát triển trong các phiên bản kế tiếp.
2. Fixed: https://github.com/hongoctrien/module-shops/commit/49196df3a8d222f0ef1a7cd319eed5156b27ed44
