### ISSUE TITLE
Lỗi ảnh ở module.block_others_product

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/module-shops#386]
1. $src_img = NV_BASE_SITEURL . NV_FILES_DIR . '/' . $site_mods[$module]['module_upload'] . '/' . $homeimgfile_i;
2. $src_img = NV_BASE_SITEURL . NV_UPLOADS_DIR . '/' . $site_mods[$module]['module_upload'] . '/' . $homeimgfile_i;

Fix:
Thay: $site_mods[$module]['module_upload'] bằng $module

**Comment by hongoctrien** [comment]
@phamdinhhau  Vẫn giữ $site_mods[$module]['module_upload'] nhé.
Lỗi này do $site_mods chưa được khai báo trong global.
Fixed: https://github.com/hongoctrien/module-shops/commit/28e35f81decee31a9005c2a49d9fa1720dd9c51c
