### ISSUE TITLE
4.0.17 Lỗi sử dụng mã giảm giá.

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/module-shops#388]
Khi kích sử dụng mã giảm giá mà Cập nhật giỏ hàng lại thì lỗi. Nên sử dụng Session or viết lại phần này :dancer:

**Comment by phamdinhhau** [comment]
Fix:

Thêm vào phần js coupons_info.tpl

var coupons_code = $('#coupons_code').val();        
		if($('#coupons_uses').is(":checked")) {
			$("#total").load(urload + '&coupons_check=1&coupons_load=1&coupons_code=' + coupons_code + '&t=2');
			$("#cart_" + nv_module_name).load(urload + '&coupons_check=1&coupons_code=' + coupons_code);
		}

Mục đích: xác định lại xem coupon đc check sử dụng chưa để load lại Tổng tiền cần thanh toán

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/449c352eb74c487c6c76257b7c545c6a8c81ddd8
