### ISSUE TITLE
Lỗi thay đổi kích thước ảnh.

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/module-shops#393]
Cấu hình kích thước không gắn liền với kích thước, làm ảnh bị mờ...

**Comment by RightPro** [comment]
Bổ sung thêm phần resize nên có thêm hình demo với kick thước ảnh thumb sau khi được resize và bên cạnh ảnh kích thước gốc.

**Comment by hongoctrien** [comment]
Cái này issue sang NukeViet nhé.

**Comment by RightPro** [comment]
OK Triển

**Comment by vuthao** [comment]
Phần này cần cấu hình với cả module shop và upload cho phù hợp.
Do ngoài làm ảnh thumb, có thể các block sẽ sử dụng kích thước khác.
Nên người quản trị sẽ cấu hình cho phù hợp.
