### ISSUE TITLE
Lỗi không hiển thị nội dung chi tiết của sản phẩm

### ISSUE THREAD

**Issue by saurom1205** [nukeviet/module-shops#394]
Lỗi không hiển thị nội dung chi tiết của sản phẩm.
Tôi thấy lỗi không hiển thị chi tiết sản phẩm khi vào xem chi tiết sản phẩm. Mong đội code xem lại giúp.

**Comment by nhimthulinh** [comment]
quản lý tab  trong module shops thêm tab vào bạn

**Comment by mynukeviet** [comment]
@saurom1205 bạn mô tả rõ hơn về lỗi này nhé.
Tab chi tiết sản phẩm mặc định hiển thị khi cài mới shops, lỗi này mình kiểm tra không thấy ạ.
