### ISSUE TITLE
Lỗi tùy biến dữ liệu

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#398]
Hiện tại bản mới nhất chức năng tùy biến dữ liệu không hiện trong phần chi tiết sản phẩm. (Đã bật tab)

**Comment by phamdinhhau** [comment]
Vì nó chưa đc code =))

**Comment by mynukeviet** [comment]
Bạn xem qua cách cấu hình nhé http://wiki.nukeviet.vn/nukeviet4:admin:shops:template

**Comment by vuthao** [comment]
@hongoctrien hình như hướng dẫn chưa đầy đủ thì phải, em kiểm tra và bổ sung vào tài liệu trên wiki nukeviet nhé

**Comment by mynukeviet** [comment]
@motcaiten mình có cập nhật lại code cho phần này https://github.com/hongoctrien/module-shops/commit/15002099a876b42a606885b14689034ffae59d0c, và viết lại tài liệu cấu hình.
Bạn lấy code mới nhất và xem lại tài liệu nhé.

**Comment by motcaiten** [comment]
Ok . Phần này e test đã ok.

**Comment by billygoat-trump** [comment]
Hello bác @hongoctrien @mynukeviet , mình có một vấn đề nhỏ thế này, tất cả thao tác mình đoán là đã làm theo hướng dẫn chuẩn nhất rồi, và đã **_từng thành công_** khi thêm "dữ liệu tùy biến" cho TAB , thế nhưng vì lý do "tab_english" là một trình soạn thảo .... (vui lòng xem hình) nó không hiển thị ... 

**khai báo tab:**
![shop-2](https://cloud.githubusercontent.com/assets/27043619/24825959/349ce2ba-1c55-11e7-8506-ef0e986fdbcd.png)
**nhóm dữ liệu:**
![shop-3](https://cloud.githubusercontent.com/assets/27043619/24825961/58e88b88-1c55-11e7-9cba-d794fa5027f5.png)
**cấu hình hiển thị dữ liệu tùy biến:**
![shop-4](https://cloud.githubusercontent.com/assets/27043619/24825963/6e7ed9c0-1c55-11e7-80ab-d03e2948c834.png)
**tùy biến dữ liệu:**
![shop-5](https://cloud.githubusercontent.com/assets/27043619/24825966/8183927c-1c55-11e7-86ad-482c71517ec8.png)
**trường dữ liệu:**
![shop-6](https://cloud.githubusercontent.com/assets/27043619/24825971/a7c06e56-1c55-11e7-980d-d3505d1cbf14.png)

1...Mình cấu hình các bước theo trình tự các hình ảnh đã chup lại, tuy nhiên khi vào "thêm sản phẩm" chọn đến "loại sản phẩm" đã cấu hình dữ liệu tùy biến theo tab, nó vẫn trống trơ ....  (vui lòng xem hình)
![shop-8](https://cloud.githubusercontent.com/assets/27043619/24825853/73e78c70-1c52-11e7-9b3e-39d7ceb8b13a.png)

2...vấn đề nữa là khi khai bào trong Catalogy - Danh sách loại sản phẩm - tại mục chọn: Dữ liệu tùy biến -- thì xuất hiện hàng loạt các loại (hiện hữu và đã xóa) việc này gây khó khăn (vui lòng xem hình)
![shop-7](https://cloud.githubusercontent.com/assets/27043619/24825859/81ff360a-1c52-11e7-9987-e7be78d8fd43.png)

xem thêm trong database - 
![shop-9](https://cloud.githubusercontent.com/assets/27043619/24825974/c6790006-1c55-11e7-9574-f5689de86b99.png)

* vui lòng giúp đỡ - xóa bớt các Nhóm dữ liệu bị thừa ra khi cấu hình
* Không co bất cứ thay đổi khi thêm sản phẩm mới

**Comment by billygoat-trump** [comment]
Hello, mình đã Vọc ra, nhưng cơ mà cái ISSUE này khôi hài thật nha, Nếu có nhiều hơn 2 **nhóm dữ liệu** và trong mục **Loại sản phẩm** bạn chon "Dữ liệu tùy biến" là một cái đã DELETE rồi , thì chẳng có gì hiển thị ra cả --- chung quy lại nên chọn cận thận **Dữ liệu tùy biến** cho từng loại sản phẩm, mà lỡ tay có thay đổi thì lên đây viết Issue.. 
** lỗi này hình như có ai đó post rồi nhưng mình cũng sẵn hỏi luôn: id="content_customdata" trong **Trình soạn thảo** của Tab mới thêm vào, mỗi dòng nó tự động thêm 2 cái <br> đôi khi là 3 và cứ thế làm cho nội dung thêm vào xấu kinh -- vui lòng hướng dẫn cách khắc phục.

`this is test text number 1
<br>
<br>
this is test text number 2
<br>
<br>
this is test text number 3`

** vẫn chưa khắc phục lỗi **ghi nhớ** này mong hướng dẫn của đội code (nhưng thành phần thừa khi đã delete rồi vẩn còn nguyên trên đây, dẫn đến việc báo lỗi phía trên)

![shop-7](https://cloud.githubusercontent.com/assets/27043619/24827801/03ae5ff0-1c7b-11e7-88df-40b33b524e6e.png)
