### ISSUE TITLE
Hỏi về số lượng sp hiển thị trên 1 hàng?

### ISSUE THREAD

**Issue by levietpro** [nukeviet/module-shops#403]
các bác cho hỏi sao trong cấu hình shops ko có lựa chọn hiển thị 5 sp trên 1 hàng vậy??? 4 thì e thấy nó ít quá, mà 6 thì e thấy nó co lại quá nên e muốn để 5 cho nó vừa vừa mà ko có 5 :(

**Comment by vuthao** [comment]
Do lưới ở đây đang sử dụng là 24, nên chỉ có thể chia ra làm 1, 2, 3, 4, 6, 8 ...
Yêu cầu của bạn chúng tôi không thể đáp ứng.
