### ISSUE TITLE
Lỗi không hiển thị phân trang trong tìm kiếm module shops

### ISSUE THREAD

**Issue by 0zozozo** [nukeviet/module-shops#406]
Xin chào các bạn ! 
Hiện mình đang sử dụng module shop.
Có sử dụng hai block sau:
 - module block_filter_product
 - global block_search
Nhưng khi thực hiện tìm kiếm thì chỉ hiện thị được 12 sản phẩm ở trang chủ.
Rất mong được các bạn giúp đỡ.

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/933e34594ff7e60a9b982fe5354d0d581b0fa7a1
Cảm ơn bạn.
