### ISSUE TITLE
Lỗi cảnh báo xem chi tiết sản phẩm

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-shops#410]
Sản phẩm không có hình ảnh
Nên chú ý: getimagesize(): Read error! in file /includes/core/filesystem_functions.php on line 783

**Comment by levietpro** [comment]
lỗi này khi up 1 sản phẩm mới thì mới có hình, còn sd dữ liệu mẫu cài lên nv bản 4.22 sẽ bị ko có hình @@

**Comment by hoanglongvnpt** [comment]
lỗi này vào acp/shop/danh mục sản phẩm thay đổi đường dẫn ảnh trong thư mục uploads/shops/2015_05 sang link: uploads/shops/2015_08 sẽ hiển thị hình ảnh

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/09e26630a916a9335ba275391a8f05375d28403e
