### ISSUE TITLE
báo lỗi hiển thị block cataloge.tpl

### ISSUE THREAD

**Issue by levietpro** [nukeviet/module-shops#413]
trong nội dung file cataloge của bản shops 4.0.17 có phần : 

<script type="text/javascript" data-show="after">
    var imageslist = {
        down : ['downarrowclass', '{THEME_TEM}/images/promenu/down.gif', 23],
        right : ['rightarrowclass', '{THEME_TEM}/images/promenu/right.gif']
    };
</script>

<script type="text/javascript" data-show="after" src="{THEME_TEM}/js/promenu.js"></script>

<script type="text/javascript" data-show="after">
    ddsmoothmenu.init({
        mainmenuid : "smoothmenu2",
        orientation : 'v',
        classname : 'ddsmoothmenu-v',
        contentsource : "markup"
    })
</script>

<link rel="stylesheet" type="text/css"  href="{THEME_TEM}/css/promenu.css" />

<div id="smoothmenu2" class="ddsmoothmenu-v">
    <ul>
        {CONTENT}
    </ul>
    <br style="clear: left"/>
</div>

Tuy nhiên tất cả các đường dẫn đến file css và js của promenu đều Không tồn tại trong các bản nukeviet 4 nên bị lỗi hiển thị block cataloge.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-shops/commit/dac36ac7969b1504ff1ac9c98ba77badf40981b1

**Comment by mynukeviet** [comment]
Block này tương tự như global.block_catalogs.
Nên mình xóa luôn cái này đi https://github.com/hongoctrien/module-shops/commit/84818d49e073ca5435fc741a5e25232a0e79c747
