### ISSUE TITLE
Lỗi thêm tài liệu trong shop v4.0.17 trên bản develop

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#414]
Khi thêm tài liệu ở mục quản lý tài liệu thì báo lỗi "Đường dẫn tập tin không hợp lệ"

**Comment by truongdacngoc1993** [comment]
![1](https://cloud.githubusercontent.com/assets/12822407/9192835/bc09b8c2-4038-11e5-9d8f-e3bf684d3876.png)

**Comment by thanhhaionline** [comment]
minh cung bi loi nay

**Comment by anhyeuviolet** [comment]
Commit này không có lỗi trên.
https://github.com/nukeviet/module-shops/commit/cfe498b1e225ffae4b9601a8e1eff765cc6f1554
