### ISSUE TITLE
Bản develop hiện tại không load css shops.css

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/module-shops#415]
Lỗi như tiêu đề khi cài trên NV 4.0.22

**Comment by anhyeuviolet** [comment]
Hình như cái này do NV thì phải...

**Comment by mynukeviet** [comment]
ĐÚng ạ, cái này do lỗi NukeViet. Mọi người cập nhật NukeViet mới nhất sẽ hết nhé.
