### ISSUE TITLE
[Lỗi giao diện] Hình ảnh phóng lớn dạng modal hiển thị lệch

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#418]
![wrong-popup](https://cloud.githubusercontent.com/assets/6290970/9214492/6e8eb940-40c8-11e5-8728-305c2ffcc1fa.PNG)

Commit
cfe498b

Môi trường test : XAMPP 1.8.3
Firefox 40.

**Comment by levietpro** [comment]
em cũng bị :(

**Comment by levietpro** [comment]
lôi này đã ai fix chưa vậy ah @@

**Comment by mynukeviet** [comment]
Vâng. Đội code đang thảo luận xử lý cái này, chung cho cả NukeViet ạ.
https://github.com/nukeviet/nukeviet/issues/1358

**Comment by anhyeuviolet** [comment]
Cái này nếu xoá vài dòng trong detail.tpl là ổn. Ảnh cũng tự co lại hoàn
chỉnh. Bữa làm mà quên push lên. @@
