### ISSUE TITLE
Lỗi các nút đặt hàng; thêm vào giỏ..

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#421]
Mình đang test bản shop dev nhưng khi click vào các nút: Thêm vào giỏ hàng; đặt hàng; yêu thích thì không hoạt động, bị đơ

**Comment by anhyeuviolet** [comment]
https://github.com/nukeviet/nukeviet/issues/1271

**Comment by mynukeviet** [comment]
NkeViet develop đã fix.
