### ISSUE TITLE
global block product center lỗi đen nền, lỗi chạy song song global block product center

### ISSUE THREAD

**Issue by thanhhaionline** [nukeviet/module-shops#424]
global block product center Shops 4.017 develop nền bị đen thì phải làm sao, e thích để hình mũi tên trượt sản phẩm như cũ hơn. Vẫn bị lỗi song song global block product center khi chạy cùng vì chung js.

![center](https://cloud.githubusercontent.com/assets/13663581/9229606/2078aa4c-4148-11e5-89b1-4d6f134dfa30.jpg)

**Comment by hoanglongvnpt** [comment]
Do khối css chưa nó vì vậy bạn vào style.css tìm đến đoạn css:
figure {
    background: #949494;
    padding: 3px;
    display: block;
    float: left;
    margin: 5px 10px 10px 0;
    text-align: center
}
đổi lại màu sắc cho nó
