### ISSUE TITLE
lỗi không phân trang trong quản lý giảm giá

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#429]
Hiện tại trong quả lý giảm giá không có phân trang gây ra hiện tượng chỉ hiển thị được có 5 giảm giá
PS: triển fix đi nhá, biết chỗ rồi thì fix luôn ha :dancer: đang xử lý cái khác rồi

**Comment by vuthao** [comment]
Cái này theo mình sẽ không có nhiều, cho hiển thị hết luôn ra nhé.

**Comment by trinhthinhhp** [comment]
@vuthao ví dụ 1 tháng có 3 chương trình, 1 năm nhân lên cũng kha khá , hiển thị hết luôn chắc ớn khoản kéo chuột xuống tận dưới để điền thêm thông tin khác và xem danh sách giảm giá đã xài

**Comment by mynukeviet** [comment]
Phân ra cũng ko mất gì, mà cũng khá nhiều đó anh.
Cái này cứ để lại rồi giải quyết luôn sau.

**Comment by anhyeuviolet** [comment]
Cái này mình thấy điều chỉnh lại cơ chế giảm giá và coupon chút xíu.
Giảm giá thì theo từng SP. Chứ hiện tại phải tạo nhóm giảm giá, gán vào loại SP. Thấy không tiện cho lắm. Bước giảm giá nên thêm ngay khi đăng SP.
Về coupon, hiện tới bản này mình chưa thấy ( hoặc tìm chưa ra ). Cái coupon này hoạt động theo cơ chế giảm giá hiện tại thì chính xác hơn, do phân ra Coupon dùng được bao nhiêu lần, cho loại SP nào, hay thậm chí theo từng SP.

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/1ab847f5596b5ab07a45e004fb79a0451e45a072

@anhyeuviolet mình tách issue ra ở đây nhé https://github.com/nukeviet/module-shops/issues/431
