### ISSUE TITLE
Lỗi chức năng sử dụng coupon giảm giá ?!

### ISSUE THREAD

**Issue by levietpro** [nukeviet/module-shops#430]
Thử nghiệm trên nukeviet 4.0.22 với bản shop dev ngày 17/8
Tình trạng:
Nhập mã giảm giá (điều kiện giảm giá thoả mãn) nhưng cập nhật giỏ hàng hoặc ấn đặt hàng Giá sp ko đc cập nhật giảm mà giá vẫn giữ nguyên ?!!?

![copupon](https://cloud.githubusercontent.com/assets/13252230/9401136/d026a3ce-47f4-11e5-9d06-81bad9838360.png)
ps: đặt 2 sp , với tổng số tiền là 100000 thì mã giảm giá mới bắt đầu có tác dụng ??? trong khi điều kiện ghi từ 50k đc áp dụng rồi !?!?!?

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/0577a77874b65ba38ee6ed0fd343fc6ea167bf12
Cảm ơn @levietpro
