### ISSUE TITLE
Lỗi khi đăng sp mới trên bản news dev 4.0.23

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#444]
Như tiêu đề, khi thêm sp mới xuất hiện lỗi:
Lỗi cảnh báo: getimagesize(C:/xampp/htdocs/Developnew//Developnew/uploads/shops/2015_08/giamgia.png): failed to open stream: No such file or directory in file /includes/core/filesystem_functions.php on line 783

**Comment by mynukeviet** [comment]
Lỗi này do hàm **getimagesize**
Fixed: https://github.com/nukeviet/nukeviet/pull/1514
