### ISSUE TITLE
URL của shop chưa thu nhỏ về URl chữ thường

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/module-shops#446]
đây là ví dụ đường link shop mới nhất em cài chưa có chức năng thu nhỏ đường link giống site tin tức
---> i/shops/Giay-bup-be/GIAY-BUP-BE-NGOI-SAO-NHAP-KHAU.html

---> đây là điều mong muốn :(((( i/shops/giay-bụp-be/giay-bup-be-ngoi-sao-nhap-khau.html

**Comment by vuthao** [comment]
Hiện tại các module trong nukeviet chạy độc lập nhau bạn.
Nên cần cấu hình này sẽ phải code thêm.
