### ISSUE TITLE
Lỗi khi thêm sản phẩm và giá

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#447]
Hiện tại với bản nukeviet mới nhất 4.0.23 thì bị lỗi khi thêm sản phẩm mới (Như hình).
Đơn giá sảnh phẩm nhưng hiện thị 0.
![1](https://cloud.githubusercontent.com/assets/8292355/9537627/d23636f0-4d64-11e5-8055-24799a89752e.PNG)
![2](https://cloud.githubusercontent.com/assets/8292355/9537628/d2367e62-4d64-11e5-99f2-b19323ca2fda.PNG)

**Comment by anhyeuviolet** [comment]
Mình tin là bạn khai báo thiếu một trong các món : đơn vị tiền tệ, đơn vị khối lượng. Thử tạo các thông số đó và tạo SP lại xem sao bạn.

**Comment by motcaiten** [comment]
Em cài lại với dữ liệu mẫu thì đã ok phần này.

Còn nếu cài không dữ liệu mẫu thì bị lỗi như trên.

**Comment by anhyeuviolet** [comment]
Lý do như mình mô tả bên trên. :D

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/fd08375fcf12c34133d92dd0bd47d7a7958f5958
