### ISSUE TITLE
[Hỏi] Comment trong module

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#448]
Cho em hỏi là tùy biến phần comment trong module shop thì thực hiện chỗ nào vậy. Em tìm mãi không ra. 

Em muốn thay phần đó bằng bình luận facebook

**Comment by anhyeuviolet** [comment]
Cái này mình thấy trước mắt là phải chỉnh vào trong theme ( file TPL ) chứ chưa cấu hình trong đó được thì phải.

**Comment by motcaiten** [comment]
Vậy giờ em muốn chính trong theme để ở đoạn đó nó hiện comment bằng facebook thì phải sửa đoạn này thế nào anh

elseif( $tabs_key == 'content_comments' ) // Bình luận
                    {
                        $tabs_content = $content_comment;
                    }

**Comment by anhyeuviolet** [comment]
Bạn tạo chủ đề trên forum nhé. Sẽ có HD giúp bạn.

**Comment by motcaiten** [comment]
Em gửi rồi đó anh. Anh vào xem link và hướng dẫn dùm. Cảm ơn.

http://forum.nukeviet.vn/viewtopic.php?f=182&t=36330

**Comment by mynukeviet** [comment]
@anhyeuviolet  đã trả lời trên forum nhé @motcaiten
