### ISSUE TITLE
[Tạo đơn vị tiền tệ, khối lượng] Cần có hướng dẫn hoặc yêu cầu bắt buộc tạo khi cài Shops

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#450]
Do cái này
https://github.com/nukeviet/module-shops/issues/447

Nguyên nhân là nếu cài mới shops mà ko dùng dữ liệu mẫu thì sẽ ko có các trường như : đơn vị tiền tệ, tỉ giá, đơn vị khối lượng ....dẫn đến giá hiển thị thành 0VND dù SP được nhập giá đàng hoàng.
Do đó cần có yêu cầu tạo mới các trường này khi cài "sạch" shops, tương tự như yêu cầu tạo loại SP, hoặc cập nhật hàm tính giá ra trang chủ để tránh các vấn đề đáng tiếc.

**Comment by mynukeviet** [comment]
Cái này khi thêm sản phẩm thiếu một câu lệnh kiểm tra *_đơn vị tiền tệ_ đã có hay chưa, trong khi thêm sản phẩm mà không chọn đơn vị nó cũng không báo lỗi :D.

Fixed: https://github.com/hongoctrien/module-shops/commit/fd08375fcf12c34133d92dd0bd47d7a7958f5958
