### ISSUE TITLE
Lỗi đặt hàng sản phẩm

### ISSUE THREAD

**Issue by vinatec789** [nukeviet/module-shops#452]
Hệ thống nukeviet 4.0.23
Module: shop 4.0.17
Sau khi cài đặt nukeviet 4.0.23 và shop 4.0.17(cài thủ công) thì khi thực hiện đặt hàng hay bấm nút "yêu thích" đều không thực hiện được

**Comment by anhyeuviolet** [comment]
Shops 4.0.17 không tương thích với NV 4.0.22 trở lên. Bạn sử dụng bản Dev hiện tại của Shops mới được nhé.

**Comment by vinatec789** [comment]
Cảm ơn https://github.com/anhyeuviolet sử dụng bản dev đã khắc phục được lỗi đặt hàng, tuy nhiên trong cấu hình module shop, mình không tìm thấy chỗ nào cấu hình tích hợp thanh toán(ví dụ: tích hợp ngân lượng, bảo kim...)
mong bạn chỉ giúp!

**Comment by anhyeuviolet** [comment]
http://wiki.nukeviet.vn/nukeviet4:admin:shops:payport
Bạn tham khảo nhé ! Phần đó có thể bị ẩn đi, truy cập vào Cấu hình module của Shops, rê chuột vào Chữ cấu hình modules chút xíu nó sẽ hiện ra.

**Comment by mynukeviet** [comment]
@vinatec789 trong shops, ở mỗi phần quản lý, bạn để ý góc trên - phải có icon cuốn sách, bạn click vào đó để xem tài liệu quản trị của nó.
