### ISSUE TITLE
Khi thêm mới sản phẩm bị lỗi này?

### ISSUE THREAD

**Issue by thucvinh** [nukeviet/module-shops#453]
Nên chú ý: Undefined index: in file /modules/shops/site.functions.php on line 270
Nên chú ý    Nên chú ý: Undefined index: in file /modules/shops/site.functions.php on line 275
Nên chú ý    Nên chú ý: Undefined index: VND in file /modules/shops/site.functions.php on line 253
Nên chú ý    Nên chú ý: Undefined offset: 1 in file /modules/shops/site.functions.php on line 254
Lỗi cảnh báo   Lỗi cảnh báo: getimagesize(D:/xampp/htdocs/TWAY//TWAY/uploads/shops/2015_08/in-an-offset-gia-re-song-tam-in-danh-thiep-1.jpg): failed to open stream: No such file or directory in file /includes/core/filesystem_functions.php on line 783

**Comment by anhyeuviolet** [comment]
https://github.com/nukeviet/module-shops/issues/447
https://github.com/nukeviet/module-shops/issues/450

Xem xét tạo đủ các thông số thì sẽ ko bị nữa.

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/fd08375fcf12c34133d92dd0bd47d7a7958f5958
