### ISSUE TITLE
Tích hợp thanh toán qua Bảo Kim bị lỗi

### ISSUE THREAD

**Issue by PhucSD** [nukeviet/module-shops#454]
Dù đã đăng ký merchant site đúng hết các thông tin nhưng khi nhấp thanh toán qua Bảo Kim thì họ báo là:

400 - An Error Was Encountered
Xin lỗi, hành động của bạn không thể hoàn thành vì:
Thong tin thanh toan khong chinh xac:
business phải có giá trị.
order_id phải có giá trị.
total_amount phải có giá trị.
merchant_id phải có giá trị.
checksum phải có giá trị.

Có phải là code của module này có vấn đề không, xin xem lại. Cảm ơn đội ngũ dev nhiều.

**Comment by ThinhNguyenVB** [comment]
@PhucSD Bạn kiểm tra lại thông tin tài khoản bảo kim nhé, hiện tại mình coi thì thấy bình thường bạn nhé

**Comment by hoaquynhtim99** [comment]
Hiện tại shops mới nhất phần Bảo Kim đã bị loại do code lâu chưa cập nhật
