### ISSUE TITLE
Góp ý về block cart

### ISSUE THREAD

**Issue by levietpro** [nukeviet/module-shops#456]
Góp ý về block giỏ hàng :
Làm cách nào để đưa toàn bộ link của giỏ hàng (điểm tích luỹ, đơn hàng, yêu thích,lịch sử...) vào modal popup như cái block user_button nhìn cho gọn gàng và chuyên nghiệp hơn chứ hiện tại cứ list ra trong cái block cart nhìn hơi cổ và chuối :-1:

**Comment by ThinhNguyenVB** [comment]
cái này thì bạn tự mắm muối lại thôi, chứ site nào cũng thế này thế kia thì hơi khó

**Comment by mynukeviet** [comment]
@levietpro cái này làm nhiệm vụ của giao diện. Mặc định shops đã cung cấp đủ các thông tin, tùy theo giao diện mà người lập trình định dạng lại cho nó nhé.
