### ISSUE TITLE
Nên hay không thiết kế một themes riêng cho Shop?

### ISSUE THREAD

**Issue by tuyenclub** [nukeviet/module-shops#457]
Mình thấy Shop hiện dùng chung giao diện mặc định của phần tin tức nên nó khô cứng và nhàm chán.
Với nhưng người tay ngang như mình thì việc tạo một themes mới dành riêng cho shop thì thực sự là một khó khăn lớn. Vì thế mình đề nghị module Shop nên có một themes default riêng để anh em không chuyên có thể tùy biến nó đi một chút thành riêng mình. Giao diện shop sẽ thiết kế theo phong cách chuyên nghiệp theo xu hướng các code shop hiện nay sẽ giúp module ăn khách hơn qua đó nukeviet cũng sẽ được chú ý nhiều hơn.

**Comment by anhyeuviolet** [comment]
Mình thấy cái này ko cần thiết. 
Các nhà phát triển theme sẽ có việc để làm hơn.

**Comment by ThinhNguyenVB** [comment]
cái này thì tự làm giao diện module shops theo dự án cần thui, không phải làm riêng gì hết
