### ISSUE TITLE
Vấn đề mã giảm giá

### ISSUE THREAD

**Issue by sutuem** [nukeviet/module-shops#458]
Chào đội code. Mình thấy ví dụ khi có mã giảm giá v100(giảm 100K), trong phần đơn hàng khi tick vào thì trừ đi 100K, khi không tích thì trở về giá cũ. Khi chuyển sang phàn thanh toán mặc dù đã bỏ phần sử dụng mã giảm giá đi rồi nhưng số tiền vẫn bị trừ (vẫn bị sử dụng mã giảm giá). Mong đội code xem xét vấn đề này sớm nhé. Đây là 1 chức năng khá quan trọng

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/9502688e759f87200bcf726db724ad963e687422
