### ISSUE TITLE
Lỗi quản trị đơn hàng.

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#459]
Trong phần xem chi tiết từng đơn hàng có phần tên sản phẩm kèm link dẫn tới nhưng đường link này bị sai.

Ví dụ : Tên sản phẩm là "Áo thời trang" có link đúng là http://domain.com/ao/ao-thoi-trang.html. Khi khách đặt hàng sản phẩm này và có mã đơn hàng là NV022 thì click vào tên sản phẩm thì bung ra đường link http://domain.com/ao/ao-thoi-trang-22.html (tức là thêm mã đơn hàng vào đường link)

**Comment by anhyeuviolet** [comment]
Fix https://github.com/anhyeuviolet/module-shops/commit/99f581ff8ef9949af27fcfa1f33a451f4dd113d2
