### ISSUE TITLE
Thiếu so sánh

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/module-shops#460]
Trong theme.php của shops ở funtions  viewcat_page_list thiếu đoạn xuất ra so sánh
    else
            {
                if( $pro_config['show_compare'] == 1 )
                {
                    if( !empty( $compare_id ) )
                    {
                        $ch = ( in_array( $data_row['id'], $compare_id )) ? ' checked="checked"' : '';
                        $xtpl->assign( 'ch', $ch );
                    }
                    $xtpl->parse( 'main.row.compare' );
                }
            }

sửa thành

```
// So sanh san pham
        if( $pro_config['show_compare'] == 1 )
        {
            if( !empty( $compare_id ) )
            {
                $ch = ( in_array( $data_row['id'], $compare_id )) ? ' checked="checked"' : '';
                $xtpl->assign( 'ch', $ch );
            }
            $xtpl->parse( 'main.row.compare' );
        }
```

**Comment by anhyeuviolet** [comment]
Cái này anh @nhimthulinh bị nhầm á.
Cái này nếu là Admin thì sẽ hiển thị chức năng sửa xoá, ngược lại thì sẽ hiển thị so sánh. Ko phải lỗi nha anh.

**Comment by mynukeviet** [comment]
Xác nhận đúng như @anhyeuviolet nói.

**Comment by ThinhNguyenVB** [comment]
Đã fix: https://github.com/nukeviet/module-shops/pull/551/commits/8c74203baf6bd537e0271c509ad8693b26b8582e
