### ISSUE TITLE
Lỗi khi sửa chuyên mục con

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/module-shops#461]
Bị trẳng trang nếu di chuyển chuyên mục con ra thành chuyên mục chính hoặc qua các chuyên mục chính khác đều bị trắng trang

**Comment by anhyeuviolet** [comment]
Fix https://github.com/anhyeuviolet/module-shops/commit/99f581ff8ef9949af27fcfa1f33a451f4dd113d2
