### ISSUE TITLE
Thông báo từ Hệ thống Lỗi hệ thống không cập nhật được nội dung.

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/module-shops#463]
Thông báo từ Hệ thống
Nên chú ý    Nên chú ý: Undefined index: warranty in file /modules/shops/admin/content.php on line 562
Nên chú ý    Nên chú ý: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'vi_warranty' cannot be null

Lỗi hệ thống không cập nhật được nội dung.

**Comment by anhyeuviolet** [comment]
Trường bảo hành (warranty) mình nhớ bỏ khỏi shops hiện tại rồi mà. Bạn có thể cho biết thông tin bản shops bạn đang dùng không ?

**Comment by NukeVietCMS** [comment]
Mình sử dụng shops 4.0.18 cũng cùng 1 bản đó mà không hiểu sau lần này nó lại bóa như thế nữa. Mình cài trên 3 site thì chỉ có 1 site là có thông báo như thế nên cũng chẳn hiểu vì sau nữa

**Comment by mynukeviet** [comment]
@NukeVietCMS bạn test lại bản mới nhất nhé.
