### ISSUE TITLE
Lỗi cảnh báo: Hình minh họa  /includes/core/filesystem_functions.php on line 783

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/module-shops#464]
Thông báo từ Hệ thống
Lỗi cảnh báo: getimagesize(/home/muabandogo/domains/muabandogo.info/public_html/URL của hình ảnh): failed to open stream: No such file or directory in file /includes/core/filesystem_functions.php on line 783

Lổi này xuất hiện khi đăng 1 sản phẩm mà phần ảnh minh họa không được up lên host. URL hình ảnh từ 1 trang web khác.
Hình ảnh vẫn có nhưng thông báo như trên.

**Comment by anhyeuviolet** [comment]
Bạn @NukeVietCMS thử tải lại code Shops và up lại SP xem còn bị tình trạng này không ? Hiện thời thì mình không nhận thấy lỗi tương tự.

**Comment by hiidemo** [comment]
Mình cũng bị lỗi y hệt thế này

**Comment by mynukeviet** [comment]
Cái lỗi do hàm getimagesize
Fixed: https://github.com/nukeviet/nukeviet/pull/1514
