### ISSUE TITLE
Lỗi Rich snippets

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#466]
Em thấy cái Rich snippets hình như bị lỗi. Tuy là có đánh giá sản phẩm rồi nhưng nó vẫn chưa add lên trên.
![capture](https://cloud.githubusercontent.com/assets/8292355/10098848/9b40de56-63ae-11e5-895a-78664d6e8263.PNG)

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/5e8051b066f89ae9a6956abb0cded467a154782e
