### ISSUE TITLE
Lỗi trang trắng khi xóa bỏ nhóm

### ISSUE THREAD

**Issue by nguyenlapvn** [nukeviet/module-shops#467]
Khi xóa bỏ nhóm nhưng trong nhóm có sản phẩm và được đề nghị chuyển sản phẩm vào nhóm khác. Sau khi chọn nhóm sản phẩm được chuyển sang và nhấn nút " Thực hiện" thì sẽ bị lỗi trang trắng.
Môi trường thử nghiệm
Windown XP SP3
Phần mềm sever: Xampp 1.8.2
PHP 5.4
Nukeviet 4.2.3

**Comment by ThinhNguyenVB** [comment]
@hongoctrien  chỗ này thiếu function nv_check_movegroup để di chuyển sang các mục khác

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/db0cd1343f7fe1b6764e643bb87abe7240a74f5a

**Comment by ThinhNguyenVB** [comment]
Phần này đã fix, đề nghị close lại topic
