### ISSUE TITLE
Hình không responsive

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-shops#468]
http://forum.nukeviet.vn/viewtopic.php?f=178&t=36539

**Comment by ThinhNguyenVB** [comment]
@hongoctrien đây nhé: https://github.com/ThinhNguyenVB/module-shops/commit/94e583c53017531074d501ba50831498bebcb7a4

**Comment by mynukeviet** [comment]
:D

**Comment by ThinhNguyenVB** [comment]
@hongoctrien gì thế?

**Comment by anhyeuviolet** [comment]
Cách này giải quyết về tạm thời thì tốt, nhưng có lẽ nên có phương án chuẩn mực hơn. Đang suy nghĩ :D

**Comment by ThinhNguyenVB** [comment]
@anhyeuviolet thì nó cứ gặp thẻ img là respon thôi, chứ giờ mỗi người post một kiểu đến mức đè đống một loạt thẻ html thì sao mà bắt được hết :dancer:

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/50aa30da4e5a8080a15edb505775b5c5a7420ee2
