### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/module-shops#469]
Nên chú ý: Undefined index: VND in file /modules/shops/site.functions.php on line 270
Nên chú ý    Nên chú ý: Undefined index: VND in file /modules/shops/site.functions.php on line 275
Nên chú ý    Nên chú ý: Undefined index: VND in file /modules/shops/site.functions.php on line 253
Nên chú ý    Nên chú ý: Undefined offset: 1 in file /modules/shops/site.functions.php on line 254

**Comment by anhyeuviolet** [comment]
https://github.com/nukeviet/module-shops/issues/447
https://github.com/nukeviet/module-shops/issues/450
https://github.com/nukeviet/module-shops/issues/453

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/fd08375fcf12c34133d92dd0bd47d7a7958f5958
