### ISSUE TITLE
Lỗi so sánh sản phẩm

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#471]
Chức năng ngoài trang chủ thì ok nhưng khi vào từng danh mục sản phẩm thì bị lỗi. Dù đã chọn 2,3 sản phẩm nhưng vẫn hiện thông báo là số lượng so sánh phải lớn hơn hoặc bằng 2.

Phiên bản NukeViet   4.0.23
Phiên bản PHP    5.4.36
Giao thức giữa máy chủ và PHP   Apache/2, cgi-fcgi
Hệ điều hành máy chủ   LINUX
Phiên bản Database   mysql 5.5.41

**Comment by vuthao** [comment]
Bạn kiểm tra lại bản mới nhất xem đã hết lối chưa nhé.

**Comment by motcaiten** [comment]
HIện tại ok rồi anh.
