### ISSUE TITLE
Lỗi khi cài đặt thêm ngôn ngữ tiếng anh. module shops bị cài trắng dữ liệu cả 2 ngôn ngữ

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/module-shops#475]
Lỗi khi cài đặt thêm ngôn ngữ tiếng anh. module shops bị cài trắng dữ liệu cả 2 ngôn ngữ anh việt
Khi thực hiện cài lại module thì có thông báo lỗi vì lý do lệnh cài đặt đã không được thực hiện

**Comment by mynukeviet** [comment]
> Lỗi khi cài đặt thêm ngôn ngữ tiếng anh. module shops bị cài trắng dữ liệu cả 2 ngôn ngữ anh việt

Có vẻ đây là vấn đề https://github.com/nukeviet/nukeviet/issues/1671

> Khi thực hiện cài lại module thì có thông báo lỗi vì lý do lệnh cài đặt đã không được thực hiện

Fixed: https://github.com/nukeviet/module-shops/commit/7adceab010a2ce4d1bd06c1af98e23a50bc7fd54

**Comment by ThinhNguyenVB** [comment]
Phần này đã fix close lại nhé
