### ISSUE TITLE
lỗi ảnh đại diện sản phẩm của module shops

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-shops#484]
Khi sửa sản phẩm mặc định của hệ thống không thay đổi ảnh thì bị mất ảnh và khi thêm ảnh mới vô không đính được vào

**Comment by mynukeviet** [comment]
Kiểm tra và không thấy lỗi này @ThinhNguyenVB

**Comment by ThinhNguyenVB** [comment]
Đã thấy fix ko còn lỗi
