### ISSUE TITLE
Lỗi khi cài đặt mới module shops

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-shops#486]
Khi cài đặt mỡi phát sinh lỗi và không vào được module shops
Nên chú ý: Undefined index: use_shipping in file /modules/shops/admin.menu.php on line 24
Nên chú ý    Nên chú ý: Undefined index: review_active in file /modules/shops/admin.menu.php on line 31
Nên chú ý    Nên chú ý: Undefined index: active_warehouse in file /modules/shops/admin.menu.php on line 36
Nên chú ý    Nên chú ý: Undefined index: use_coupons in file /modules/shops/admin.menu.php on line 48
Nên chú ý    Nên chú ý: Undefined index: point_active in file /modules/shops/admin.menu.php on line 53
Nên chú ý    Nên chú ý: Undefined index: download_active in file /modules/shops/admin.menu.php on line 58
Nên chú ý    Nên chú ý: Undefined index: template_active in file /modules/shops/admin.menu.php on line 74
Nên chú ý    Nên chú ý: Undefined index: active_payment in file /modules/shops/admin.menu.php on line 80

**Comment by NukeVietCMS** [comment]
Cái này tôi cũng bị y như bạn
![cai dat bao loi](https://cloud.githubusercontent.com/assets/8376014/10965097/528932c2-83dd-11e5-9193-2dc2304971ce.png)

Khi bấn vào modules shops thì báo lỗi:
Lỗi máy chủ
500

Tất cả các menu của modules này khi vào điều báo lỗi  "Lỗi máy chủ 500"
Các modules khác thì vẫn bình thường.

**Comment by vuthao** [comment]
Module Shop hiện tại chưa tương thích với bản nukeviet mới nhất.
Xem chi tiết tại: http://forum.nukeviet.vn/viewtopic.php?f=163&t=36735

**Comment by quehvbg** [comment]
Mình đã cài module shop kết hợp với nukeviet thành công trên hệ thống hosting và domain.

Website test cụ thể các bạn có thể vào trang http://htcomputer.vn

Các phiên bản cài như sau :

1: Nukeviet 4.0.23
2: Cài Module shop 4.017 theo thủ công trước sau đó cài đè bản Module shop dev cũng bằng thủ công để fix lỗi click yêu thích và đặt hàng
3: Thêm trường order_address vào bảng module shop order trong database để fix lỗi khi đặt hàng trên website.

Trên đây là các thao tác cài và fix lỗi, hy vọng có thể giúp ích được các bạn muốn dùng NV4 và module shop vào công việc của mình.

Nếu các bạn thắc mắc và muốn hỗ trợ liên hệ mình qua SDT 0983.138.328 hoặc email quehvbg@gmail.com.

Xin chân thành cảm ơn cộng đồng Open Source.

**Comment by ThinhNguyenVB** [comment]
@quehvbg ối trời, 23 với 17 kết hợp thì đẻ đâu ra lỗi mình báo cơ chứ, hiện tại mình đang chạy 24 và 18 mới sinh ra lỗi đó và hoàn toàn dùng bản mới nhất cài mới toanh
cách bạn làm thì chỉ là khắc phục tạm thời, nếu bạn làm một site mới thì ngồi nhìn thôi :dancer:

**Comment by quehvbg** [comment]
@ThinhNguyenVB  :)) do bạn không nói rõ là môi trường cài đặt và các phiên bản nên mình comment vậy, có thể sẽ có ích cho các bạn cần môi trường tạm ổn định để hoạt động và nâng cấp khi phát hành chính thức sau. 
Thanks bạn đã cmt

**Comment by vuthao** [comment]
Lỗi cài đặt này đã được fix tại: https://github.com/nukeviet/module-shops/commit/39df529174b826dcb17f44afd78a22ce3593ba43
Các bạn kiểm tra lại nhé.

**Comment by lyhuutrong** [comment]
cho mình hỏi hiện tại thì dùng module shop nào và nukeviet mấy thì không bị lỗi nữa ạ?
Mình xin cảm ơn rất nhiều

**Comment by quehvbg** [comment]
Theo mình thì bạn nên dùng shop 4.0.17 và nuke 4.0.23 vì hai bản này
release lâu và được test nhiều, nếu bạn muốn có những tính năng mới thì
dùng shop 4.0.18 hoặc các bản sau này.

Chịu khó tìm hiểu trên diễn đàn xem bản nào tương thích với nukeviet nào
nữa là ok.

Vào 20:24 Ngày 23 tháng 11 năm 2015, lyhuutrong notifications@github.com
đã viết:

> cho mình hỏi hiện tại thì dùng module shop nào và nukeviet mấy thì không
> bị lỗi nữa ạ?
> Mình xin cảm ơn rất nhiều
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nukeviet/module-shops/issues/486#issuecomment-158932561
> .

## 

Many thanks.
Regard QueHV
Mobile : 0983.138.328
Skype : quehvbg
Email : quehvbg@gmail.com

**Comment by lyhuutrong** [comment]
Cho mình hỏi nếu xài nukeviet 4.0.23 và bản 4.0.17 tương thích thì xài lâu
có phát sinh lỗi ko ạ? Vì mình xài nuke 4.0.23 và bản shop develop xài được
khoảng 2 tuần thì nó báo lỗi unlink gì đó ạ.

Vào Thứ Tư, ngày 25 tháng 11 năm 2015, quehvbg notifications@github.com
đã viết:
