### ISSUE TITLE
khi click thanh toán xong thì hiển thị trang trắng

### ISSUE THREAD

**Issue by vipk31** [nukeviet/module-shops#488]
Môi trường localhost
Module Shops bản dev
## NukeViet 4.0 Open Beta 9 (v4.0.23 - 28/08/2015)

khi click thanh toán xong thì hiển thị trang trắng
vào admin thì vẫn thấy đơn đạt hàng
Mong muốn : khách hàng thanh toán hóa đơn xong thì hiển thị lại trang chủ

**Comment by mynukeviet** [comment]
> khi click thanh toán xong

Cụ thể là click vào đâu bạn?
Nếu là cổng thanh toán bạn cho mình hỏi luôn là cổng nào ạ?

**Comment by vipk31** [comment]
khi click vào "Gửi thông tin phiếu đặt hàng"
 thì nó chuyển sang trang trắng
(như hình)
![capture](https://cloud.githubusercontent.com/assets/12049629/11455632/c24e9afa-969a-11e5-84ef-a59d5a50790e.PNG)

**Comment by mynukeviet** [comment]
@vipk31 bạn đang dùng shops phiên bản nào ạ?

**Comment by hoaquynhtim99** [comment]
Bạn check lại ở bản mới nhất nhé, nếu còn mở lại Issue này giúp mình
