### ISSUE TITLE
Lỗi trong admin chức năng xóa sản phẩm chưa được!

### ISSUE THREAD

**Issue by anhhai986** [nukeviet/module-shops#489]
Lỗi trong admin chức năng xóa sản phẩm chưa được!

**Comment by mynukeviet** [comment]
Không biết bạn sử dụng phiên bản nào ạ?
Mình kiểm tra trên shops + NukeViet mới nhất đều không gặp lỗi xóa sản phẩm như bạn nói.
Bạn vui lòng kiểm tra lại, nếu vẫn lỗi thì cung cấp thêm thông tin như tại https://github.com/nukeviet/module-shops/blob/develop/CONTRIBUTING.md để mình kiểm tra lại.
Cảm ơn bạn.

**Comment by mynukeviet** [comment]
@anhhai986 bạn cài NukeViet 4.0.23 thì cài shops 4.0.18 nhé. Phiên bản bạn dùng chưa tương thích nên lỗi đó ạ.

**Comment by hoaquynhtim99** [comment]
Bạn check lại ở bản mới nhất nhé, nếu còn mở lại Issue này giúp mình
