### ISSUE TITLE
Nukeviet 4.0.23 thích hợp với Modules shop nào

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/module-shops#490]
Chào mọi người. mọi người cho mình hỏi nukeviet 4.0.23 thích hợp với modules shop nào mà không bị lỗi gì hết ạ ? mong mọi người giúp đỡ mình với ạ.

**Comment by Actionmankaefer** [comment]
Hiện tại mình dùng Nukeviet 4.0.23 và sử dụng shop 4.0.17, sau khi chỉnh :
- Tập tin modules/shops/js/admin.js chuyển sang (và đổi tên thành) themes/admin_default/js/shops.js
- Tập tin modules/shops/js/user.js chuyển sang (và đổi tên thành) themes/default/js/shops.js 

Trong tập tin:
themes/default/modules/shops/detail.tpl
tìm từ: nv_sitelang
đổi thành: nv_lang_data

Trong tập tin:
themes/default/js/shops.js (tập tin này vừa cop vào)
tìm: nv_sitelang
đổi thành: nv_lang_data
tìm: nv_siteroot
đổi thành: nv_base_siteurl

Trong tập tin themes/default/modules/shops/order.tpl

Thì lỗi Javascript đã khắc phục được.
Nhưng mình chưa giải quyết được 
- việc gửi mail xác nhận đến người mua và người quản lý để theo dõi.
- Capcha đánh giá.

Mong mọi người fix giúp.
Thanks All!

**Comment by mynukeviet** [comment]
@Actionmankaefer ở đây chỉ giành cho góp ý và báo lỗi shops.
Cái này bạn post lên diễn đàn cho tiện thảo luận nhé.

**Comment by mynukeviet** [comment]
@lyhuutrong NukeViet 4.0.23 và Shops 4.0.18 bạn nhé https://github.com/nukeviet/module-shops/releases/tag/4.0.18

Song bản này vẫn còn một số lỗi, nhưng chấp nhận được. Bản shops mới nhất chúng tôi đã sửa nhiều lỗi, sẽ dùng trong NukeViet 4.0.24 sắp tới.
