### ISSUE TITLE
khách đặt hàng, quản lý site không nhận được mail - quản lý xác nhận đặt hàng, khách không nhận được mail.

### ISSUE THREAD

**Issue by Actionmankaefer** [nukeviet/module-shops#492]
Sorry đội code nhưng mình không biết đây là tính năng mới hay lỗi nhưng như tiêu đề có ghi rõ:
1. khi khách đặt hàng thì quản lý site không nhận được mail thông báo có khách đặt hàng để vào duyệt hàng.
2. Khi Quản lý site duyệt đơn hàng thì khách không nhận được mail thông báo quản lý site đã nhận được yêu cầu đặt hàng.

Rất mong đội code hoàn thiện tính năng này vì nó khá cần thiết.
Cám ơn đội code rất nhiều!

**Comment by mynukeviet** [comment]
Bạn chắc chắn site của bạn gửi mail được chứ.
Thường thì bạn cần cấu hình SMTP thì mới gửi email được nhé.

**Comment by Actionmankaefer** [comment]
Thanks Hongoctrien.
Sau khi fix SMTP thì có một số lỗi sau, mình báo luôn để Shop được hoàn thiện.
1. Gửi cho khach đến 2 mail trong đó mail ARRAy là gì vậy? có phải lỗi không? 
2. Quản trị không nhận được thông báo khách đặt hàng qua mail. Cảm phiền cho mình hỏi đây là tính năng nâng cao hay là tính năng có trong bản shop nyaf vậy.  Thanks!
3. Khách nhận được mail nhưng khi click vào Link xem đơn hàng tại đây thì hiện lỗi Object not found với link:
http://localhost:8080/nukeviet/nukeviet/index.php?language=vi&nv=shops&op=payment&order_id=2&checkss=ee16452a8e8ac044e8156c783df4b973

Thanks!

**Comment by mynukeviet** [comment]
> 1. Gửi cho khach đến 2 mail trong đó mail ARRAy là gì vậy? có phải lỗi không? 
> 2. Khách nhận được mail nhưng khi click vào Link xem đơn hàng tại đây thì hiện lỗi Object not found với link:
>    http://localhost:8080/nukeviet/nukeviet/index.php?language=vi&nv=shops&op=payment&order_id=2&checkss=ee16452a8e8ac044e8156c783df4b973

Cảm ơn bạn, mình sẽ kiểm tra lại

> 1. Quản trị không nhận được thông báo khách đặt hàng qua mail. Cảm phiền cho mình hỏi đây là tính năng nâng cao hay là tính năng có trong bản shop nyaf vậy. Thanks!

Bạn vào cấu hình module, tìm đến **Các nhóm nhận thông báo từ hệ thống** chọn nhóm QUản trị nhận mail nhé

**Comment by Actionmankaefer** [comment]
Ok Thanks bạn nhiều!

**Comment by mynukeviet** [comment]
@Actionmankaefer bạn đang dùng phiên bản NukeViet và shops nào vậy ạ.

**Comment by Actionmankaefer** [comment]
minh đang dùng Nuke beta 9 và shop 4.0.17.

**Comment by Actionmankaefer** [comment]
1. Ah có thêm một lỗi nữa mình mới phát hiện là khi xem trang detail shop thì xem source code phát hiện lỗi load ảnh với đường link :
   http://localhost:8080/nukeviet/nukeviet/assets/shops/2015_11/usda_wheat.jpg
   mặc dù trang detail không thấy lỗi giao diện.
2. Cho mình hỏi riêng việc này với được không? vì post trong FR lâu phản hồi quá.
   Vấn đề là trang mình có sử dụng slide ảnh background , src ảnh để trong file javascript.
   Nhưng để link ảnh tương đối trong file js thì bị lỗi load ảnh khi sử dụng trang chủ bằng module Home.
   Code như sau:
   $(window).ready(function() {
   
   'use strict';
   
   $.vegas('slideshow', {
   
     backgrounds:[
   
   ```
   { src:'../themes/EGRET/images/bg-slider/bg-1.jpg', fade:1000 },
   { src:'../themes/EGRET/images/bg-slider/bg-2.jpg', fade:1000 },
   { src:'../themes/EGRET/images/bg-slider/bg-3.jpg', fade:1000 }
   ```
   
     ]
   })();
   });

Rất mong bạn có thể giúp ,mình với,
Cám ơn bạn rất nhiều!

**Comment by mynukeviet** [comment]
> 1. Gửi cho khach đến 2 mail trong đó mail ARRAy là gì vậy? có phải lỗi không?
> 2. Khách nhận được mail nhưng khi click vào Link xem đơn hàng tại đây thì hiện lỗi Object not found với link:
>    http://localhost:8080/nukeviet/nukeviet/index.php?language=vi&nv=shops&op=payment&order_id=2&checkss=ee16452a8e8ac044e8156c783df4b973

Hình như bạn đang dùng phiên bản cũ? Mấy lỗi này mình thấy đã fix.

**Comment by alialichau** [comment]
Cho mình hỏi làm sao để trong mail đơn hàng ghi luôn bảng thông tin vận chuyển nhỉ ? Thanks
