### ISSUE TITLE
khi đặt hàng có 2 nhóm size khác nhau, chỉ có thể chọn một, đặt hàng thêm nhóm kia không được

### ISSUE THREAD

**Issue by Actionmankaefer** [nukeviet/module-shops#501]
Như tiêu đề, khi mình cho 1 sản phẩm có nhiều hơn 2 nhóm khác nhau , thì khi khách chọn một sản phẩm thuộc nhóm này và muốn chọn thêm một sản phẩm nửa thuộc nhóm kia thì không thể chọn mà trang tự mặc định khách thêm số lượng cho nhóm đầu.

Rất mong đội code hỗ trợ dùm tính năng này.
Chân thành cám ơn mọi người!

**Comment by hqc210185** [comment]
kiểm tra thấy vấn đề này đã được xử lý
