### ISSUE TITLE
Khi cài xong bản mới nhất báo lỗi sau

### ISSUE THREAD

**Issue by thucvinh** [nukeviet/module-shops#506]
Lỗi cảnh báo: scandir(D:/Xampp/htdocs/binhphongsaigon/assets/shops/files_tpl,D:/Xampp/htdocs/binhphongsaigon/assets/shops/files_tpl): The system cannot find the file specified. (code: 2) in file /modules/shops/admin/cat.php on line 37
Lỗi cảnh báo   Lỗi cảnh báo: Invalid argument supplied for foreach() in file /modules/shops/admin/cat.php on line 38

**Comment by hqc210185** [comment]
hiện tại không thấy lỗi này
