### ISSUE TITLE
Lỗi module shop 4.0.18

### ISSUE THREAD

**Issue by quangvinhdangvn** [nukeviet/module-shops#508]
Module shop bản 4.0.18 sau khi cài đặt thủ công trên nuke 4.0.23 thì không có trường số lượng trong kho, do vậy mà số lượng trong kho luôn là 0 và luôn ở tình trạng hết hàng.
Xin xem xét vấn đề này!

**Comment by mynukeviet** [comment]
Bạn cần nhập kho đã nhé
