### ISSUE TITLE
Lỗi khi cài module shop lên  NUKEVIET 4.0.25

### ISSUE THREAD

**Issue by minhlaoleu** [nukeviet/module-shops#509]
Xin chào, lỗi phát sinh là trắng trang và toàn bộ khu vực admin đều trắng trang khi cài module shop phiên bản Module Shops 4.0.16 (Release Candidate 1) lên NUKEVIET 4.0.25

Thông tin hệ thống:
Linux mint 17.2
![screenshot](https://cloud.githubusercontent.com/assets/2928316/12350580/8914831e-bbaa-11e5-8a03-1ce5256eb0d4.png)

**Comment by hoaquynhtim99** [comment]
Có NukeViet 4.0.25 khi nào ta

**Comment by minhlaoleu** [comment]
Mình copy y chang từ cái changelog.txt ra mà :))

+NUKEVIET 4.0.25
 +- Update jQuery v2.2.0 
 +- Update jQuery Validation Plugin - v1.14.0
 +- Optimizer class XTemplate for NukeViet
 +- Update utf8 lookup: fix check email

**Comment by minhlaoleu** [comment]
Mình check error.log của apache2 thì ko thấy báo gì. Check log của nukeviet /www/flower_shop/data/logs/error_logs.log thì báo thế này:

[Fri, 15 Jan 2016 23:58:24 +0700] [127.0.0.1] [Notice(8): session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13)] [FILE: /vendor/vinades/nukeviet/Core/Request.php] [LINE: 384]

Hồi chiều thì lại báo lỗi khác. Nó báo lỗi trùng khoá Primary của shop @@

**Comment by anhyeuviolet** [comment]
Shops còn chưa lên được 4.0.24 =_=

**Comment by vuthao** [comment]
Mình mới nâng cấp cho tương thích với bản 4.0.24, các bạn test lại dùm nhé: https://github.com/nukeviet/module-shops/tree/develop

**Comment by minhlaoleu** [comment]
Cám ơn @vuthao , để mình test thử :smile:
