### ISSUE TITLE
Lỗi: Ứng dụng này có cấu trúc không phù hợp và có thể gây nguy hại đến website. Để đảm bảo an toàn, hệ thống từ chối việc tiếp tục cài đặt ứng dụng này

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/module-shops#510]
Mở rộng -> Quản lý ứng dụng -> Cài đặt ứng dụng

Thông tin ứng dụng được tải lên:
Dung lượng: 684.59 KB
Tổng số file + folder: 328
Tên ứng dụng: shops
Loại: Module
Phiên bản: 4.0.25
Tác giả: VINADES.,JSC (nukeviet.store@vinades.vn)
Số file trùng: 0
Số file cấu trúc không phù hợp: 4
Lỗi: Ứng dụng này có cấu trúc không phù hợp và có thể gây nguy hại đến website. Để đảm bảo an toàn, hệ thống từ chối việc tiếp tục cài đặt ứng dụng này

Phiên bản sử dụng: Nukeviet 4.0.25

![c u truc khong phu h p](https://cloud.githubusercontent.com/assets/8376014/12502310/bf3fe40c-c0f9-11e5-9312-43adb4d6af01.jpg)

**Comment by anhyeuviolet** [comment]
Gói này tới giờ vẫn phải cài thủ công.

**Comment by hoaquynhtim99** [comment]
Phiên bản kế tiếp sẽ cài tự động được hoặc cập nhật file `admin/extensions/upload.php` theo https://github.com/hoaquynhtim99/nukeviet/blob/3647c4628dbdfb0aa02654339d5c2eee72260524/admin/extensions/upload.php
