### ISSUE TITLE
lỗi tùy biến dữ liệu

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/module-shops#511]
Không xóa được tùy biến dữ liệu
![koxoadc](https://cloud.githubusercontent.com/assets/2918834/12545555/f26e501a-c375-11e5-968f-2a0a2e618579.jpg)
Module Shops 4 RC 1 4.0.25
khi tạo vào chi tiết sản phẩm trong admin thì vẫn ko hiện ra. Module Shops 4 RC   4.0.17 chạy chức năng này ok

**Comment by nguyengiakt** [comment]
module shop có vẻ như ko đc để ý?

**Comment by thucvinh** [comment]
Bạn mở file detemplate.php  tìm đến dòng 20 thay câu truy cấp sql thành

`$template = $db->query("SELECT " . NV_LANG_DATA . "_title, alias FROM " . $db_config['prefix'] . "_" . $module_data . "_template WHERE id =" . $id)->fetch();`

**Comment by nguyengiakt** [comment]
cũng vậy à bạn

**Comment by xuanthuy235** [comment]
Cảm ơn bạn thucvinh nhé. bạn hướng dẫn chuẩn rồi. truy vấn trong file đó thiếu biến ngôn ngữ

**Comment by ThinhNguyenVB** [comment]
phần xóa custom fields đã fix ở đây bạn nhé, cả thao tác check nhầm sang cột trạng thái: https://github.com/nukeviet/module-shops/pull/551/commits/227e5ac5bc964d6921e0d27eb63b4de5a00d42e5
