### ISSUE TITLE
lỗi dữ liệu tùy biến tự thêm br

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/module-shops#516]
Mình đã cập nhật bản shop mới, dữ liệu tùy biến chạy đã ổn định, tuy nhiên cái kiểu định dạng editor khi thêm dữ liệu thì mỗi dòng xuống hàng code tự thêm <br/>

**Comment by nguyengiakt** [comment]
ko biết là lỗi hay người phát triển muốn vậy, dư ra một số <br/> trong file file fields.check.php ![a](https://cloud.githubusercontent.com/assets/2918834/13564698/2be6fba2-e47e-11e5-8c30-27341ceeefcf.jpg)

**Comment by vuthao** [comment]
@nguyengiakt bạn mô tả ký hơn để các bạn khác kiểm tra nhé.
Nhìn qua mình cũng chưa biết lỗi tại đâu.

**Comment by nguyengiakt** [comment]
mình fix được rồi bạn, tức là khi dữ liệu tùy biến tạo xong vào sản phẩm thêm thì cứ cách 1 dòng ký tự nó sẽ hiện ra khoảng cách, vào database kiểm tra thì nó insert tự động 1 dòng br, thì mình check fields.check.php thì dư ra mấy cái br, xóa nó đi thì ok
![b](https://cloud.githubusercontent.com/assets/2918834/13565021/24996464-e480-11e5-981a-5b8c1b7bf70f.jpg)

**Comment by vuthao** [comment]
Mình đã sửa lại cái này: https://github.com/nukeviet/module-shops/commit/6db87e8ee96775f936ba5b2b0789356e8a829ec6
