### ISSUE TITLE
Lỗi hiển thị khi tạo Module ảo của Module Shops

### ISSUE THREAD

**Issue by vandien** [nukeviet/module-shops#517]
Mình có tạo Module ảo của Module shops, mọi việc về cấu hình và nhập liệu đều ổn. Nhưng khi hiển thị thì phần nội dung chi tiết lại ẩn đi. ( Vui lòng xem demo ở địa chỉ: http://sabucoffee.com )
Mọi người cho ý kiến khắc phục nhé.
Trân trọng.

**Comment by hoaquynhtim99** [comment]
Hiện mình check không thấy lỗi và trang của bạn cũng không thấy lỗi, có lẽ là vấn đề đã được giải quyết

**Comment by quocngoc** [comment]
Mình cũng bị lỗi tương tự trên, http://atoztourist.com/en/tour/Group-Daily-Tour/paradise-cave.html
Rất mong được đội code khắc phục.
Thanks!

**Comment by ngocphan123** [comment]
Phiên bản module shops hiện tại không có lỗi này bạn check lại hoặc cập nhật lên phiên bản mới nhất nhé.
