### ISSUE TITLE
Nhờ ban quản trị check lại chức năng popup khi đặt hàng

### ISSUE THREAD

**Issue by hunterlovevnvnn** [nukeviet/module-shops#522]
Mình xin gửi lỗi như sau: khi click vào đặt hàng 1 sản phẩm thì vẫn hiện poup đặt hàng bình thường, nhưng khi click vào chọn kích thước thì chức năng thêm vào giỏ hoặc đặt hàng không có tác dụng, demo như hình ảnh mình đính kèm.
![dathangshop1](https://cloud.githubusercontent.com/assets/10189773/15240625/2a9613b6-1915-11e6-9ccf-b9d330478d44.png)
![dathangshop](https://cloud.githubusercontent.com/assets/10189773/15240631/2e81d41a-1915-11e6-8f46-548d0b6c0364.png)

**Comment by anhyeuviolet** [comment]
Nó hiện rõ là hết hàng thế kia thì làm sao đặt được ạ.

**Comment by ngocphan123** [comment]
Tại các thông số bạn chọn tương ứng với số hàng trong kho của sản phẩm đó đã hết hàng nên không kích mua hàng được.

**Comment by hqc210185** [comment]
Lỗi đã được xử lý, có thể đóng issue
