### ISSUE TITLE
Lỗi không tạo được liên kết tĩnh khi sửa sản phẩm

### ISSUE THREAD

**Issue by hunterlovevnvnn** [nukeviet/module-shops#523]
Mình thêm mới sản phẩm thì không sao nhưng khi mình sửa sản phẩm hệ thống không tự động tạo liên kết tĩnh mặc dù đã xóa liên kết tĩnh cũ đi, và mình click vào tạo liên kết tĩnh hệ thống cũng không tạo được, phải nhập thủ công bằng tay, nhờ ban quản trị xem lại.

Xin cảm ơn,

**Comment by volong1012** [comment]
Phiên bản shop bạn đang sử dụng là phiên bản bao nhiêu vậy ?

**Comment by ngocphan123** [comment]
Phiên bản shop mới nhất không còn lỗi này.

**Comment by hqc210185** [comment]
Có lẽ nên đóng issue này.
Khi sửa sản phẩm thì nếu thay đổi "Tên sản phẩm" thì "Liên kết tĩnh" không tự động thay đổi là hợp lý vì như thế tốt cho seo (link đến sản phẩm không bị đổi), nhưng nếu mình muốn đổi liên kết tĩnh thì xóa liên kết tĩnh cũ là được
