### ISSUE TITLE
Lỗi kiểu dữ liệu

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-shops#526]
https://github.com/nukeviet/module-shops/blob/develop/modules/shops/action_mysql.php#L427

Giá ở đây kiểu dữ liệu là int

**Comment by ThinhNguyenVB** [comment]
@mynukeviet đã thay đổi ở đây triển nhé: https://github.com/nukeviet/module-shops/pull/551/commits/30a732c57c1e0fde2ef474069d5b20661548da46
