### ISSUE TITLE
Lỗi không hiển thị "Nội dung chi tiết (*) (Hiển thị đối với mọi đối tượng)"

### ISSUE THREAD

**Issue by songnhien** [nukeviet/module-shops#527]
như tiêu đề em đang chạy bản shop mới nhất và nuke mới  nhất nhưng =sản phẩm không hiển thị nội dung chi tiết mà chỉ hiển thị "Giới thiệu ngắn gọn (*) (Hiển thị đối với mọi đối tượng)"
Bác nào gặp qua cho em xin ý kiến
link test : http://songnhien.com.vn/androitv-box/kiwibox-s1.html

**Comment by anhyeuviolet** [comment]
bạn chưa kích hoạt Tab Chi tiết SP.
