### ISSUE TITLE
Code lấy nhóm sản phẩm mà không thấy xuất giá trị để tích chọn khi thêm sản phẩm

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-shops#528]
<div class="panel panel-default">
        <div class="panel-heading">{LANG.content_group}</div>

```
    <div class="panel-body">
        <div id="list_group">
            <div id="listgroupid">&nbsp;</div>
        </div>
    </div>
</div>
```

cụ thể trong file content.tpl của module shops.
Dũng xem thế nào nhé

nó là "Là sản phẩm thuộc nhóm"

**Comment by anhyeuviolet** [comment]
Nó là dùng JavaScript nạp dữ liệu vào.
Khi chọn Loại sản phẩm thì mới nạp Nhóm sản phẩm tương ứng vào ID đó.
Nên code đó không sai.

**Comment by vietnamxinchao** [comment]
Hiện tại khi đã chọn Loại sản phẩm rồi nó vẫn không hiện giá trị tích chọn trong Nhóm sản phẩm. Hiện tại tôi chỉ thấy hiện giá trị trong nhóm sản phẩm tối đa là 62 mục để tích trọn. trong khi Nhóm sản phẩm của tôi có nhiều hơn số đó. Rất mong đội code xem lại

**Comment by ngocphan123** [comment]
Khi tích chọn loại sản phẩm vẫn hiển thị list sản phẩm thuộc nhóm bình thường không thấy lỗi gì cả.

**Comment by hqc210185** [comment]
Có lẽ nên đóng issue này
