### ISSUE TITLE
Một sản phẩm thuộc nhiều loại sản phẩm

### ISSUE THREAD

**Issue by xotxa** [nukeviet/module-shops#529]
Ad cho mình hỏi làm sao khi up 1 sản phẩm lên có thể cho nó thuộc vào nhiều loại sản phẩm?. Trong cái modules shop ấy

**Comment by vuthao** [comment]
Do thiết kế module 1 sản phảm chỉ có trong 1 loại sản phẩm. Nên việc này không làm được bạn

Bạn có thể dùng sang nhóm sản phẩm
