### ISSUE TITLE
Lỗi khi truy cập từ Tags trong admin

### ISSUE THREAD

**Issue by bungbu84** [nukeviet/module-shops#530]
Quá trình lỗi xuất hiện như sau:

Truy cập admin -> Module Shop -> Quản lý Tags -> Truy cập vào liên kết trong phần **Liên kết tĩnh** nó chuyển sang trang Tags của website và xuất hiện thông báo :

> Thông báo từ Hệ thống
> Nên chú ý Nên chú ý: Undefined index: listcatid in file /modules/shops/theme.php on line 691

**Comment by ThinhNguyenVB** [comment]
@bungbu84  lỗi này không tồn tại bàn nhé, mình đã kiểm tra cả module gốc và module ảo đều không tồn tại
Bạn cho biết thông tin bản này ở bản bao nhiêu nhé

**Comment by mynukeviet** [comment]
Test lại trên develop xem sao nhé bạn
