### ISSUE TITLE
Không chọn được dữ liệu tùy biến

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/module-shops#531]
Phiên bản Nukeviet 4RC (4.0.29)
XAMTP 1.8.3
PHP Version 5.5.9
Hiện tại em tạo dữ liệu tùy biến nhưng không thể chọn được khi thêm sản phẩm.
![image](https://cloud.githubusercontent.com/assets/10495040/19229416/8b9761f8-8ef7-11e6-91f5-45fce3eb8374.png)
![image](https://cloud.githubusercontent.com/assets/10495040/19229426/9ca511c0-8ef7-11e6-831c-bd9c7460ee42.png)
![image](https://cloud.githubusercontent.com/assets/10495040/19229439/b065df32-8ef7-11e6-9137-4e63634a68c5.png)
![image](https://cloud.githubusercontent.com/assets/10495040/19229449/cc14317a-8ef7-11e6-8a8b-5c64327ee9c2.png)

**Comment by ngocphan123** [comment]
Cần cấu hình thêm chỗ loại sản phẩm để chọn những loại sản phẩm nào có dữ liệu tùy biến
