### ISSUE TITLE
Lỗi block gây ra lỗi hệ thống module và viết thừa thành phần ko có trong block

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#542]
Notice: Undefined index: symbol in     modules\shops\site.functions.php on line 186

Notice: Undefined index: homewidth in modules\shops\blocks\global.block_relates_product.php on line 186

**Comment by ThinhNguyenVB** [comment]
@vuthao Lỗi symbol vẫn còn anh nhé
Cụ thệ khi khai báo $money_config để sử dụng nó thì symbol bị mất kiểm tra nó trong các function ở trong file site.functions.php đều bị mất symbol và block sử dụng nó cũng bị mất symbol

**Comment by hoaquynhtim99** [comment]
Đã sửa https://github.com/nukeviet/module-shops/commit/b891b6814fab1b72fcf97b1effa72f7a79a1a37d
