### ISSUE TITLE
Groups view

### ISSUE THREAD

**Issue by hoangloctn** [nukeviet/module-shops#543]
bản trước phần groups_view sẽ tự động chọn Tất cả, bản hiện tại sau khi cài đặt phải chọn khi thêm từng loại sản phẩm.

**Comment by ThinhNguyenVB** [comment]
@hoangloctn bạn chụp lại vị trí trong module shops dùm mình nghe, mình vẫn chưa hình dung nó ở chỗ nào trong module shops

**Comment by hoangloctn** [comment]
lỗi này các bác ấy sửa rồi bạn,

**Comment by ThinhNguyenVB** [comment]
@hoangloctn ok bạn
