### ISSUE TITLE
Đề xuất điều chỉnh nút sửa của đơn hàng ở các trạng thái hàng hóa

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-shops#546]
Hiện tại có danh sách các trạng thái
- Đã thanh toán, đã giao hàng
- Chưa thanh toán, đang giao hàng
- Đã thanh toán, đang giao hàng
- Bị hoàn trả
- Chưa thanh toán
- Chờ duyệt đơn hàng

Thì chỉ có chưa thanh toán và chờ duyệt đơn hàng mới hiển thị nút sửa đơn hàng, còn lại các trạng thái khác đang chuyển hàng không cho phép sửa đơn hàng vì đơn hàng đang trên đường đến nơi nhận không thể bổ sung thêm được đơn hàng và cả trạng thái hoàn trả thì ko cho phép sửa

Hiện tại chỉ có "Đã thanh toán, đang giao hàng" mới bỏ nút sửa đơ hàng

**Comment by vuthao** [comment]
+1
