### ISSUE TITLE
Fixx lỗi Giá vận chuyển đơn hàng

### ISSUE THREAD

**Issue by thuongmaiso** [nukeviet/module-shops#550]
Fixx lỗi Giá vận chuyển đơn hàng
https://nukeviet.vn/vi/forum/Thong-tin-van-chuyen-t41456-p183629/#p183629
mở file modules/shops/site.functions.php tìm đến function nv_shipping_price
tìm dòng 239
if ($weight < $config['weight'])
Sửa thành 
if ($weight <= $config['weight'])

**Comment by vuthao** [comment]
Thank @thuongmaiso
