### ISSUE TITLE
Help mình hiện thị mỗi giá mỗi đơn vị sản phẩm

### ISSUE THREAD

**Issue by anshpy** [nukeviet/module-shops#553]
![image](https://cloud.githubusercontent.com/assets/17925443/25094739/c985eb8c-23c2-11e7-89f6-d03e2edc6013.png)
mình cấu hình giá từ sản phẩm ( hiện jo muốn mỗi 1 giá 1 đơn vị sản phẩm khách nhau đc ko ạ )

**Comment by hoaquynhtim99** [comment]
Phần này hình như bạn tự tùy biến, cái này bạn thảo luận ở diễn đàn nhé
