### ISSUE TITLE
Lỗi khi tiến hành sửa đơn hàng

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-shops#554]
Khi tiến hành đặt hàng xong mà bấm nút sửa đơn hàng sẽ ra trang lỗi

Không thể truy cập trang web này

Trang web tại http://nukeviet44.in/vi/shops/cart/ có thể tạm thời không hoạt động hay được chuyển vĩnh viễn sang địa chỉ web mới.
ERR_CONTENT_DECODING_FAILED

**Comment by anhyeuviolet** [comment]
ERR_CONTENT_DECODING_FAILED
Lỗi kiểu này khéo do mở gzip nhưng lại tắt class xử lý lỗi của NukeViet đi.

**Comment by ThinhNguyenVB** [comment]
@anhyeuviolet khi code bắt buộc tắt class đó đi để show các lỗi hệ thống nếu có mà :D

**Comment by anhyeuviolet** [comment]
Thế bạn có tắt Gzip đi không ?

**Comment by ThinhNguyenVB** [comment]
tắt đi để debug lỗi chứ. Để nó để mà ko debug được sao mà fix hả bạn

**Comment by anhyeuviolet** [comment]
Lỗi trên phát sinh chỉ khi mở gzip mà tắt class xử lý lỗi thôi.

**Comment by ThinhNguyenVB** [comment]
mình tắt hết chứ ko phải mở một trong 2

**Comment by anhyeuviolet** [comment]
hihi !

**Comment by ngocphan123** [comment]
Em check thấy sửa đơn hàng có lỗi nhưng không báo lỗi như anh ghi em đã fix và tạo pull request
