### ISSUE TITLE
Báo lỗi: global.block_bxproduct_center

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-shops#555]
Rất mọng được đội code pix lỗi hoặc hướng lỗi:
Khi kích hoạt block global.block_bxproduct_center thì js cứ loading mãi.
Thông tin thêm:
Cài bản shop: shops 4.0.29
trên phiên bản nukeviet 4.1.02
Thank all!

**Comment by anhyeuviolet** [comment]
https://github.com/nukeviet/module-shops/commit/8ac1b6ed107baaec1b39e23f8484e6cfe3bca832

**Comment by hoanglongvnpt** [comment]
Nghĩa là sao đây à ta?

**Comment by anhyeuviolet** [comment]
Vấn đề của issue này đã được xử lý ở commit theo link bên trên :D

**Comment by hoaquynhtim99** [comment]
Trên shops dev phần lỗi này đã hết @hoanglongvnpt check lại nếu còn lỗi mở lại Issue giúp mình
