### ISSUE TITLE
Lỗi Module Shops ở giao diện tiếng Anh

### ISSUE THREAD

**Issue by thanhtranntkh** [nukeviet/module-shops#557]
[Tue, 13 Jun 2017 19:28:39 +0700] [Ip máy Khách] [Notice(8): Undefined index: displays_new] [FILE: /modules/shops/functions.php] [LINE: 30]
[Tue, 13 Jun 2017 19:28:39 +0700] [Ip máy Khách]] [Notice(8): Undefined index: displays_price_asc] [FILE: /modules/shops/functions.php] [LINE: 31]
[Tue, 13 Jun 2017 19:28:39 +0700] [Ip máy Khách]] [Notice(8): Undefined index: displays_price_desc] [FILE: /modules/shops/functions.php] [LINE: 32]
[Tue, 13 Jun 2017 19:28:41 +0700] [Ip máy Khách]] [Notice(8): Undefined index: displays_new] [FILE: /modules/shops/functions.php] [LINE: 30]
[Tue, 13 Jun 2017 19:28:41 +0700] [Ip máy Khách]] [Notice(8): Undefined index: displays_price_asc] [FILE: /modules/shops/functions.php] [LINE: 31]
[Tue, 13 Jun 2017 19:28:41 +0700] [Ip máy Khách]] [Notice(8): Undefined index: displays_price_desc] [FILE: /modules/shops/functions.php] [LINE: 32]

**Comment by ngocphan123** [comment]
Bạn phải nói rõ lỗi này xảy ra khi nào thì mới có thể biết để sửa được

**Comment by hoaquynhtim99** [comment]
Bản mới nhất đã sửa các cảnh báo này!
