### ISSUE TITLE
Lỗi hiển thị sản phẩm khi sửa lại thời gian đăng sản phẩm

### ISSUE THREAD

**Issue by thuvp1995** [nukeviet/module-shops#558]
Có list 5 sản phẩm sắp xếp theo thời gian đăng. Giả sử muốn hiển thị sản phẩn cũ hơn (sp số 4 chẳng hạn) lên đầu, sau khi cập nhập lại thời gian đăng của sản phẩm đó (sp thứ 4) tại trang quản trị thì sản phẩm đó lên đầu tiên, nhưng ở ngoài site thì nó không lên đầu tiên. (Lưu ý sử dụng shop là module chính của web site).

**Comment by ngocphan123** [comment]
Đây không phải lỗi mà mặc định ngoài site sắp xếp theo id bài viết còn trong quản trị thì sắp xếp theo thời gian thay đổi bài viết
