### ISSUE TITLE
Lỗi tính năng giảm giá với cache

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-shops#565]
Cấu hình phương án hiển thị là **Theo loại sản phẩm**

Tạo giảm giá từ ngày A -> ngày B và áp dụng cho 1 sản phẩm bất kỳ

Khi hết hạn giảm giá, vì do cache nên dù đã hết hạn rồi nhưng giá của sản phẩm ở trang chủ vẫn đề giảm giá (trong khi đã hết hạn), click vào trang xem chi tiết (không cache) thì mới hiển thị đúng

**Comment by hqc210185** [comment]
đang xử lý

**Comment by hqc210185** [comment]
Kiểm tra lỗi đã được xử lý
