### ISSUE TITLE
Lỗi $pro_config['homewidth'] ở block global.block_relates_product.php

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-shops#566]
Hiện tại global.block_relates_product.php sẽ có vấn đề với $pro_config['homewidth'] khi ở trang module shops thì nó có giá trị trong mảng array còn ở trang khác không tồn tại giá trị dẫn đến cảnh bóa lỗi ở dòng này

**Comment by hqc210185** [comment]
đang fix

**Comment by hqc210185** [comment]
Kiểm tra thấy lỗi này đã được fix
