### ISSUE TITLE
Tối ưu hóa giao diện

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-shops#568]
Giao diện các func của shops đang sử dụng file tách biệt. Ví dụ: cùng 1 kiểu hiển thị lưới nhưng ở search.tpl sử dụng code riêng, viewcat code riêng,....

Đề xuất, tạo giao diện viewgrid (hàm theme.php), các func chỉ việc gọi hàm giao diện.

Bây giờ sửa sẽ làm thay đổi rất nhiều, nhưng sẽ rất tiện cho việc phát triển, bảo trì.

**Comment by nguyenphuongdong** [comment]
Chính xác. Hiện tại shops có nhiều bất cập

**Comment by vuthao** [comment]
@mynukeviet đã đăng ký sửa lại phần này.

@mynukeviet do việc sửa chữa này sẽ thay đổi rất nhiều, nên em tách nó pháh triển riêng trên 1 nhánh nhé, sau khi hòan thiện thì gửi pull resquest vào nhánh develop để mình kiểm tra.

**Comment by mynukeviet** [comment]
Ok anh @vuthao

**Comment by mynukeviet** [comment]
Đã xong https://github.com/nukeviet/module-shops/pull/578/commits/90ea08355731c736916f8faa9a076eb0d82b2fc9
