### ISSUE TITLE
Yêu cầu bổ sung nút đặt hàng ở phần so sánh sản phẩm

### ISSUE THREAD

**Issue by Ngoclan** [nukeviet/module-shops#58]
Theo mình khi so sánh các sản phẩm thì sẽ chọn ra 1 sản phẩm vừa ý để mua hàng, vậy nên cuối mỗi sản phẩm khi được đưa ra so sánh nên bổ sung thêm nút "Đặt hàng". Thank!

**Comment by hongoctrien** [comment]
@Ngoclan Chúng tôi sẽ xem xét và bổ sung tính năng này.

**Comment by hongoctrien** [comment]
[Updated](https://github.com/hongoctrien/module-shops/commit/792d9cade7334deabead9ddfe5e3b7331d769a07)
