### ISSUE TITLE
Lỗi hiển thị ngoài site với phần "Nhóm sản phẩm"

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module-shops#580]
Hiện tại phần "Nhóm sản phẩm" có tính năng sắp xếp nhưng ngoài site ở trang chi tiết thì lại hiển thị theo id tăng dần mà không theo sắp xếp. Chỗ này cần chỉnh sửa lại theo đúng sắp xếp

**Comment by mynukeviet** [comment]
Em nhận cái này nhé

**Comment by mynukeviet** [comment]
Nhóm sản phẩm chỉ có sắp xếp thứ tự nhóm chứ không có thứ tự sản phẩm, nên chổ này em thấy đúng

**Comment by trinhthinhhp** [comment]
@mynukeviet có phải là thứ tự sản phẩm đâu, vấn đề là thứ tự thông số của sản phẩm, lên để hiển thị ngoài trang chi tiết sản phẩm là thứ tự của nhóm
![image](https://user-images.githubusercontent.com/6928431/37773098-3bce5510-2e0f-11e8-9643-441461c76c6d.png)
Ví dụ anh muốn thay đổi thương hiệu lên trên thì lại phải làm lại là tạo lại từ đầu sửa tên kích thước thành thương hiệu, như vậy tốn thời gian trong khi weight của nhóm sản phẩm chỉ dùng trong admin cho sắp xếp mà ngoài ko nhảy thứ tự theo

Hình ảnh demo luôn,

**Comment by hqc210185** [comment]
đang kiểm tra lại

**Comment by hqc210185** [comment]
đã xử lý xong
