### ISSUE TITLE
Cần sửa lại block module block_filter_product

### ISSUE THREAD

**Issue by volong1012** [nukeviet/module-shops#588]
Miêu tả tình trạng: dạng lọc sản phẩm.
Hiện nay block này đang sử dụng là lấy từ nhóm sản phẩm để hiển thị ra nhưng nó chỉ đúng với loại shop bán 1 sản phẩm

Trong trường hợp shop bán nhiều loại sản phẩm thì mỗi loại lại cần có cách lọc khác nhau chứ ko thể để vào làm 1 được 

Cần giải quyết vấn đề này càng sớm càng tốt

**Comment by mynukeviet** [comment]
Cái này em nhớ có cái block filter cat gì đó, nó sẽ hiển thị  thuộc tính ứng với từng loại sản phẩm

**Comment by volong1012** [comment]
Cái đó a thiết lập thử rồi nhưng ko thấy gì cả, ko rõ nó lấy từ đâu thiết lập kiểu gì ?

**Comment by mynukeviet** [comment]
Nó chỉ hiển thị khi xem chủ đề thôi anh, còn các khu vực khác không hiển thị

**Comment by volong1012** [comment]
Thì a cần nó hiện ở từng loại sản phẩm khác nhau mà, mỗi loại thì có 1 kiểu lọc riêng biệt ... hix
