### ISSUE TITLE
[góp ý] Nên có lựa chọn ngày đăng - số lượng views sản phẩm 

### ISSUE THREAD

**Issue by thangvn** [nukeviet/module-shops#59]
Mình góp ý nên có phần lựa chọn ngày đăng sản phẩm - số lượng views trong cấu hình module shop.Thực tế thì có shop cần thông tin này nhưng đa số là không cần có thông tin này.

**Comment by hongoctrien** [comment]
Do nhu cầu mỗi người khách nhau, chúng tôi đưa ra trang Danh sách sản phẩm, những thông tin cần thiết nhất.
Nếu bạn không muốn, bạn nên tùy biến lại module. Việc thêm cấu hình này có thể thực hiện được, nhưng nếu quá nhiều cấu hình sẽ làm khó cho người dùng.
