### ISSUE TITLE
Thêm trường "Giá sĩ"

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-shops#591]
Một số shops có nhu cầu báo giá sĩ, giá lẽ của sản phẩm. 

Đề xuất thêm cấu hình này cho shops

**Comment by vuthao** [comment]
Phần này Tùy biến vào dữ liệu thôi @mynukeviet, sau đó sửa lại template để lấy dữ liệu đó ra.

**Comment by mynukeviet** [comment]
À vâng anh, đúng là em quên mất cái tùy biến dữ liệu :)
