### ISSUE TITLE
LỖI KHI ĐẶT HÀNG

### ISSUE THREAD

**Issue by tichbk06** [nukeviet/module-shops#594]
Có ai bị lỗi như mình không ạ.
Thứ nhất: lỗi hiển thị sai số lượng sản phẩm đã đặt hàng sau khi xác nhận gửi đơn hàng đi, dù số tiền không sai.
Ở đây mình đặt thử 4 loại, nhưng sau hiển thị tới 16 sản phẩm (4 lần lặp lại 4 sản phẩm)

Thứ hai là về Vận chuyển: chọn vận chuyển thì luôn hiển thị không tính được phí. Nhưng trong đơn hàng tiền vận chuyển đã được cộng vào.

Xin mọi người hỗ trợ. Xin cảm ơn ạ.

**Comment by hoaquynhtim99** [comment]
Lỗi này sửa trên bản mới nhất rồi. Bạn dùng bản mới nhất nếu có lỗi tạo issue khác giúp mình
