### ISSUE TITLE
Thay đổi kiểu dữ liệu

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#598]
Trong phần shiping trong table shops_orders_shipping cột order_id trường order_id có kiểu dữ liệu là Tinyint ở đây kiểu dữ liệu này rất bé nên khi có lượng đặt trên 255 là hết. Nên để kiểu int thì hay hơn.

**Comment by hoaquynhtim99** [comment]
Bạn check lại thử nhé, shops mới nhất mình thấy nó là `int(11)` rồi

**Comment by motcaiten** [comment]
Hiện tại đã ok
