### ISSUE TITLE
nhờ giúp đỡ module shop đăng giá 0 Đồng

### ISSUE THREAD

**Issue by hoanganhcntt** [nukeviet/module-shops#599]
hiện mình thấy dữ liệu mẫu module shop đăng sản phẩm thì giá 0 đồng đc 
nhưng khi mình đăng sản phầm mình ko muốn nhập giá cho sản phẩm của mình mà để 0 đồng thì hệ thống ko cho mình nhập sản phẩm.
vậy mình muốn nhập giá 0 đồng bạn nào có thể chỉ giáo thêm cho mình đc ko?

**Comment by motcaiten** [comment]
Bạn bỏ phần cho hiển thị giá sản phẩm đi là ok
