### ISSUE TITLE
Lỗi tìm kiếm sản phẩm trong admin 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/module-shops#60]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0)' at line 1' in D:\modules\shops\admin\items.php:143 Stack trace: #0 D:\modules\shops\admin\items.php(143): PDO->query('SELECT COUNT(*)...') #1 D:\admin\index.php(196): require('D:\\Aaweb\\htdocs...') #2 {main} thrown in D:\modules\shops\admin\items.php on line 143

**Comment by hongoctrien** [comment]
Fixed
