### ISSUE TITLE
Lỗi đa ngôn ngữ

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#607]
Khi cài đặt đa ngôn ngữ thì phần sản phẩm (row) bị trùng. 
Cài trên bản nukeviet mới nhất

**Comment by hoaquynhtim99** [comment]
Mình không thấy lỗi này nhỉ

**Comment by motcaiten** [comment]
Khi đăng một sản phẩm bên ngôn ngữ tiếng viết thì sang ngôn ngữ tiếng anh cũng có. Cả 2 đều sử dụng chung module shops luôn.

**Comment by hoaquynhtim99** [comment]
Cái này chủ đích module shops nó vậy rồi bạn, nếu bạn muốn khác nhau thì tạo module ảo để cái tên nó khác đi là được.

**Comment by motcaiten** [comment]
À vậy thì ok rùi :). Cảm ơn
