### ISSUE TITLE
Mong được bổ sung cơ chế chọn màu cho từng sản phẩm

### ISSUE THREAD

**Issue by Ngoclan** [nukeviet/module-shops#61]
Thêm cơ chế quản lý màu sắc của sản phẩm trong admin và cơ chế chon màu sản phẩm ở trang detail. Khi chọn sản phẩm thường khách hàng rê chuột vào bảng màu để chon màu sắc hợp ý (màu phong thủy). Cơ chế này thường sử dụng các shop: Xe máy; oto; điện thoại, áo quần..Rất mong đội code nghiên cứu bổ sung.
Liên kết xem thêm:
http://canthoford.vn/shops/All-new-focus.html
http://www.saigonford.com.vn/mua-ban-xe/gallery_list.php?section_id=24&category_id=50

**Comment by hongoctrien** [comment]
Shops 4 đã bổ sung phần này rồi nhé. Các ban xem ở phần "Nhóm sản phẩm"
