### ISSUE TITLE
Lỗi đặt hàng.

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#615]
Khi đặt nhiều sản phẩm. Nếu trong số đó không có sản phẩm nào thuộc 1 groups thì khi đặt hàng xong . Payment sẽ bị lặp với số lần sản phẩm đó. Ngoài ra trong admin phần đơn hàng hiển thị sai luôn.

![loi shops](https://user-images.githubusercontent.com/8292355/60568900-3cabe980-9d98-11e9-8b2c-9b147c45e308.PNG)

**Comment by aptx1987** [comment]
mong nukeviet fix lỗi này bao gồm double sản phẩm và thiếu symbol tiền tệ

**Comment by hoaquynhtim99** [comment]
Shops mới nhất hiện đã fix cái này rồi bạn nhé 

https://github.com/nukeviet/module-shops/commit/c4ec36d0d0be9b2f3acb278499fee8c9228d176d

**Comment by motcaiten** [comment]
> Shops mới nhất hiện đã fix cái này rồi bạn nhé
> 
> [c4ec36d](https://github.com/nukeviet/module-shops/commit/c4ec36d0d0be9b2f3acb278499fee8c9228d176d)

Ok anh. Xin đóng lại.
