### ISSUE TITLE
Cần chặn trang print, preview không cho google index

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-shops#617]

**Comment by hoaquynhtim99** [comment]
Shops mới nhất không thấy link print ở đâu, không rõ do đâu

**Comment by hoaquynhtim99** [comment]
Thêm `$nv_BotManager->setPrivate();` vào trang print

**Comment by hqc210185** [comment]
Lỗi đã được xử lý
https://github.com/nukeviet/module-shops/blob/9a8fa1f7c2c16b922e3f2ffd087b040c6b1627a6/modules/shops/funcs/print.php#L20

https://github.com/nukeviet/module-shops/blob/9a8fa1f7c2c16b922e3f2ffd087b040c6b1627a6/modules/shops/funcs/print_pro.php#L23
