### ISSUE TITLE
Block sản phẩm: nếu có sản phẩm inhome=0 sẽ làm sai số sắp xếp

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-shops#618]
![image](https://user-images.githubusercontent.com/6407361/61164933-57265580-a544-11e9-8d66-27fa561a8f05.png)

**Comment by hoaquynhtim99** [comment]
Cái này hình như không thấy lỗi, Tr check lại thử xem

**Comment by hqc210185** [comment]
Lỗi ở đây là khi sửa chữa một sản phẩm thì nó sẽ thay đổi thứ tự trong block lại thành 1.
![image](https://user-images.githubusercontent.com/8477589/229397409-78927075-dacc-4561-b682-e93786c42d82.png)
Đang fix lỗi này

**Comment by hqc210185** [comment]
đã fix xong
