### ISSUE TITLE
Sản phẩm trong Cấu hình "Block sản phẩm" chỉ hiển thị 24 sản phẩm (có tổng cộng 43)

### ISSUE THREAD

**Issue by phudq90** [nukeviet/module-shops#620]
Em đang gặp lỗi ở mục cấu hình Block sản phẩm, tổng cộng em đã add 43 sản phẩm vào 1 block tên là "Tất cả sản phẩm hiển thị", nhưng khi vào trong thì chỉ xem được tất cả 24 sản phẩm thôi ạ, không hiển thị đầy đủ 43 sản phẩm.

Đây là ảnh chụp blockcat có tổng cộng 43 sản phẩm:
![image](https://user-images.githubusercontent.com/6510187/61778958-08bd6480-ae2a-11e9-8e14-6b70a9f734ce.png)

Còn đây là khi vào trong chỉ hiện có 24 sản phẩm:
![image](https://user-images.githubusercontent.com/6510187/61778989-1672ea00-ae2a-11e9-9a1f-3d688be58d1a.png)

-- 
Phiên bản shops đang sử dụng: 4.0.29

**Comment by mynukeviet** [comment]
Không biết bạn đang dùng shops bản nào, mình dùng develop thấy không có lỗi này ạ

![image](https://user-images.githubusercontent.com/6407361/62007780-df7b3c00-b17b-11e9-801a-65bc8c0888b3.png)

**Comment by phudq90** [comment]
Mình đang dùng phiên bản shops 4.0.29

**Comment by mynukeviet** [comment]
Thử lấy nội dung file này thay cho file ở host bạn thử https://github.com/nukeviet/module-shops/blob/develop/modules/shops/admin/block.php

**Comment by phudq90** [comment]
> Thử lấy nội dung file này thay cho file ở host bạn thử https://github.com/nukeviet/module-shops/blob/develop/modules/shops/admin/block.php

Mình thay vào, xoá file tạm trong admincp mà vẫn bị.
Mình xin mô tả lại lỗi rõ hơn là bên ngoài trang chủ thực tế là các sản phẩm đã nằm trong block đó rồi, nhưng ở mục cấu hình ở trong block đó ở admincp thì lại không hiển thị đủ (giống như bị cache nặng).

**Comment by hqc210185** [comment]
đang xử lý

**Comment by hqc210185** [comment]
cài đặt trên nhánh develop hiện tại không phát hiện lỗi này
![image](https://user-images.githubusercontent.com/8477589/229396292-61b19ee2-ff4a-460c-8831-508a178686cc.png)

**Comment by hqc210185** [comment]
Vào code kiểm tra không có bất thường: function nv_show_block_list($bid) ở file admin.functions.php
```
$sql = 'SELECT t1.id, t1.listcatid, t1.' . NV_LANG_DATA . '_title, t1.' . NV_LANG_DATA . '_alias, t2.weight, status FROM ' . $db_config['prefix'] . '_' . $module_data . '_rows as t1 INNER JOIN ' . $db_config['prefix'] . '_' . $module_data . '_block AS t2 ON t1.id = t2.id WHERE t2.bid= ' . $bid . ' ORDER BY t2.weight ASC';
```

**Comment by hqc210185** [comment]
issue này nếu không có phản hồi lại thì có thể đóng
