### ISSUE TITLE
Lỗi mã sản phẩm

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#624]
Hiện tại mã sản phẩm không tự điền khi không nhập mã sản phẩm

**Comment by hoaquynhtim99** [comment]
Mã sản phẩm không điền nhưng tự tạo khi lưu bạn! Muốn tạo được mã cần phải lưu vào CSDL để lấy ID sau đó mới tạo mã chuẩn được.

**Comment by motcaiten** [comment]
Hiện tại em đang xài bản Shops dev mới nhất. Và khi thêm sản phẩm mới nếu không điền thì nó sẽ không tự tạo được.
