### ISSUE TITLE
Lỗi tag

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#625]
Lỗi không tạo được tag, chỉ có 1 tag được ghi nhân.

[Wed, 28 Aug 2019 20:14:32 +0700] [demodev.net] [171.249.96.149] [Notice(8): Undefined variable: array_keywords_old] [FILE: /modules/shops/admin/content.php] [LINE: 860]
[Wed, 28 Aug 2019 20:14:32 +0700] [demodev.net] [171.249.96.149] [Notice(8): Undefined variable: array_keywords_old] [FILE: /modules/shops/admin/content.php] [LINE: 864]
[Wed, 28 Aug 2019 20:14:32 +0700] [demodev.net] [171.249.96.149] [Warning(2): Invalid argument supplied for foreach()] [FILE: /modules/shops/admin/content.php] [LINE: 864]

**Comment by hoaquynhtim99** [comment]
Đã sửa ở https://github.com/nukeviet/module-shops/commit/b3310fdb91816e9c815086c82ec8adbad9ffef07

**Comment by motcaiten** [comment]
> Đã sửa ở [b3310fd](https://github.com/nukeviet/module-shops/commit/b3310fdb91816e9c815086c82ec8adbad9ffef07)

Cảm ơn !
