### ISSUE TITLE
Lỗi block : global block bxproduct center

### ISSUE THREAD

**Issue by tuyenclub** [nukeviet/module-shops#626]
Hiện tại mình đang tập tành với nukeviet ở module shop! 
Mình thấy block: global block bxproduct center bị lỗi không thể click chuột vào xem sản phẩm khi duyệt web với Chrome. riêng với MS Edge và Firefox thì vẫn sử dụng bình thường.
demo: http://tuoi.dotuyen.name.vn/

**Comment by hoaquynhtim99** [comment]
Đã sửa ở https://github.com/nukeviet/module-shops/commit/d8f04b310f0369e2afda30d013fed72af03bfb95
