### ISSUE TITLE
Lỗi mã giảm giá

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#627]
Không thêm được mã giảm giá trong phần quản lý mã giảm giá

**Comment by hoaquynhtim99** [comment]
Mình thấy shops trước giờ không có kiểu nhập mã giảm giá mà chỉ có giảm giá trực tiếp vào

**Comment by motcaiten** [comment]
Có mà anh. Khi khách mua hàng có phần sử dụng mã giảm giá. Tuy nhiên ở phần thêm mã giảm giá bị lỗi không thêm được.
![Capture](https://user-images.githubusercontent.com/8292355/64944016-71a7e280-d897-11e9-80a3-b03d4f565656.JPG)

**Comment by hoaquynhtim99** [comment]
À, cái này mới cài vô nó không có sẵn. Đã sửa ở https://github.com/nukeviet/module-shops/commit/274a099ec05029293554aacfbe59a85e7bd9f5fd

**Comment by motcaiten** [comment]
> À, cái này mới cài vô nó không có sẵn. Đã sửa ở [274a099](https://github.com/nukeviet/module-shops/commit/274a099ec05029293554aacfbe59a85e7bd9f5fd)

Ok rồi đó anh. Xin phép đóng

**Comment by motcaiten** [comment]
Còn lỗi anh.

Sau khi tạo 1 mã giảm giá. Sau đó không xài nữa xóa đi thì sẽ không load cart được.

Báo lỗi .

Error on file /vendor/vinades/nukeviet/Core/Database.php line 491:
Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /home/democcg/domains/demo214.net/public_html/vendor/vinades/nukeviet/Core/Database.php:491
Stack trace:
#0 /home/democcg/domains/demo214.net/public_html/vendor/vinades/nukeviet/Core/Database.php(491): PDO->query('SELECT pid FROM...')
#1 /home/democcg/domains/demo214.net/public_html/modules/shops/funcs/loadcart.php(36): NukeViet\Core\Database->query('SELECT pid FROM...')
#2 /home/democcg/domains/demo214.net/public_html/index.php(315): require('/home/democcg/d...')
#3 {main}
thrown

**Comment by hoaquynhtim99** [comment]
Đã sửa https://github.com/nukeviet/module-shops/commit/60e69e169ddd23a28cb565d2b082188e35ccfa34
