### ISSUE TITLE
Lỗi trang trắng khi hiển thị theo loại sản phẩm, các block Global của shop hiển thị theo 1 cột dọc

### ISSUE THREAD

**Issue by tuyenclub** [nukeviet/module-shops#628]
Chào anh em! Mình vừa download bản "đi ve lốp" về test thì phát hiện các vấn đề sau: 
1. Lỗi trang trắng khi cấu hình hiển thị sản phẩm theo "Loại sản phẩm".
https://www.upsieutoc.com/image/hien-thi-theo-loai-sp.LiFrqD

2. Các block global của Shop đều bị lỗi hiển thị theo 1 cột dọc và không chạy được dạng slide sản phẩm. Tình trạng này xảy ra ở tất cả các block_global
https://www.upsieutoc.com/image/hien-thi-theo-1-cot-doc.LiFXQr

**Comment by hoaquynhtim99** [comment]
Vấn đề số 1 đã sửa ở https://github.com/nukeviet/module-shops/commit/d67ef314fa4682e14b156005a75a91727f28997b

Vấn đề số 2 bạn cho đúng tên block để kiểm tra nhé

**Comment by tuyenclub** [comment]
> Vấn đề số 1 đã sửa ở [d67ef31](https://github.com/nukeviet/module-shops/commit/d67ef314fa4682e14b156005a75a91727f28997b)
> 
> Vấn đề số 2 bạn cho đúng tên block để kiểm tra nhé

Tất cả các block_global đều vậy ạ. demo: https://tuoi.dotuyen.name.vn/shops/ 
Hiện mình sài bản develop mới nhất !

**Comment by hoaquynhtim99** [comment]
Chỉ có các block có chữ center mới hiển thị hàng ngang, các block khác hiển thị dọc là bình thường.
Mình kiểm tra chỉ có 1 block lỗi và đã viết lại tại https://github.com/nukeviet/module-shops/commit/4a9597454b10fa9438ff3f73c61f976b845f9557
