### ISSUE TITLE
Lỗi lấy giá giảm giá trong giỏ hàng

### ISSUE THREAD

**Issue by ccu1tn** [nukeviet/module-shops#632]
Dear các bạn;

Website của mình không lấy giá đã giảm trong khi đặt hàng. 
Sản phẩm này được giảm giá là:
![image](https://user-images.githubusercontent.com/43333942/71554269-1f5e8c00-2a58-11ea-9b83-16a178e1d7b7.png)
Khi đặt hàng không lấy giảm giá 
![image](https://user-images.githubusercontent.com/43333942/71554274-37cea680-2a58-11ea-988d-e318c2311a7a.png)

Bạn nào đã fix lỗi này help mình với. 
Trân trọng!

**Comment by hqc210185** [comment]
đang xử lý

**Comment by hqc210185** [comment]
Đã kiểm tra tất cả các phương án giảm giá gồm: 
- Theo cấu hình giảm giá
- Theo từng sản phẩm
- Không giảm giá (Giá sản phẩm, giá bán ra)
=> tất cả đều hoạt động tốt.
issue này có thể close

**Comment by hoaquynhtim99** [comment]
@ccu1tn bạn dùng bản mới nhất nhé. Nếu bản mới còn lỗi thì tạo issue khác giúp mình.
