### ISSUE TITLE
Kiểm tra lại tất cả các link trong quản trị

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#633]
- Link trực tiếp
- Link post qua ajax

Hiện tại rất nhiều chỗ link không chứa biến lang language=vi|en... dẫn tới đang thao tác ngôn ngữ này lại có thể chuyển thành ngôn ngữ khác làm sai lệch dữ liệu.

**Comment by longakka** [comment]
Đang làm
