### ISSUE TITLE
Lỗi thêm tài liệu

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#635]
Tại trang thêm, sửa sản phẩm:
- Ấn nút **Thêm tài liệu** sau đó tắt popup đi
- Ấn tiếp nút **Thêm tài liệu** mở popup lên lại thì nút **Chọn tập tin hoặc nhập đường dẫn bên ngoài** không ấn vào được

- Khi thêm tài liệu xong giá trị đã chọn tại ô tài liệu trước đó bị mất!

**Comment by hoaquynhtim99** [comment]
Cần thêm chức năng thêm tài liệu thì tự điền vào ô tài liệu tại trang thêm/sửa sản phẩm

**Comment by hqc210185** [comment]
Đang fix

**Comment by hqc210185** [comment]
Thấy chức năng thêm tài liệu đã ổn. Có thể đóng issue
