### ISSUE TITLE
Lỗi tạo loại sản phẩm mới trùng alias

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#636]
Khi tạo sản phẩm mới alias bị trùng hệ thống không báo trùng mà lại hiển thị lỗi không cập nhật được nội dung

**Comment by hqc210185** [comment]
Đang kiểm tra

**Comment by hqc210185** [comment]
Kiểm tra thấy alias tự động điền thêm số ở phía sau. Thấy xử lý như vậy là đã hợp lý.
issue có thể được đóng

**Comment by hoaquynhtim99** [comment]
Vẫn chưa được

**Comment by hqc210185** [comment]
Đã hoàn thành
