### ISSUE TITLE
Lỗi hiển thị khi loại sản phẩm chọn Hiển thị theo loại sản phẩm

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#640]
Lỗi cảnh báo: call_user_func() expects parameter 1 to be a valid callback, function 'view_home_cat' not found or invalid function name in file /modules/shops/funcs/viewcat.php on line 243

**Comment by hoaquynhtim99** [comment]
Khi `view_home_cat` thì không hiển thị sắp xếp, không đổi kiểu hiển thị

**Comment by hqc210185** [comment]
Không phát hiện lỗi. Có lẽ issue có thể đóng

**Comment by hqc210185** [comment]
Lỗi do phía người sử dụng ngoài site cho phép thay đổi kiểu hiện thị và được lưu vào session. Khi vào viewcat thì nó lại ưu tiên dữ liệu trong session. Đã fix bằng cách nếu kiểu hiễn thị là 'view_home_cat' thì nó không lấy kiểu hiện thị trong session nữa.
Đã fix xong

**Comment by hqc210185** [comment]
đã xong
