### ISSUE TITLE
Lỗi khi thêm sản phẩm có thiết lập nhóm

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#641]
[Notice(8): Undefined variable: module_upload] [FILE: /modules/shops/admin/getgroup.php] [LINE: 29] [TRACE:]
#1  LINE: 175   FILE: /admin/index.php
#2  LINE: 94    FILE: /modules/shops/admin/getgroup.php

**Comment by hqc210185** [comment]
không thấy báo lỗi ở file log. 
Kiểm tra một số chức năng thấy đang tốt
Có lẽ đã đóng được issue này
