### ISSUE TITLE
Lỗi không cập nhật được nội dung khi copy sản phẩm

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#642]
[Notice(8): Undefined variable: rowcontent_coppy] [FILE: /modules/shops/admin/content.php] [LINE: 560] [TRACE:]
#1  LINE: 175   FILE: /admin/index.php

**Comment by hqc210185** [comment]
Đang kiểm tra

**Comment by hqc210185** [comment]
Chức năng copy sản phẩm ổn định.
Có thể đóng issue
