### ISSUE TITLE
Lỗi đường dẫn đến thư mục files_tpl

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#643]
Một số chỗ dùng `$module_name . '/files_tpl'` là sai cần sửa thành `$module_upload . '/files_tpl' `

**Comment by kyphan01** [comment]
đang sửa

**Comment by hqc210185** [comment]
không phát hiện $module_name . '/files_tpl' nữa. 
Issue có thể đóng
