### ISSUE TITLE
Lỗi đặt hàng đối với sản phẩm có 1 nhóm mỗi loại

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#645]
Tại trang xem chi tiết sản phẩm:

- Nếu sản phẩm không có nhóm sản phẩm => Thêm vào giỏ, mua ngay OK
- Nếu sản phẩm mỗi loại có hơn 1 nhóm => Hệ thống sẽ hỏi chọn nhóm trước, chọn nhóm sẽ báo hết hàng không mua được
- Nếu sản phẩm mỗi loại có 1 nhóm => Thêm vào giỏ báo thành công nhưng vào giỏ hàng lại không có gì

**Comment by hqc210185** [comment]
Đang xử lý

**Comment by hqc210185** [comment]
kiểm tra và thấy vấn đề đã được xử lý.
