### ISSUE TITLE
Lỗi khi Cấu hình hiển thị captcha là reCAPTCHA

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#647]
Khi Cấu hình hiển thị captcha là reCAPTCHA thì bị lỗi

**Comment by hqc210185** [comment]
Đang kiềm tra

**Comment by hqc210185** [comment]
Kiểm tra thấy  chức năng không có vấn đề gì
![image](https://user-images.githubusercontent.com/8477589/229719336-42a72cf8-5fc2-45c4-8854-7cfc1572edb1.png)
Có thể đóng issue này
