### ISSUE TITLE
Lỗi xác định link chi tiết sản phẩm tại trang main, viewcat

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#648]
Ví dụ sản phẩm thuộc loại: Quần đùi  
Loại Quần đùi nằm trong Quần

Khi xem Loại Quần thì link sản phẩm nằm trong Quần đùi là: /vi/shops/Quan/Quan-Thun.html
Trong khi link đúng phải lấy theo catid chính của nó là: /vi/shops/Quan-dui/Quan-Thun.html

**Comment by kyphan01** [comment]
Đang thực hiện

**Comment by kyphan01** [comment]
Hiện tại đã hết lỗi
