### ISSUE TITLE
Lỗi sắp xếp sản phẩm theo dạng lưới và dạng danh sách

### ISSUE THREAD

**Issue by thangvn** [nukeviet/module-shops#65]
Trong trang chuyên mục từng ngành(loại) sản phẩm.Nếu sản phẩm sắp theo danh sách là DẠNG LƯỚI thì click vào xem chi tiết được

Còn nếu trình bày sản phẩm theo dạng lưới theo không click được ( xem bên dưới trình duyệt khi click thì nó báo là lỗi javascript : void();

test tại Localhost
server : xamp v3.2.1
HĐH : win 7

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/module-shops/commit/2fef2b01a21b029bede174412ecc01c46e07acbe)
