### ISSUE TITLE
Lỗi Block sản phẩm

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#650]
Nếu có nhiều Block sản phẩm thì khi xem chi tiết Block sản phẩm ở ngoài site sẽ tự động load về link Block sản phẩm có vị trí cuối cùng .

**Comment by hoaquynhtim99** [comment]
@motcaiten mình thấy có tạo pull request nhưng sao close cái này nhỉ https://github.com/nukeviet/module-shops/pull/651
Vậy cái pull request kia có đúng không, cần close không?

**Comment by motcaiten** [comment]
> @motcaiten mình thấy có tạo pull request nhưng sao close cái này nhỉ #651
> Vậy cái pull request kia có đúng không, cần close không?

Pull request đúng đó anh. Do em gửi Pull request rồi nên em close này này .

**Comment by hoaquynhtim99** [comment]
Merged https://github.com/nukeviet/module-shops/pull/651
