### ISSUE TITLE
Lỗi đa ngôn ngữ

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#652]
Khi kích hoạt đã ngôn ngữ (Tiếng anh) khi vào kích hoạt module bên tiếng anh thì dữ liệu giữa 2 ngôn ngữ bị trùng.

**Comment by hoaquynhtim99** [comment]
Module này thế nhé bạn, dữ liệu giữa 2 ngôn ngữ là 1, có thể dịch tên khác ra chứ không phải độc lập.

Cần độc lập thì tạo module ảo khác tên ở các ngôn ngữ khác nhau.

**Comment by motcaiten** [comment]
@hoaquynhtim99 Em thấy trong database của modules thì có sinh ra các trường về của ngôn ngữ đó. Nếu xài chung rồi thì sinh ra mấy trường này với mục đích gì nhỉ ?

**Comment by hoaquynhtim99** [comment]
@motcaiten để dịch 1 sản phẩm ra nhiều ngôn ngữ khác nhau đó.
Ví dụ bạn có 1 sản phẩm thì số lượng trong kho, giá cả, .... trùng nhau nhưng tên, mô tả mỗi ngôn ngữ mỗi khác nhau

**Comment by motcaiten** [comment]
@hoaquynhtim99  Vấn đề là ở đây anh. Làm kiểu này ok rồi. Nhưng hiện tại khi vào tiếng anh nó không load ra tiếng anh mà load phần tiếng việt .

**Comment by hoaquynhtim99** [comment]
@motcaiten khi sản phẩm đó có trên tiếng Việt, bạn thiết lập module shops mới bên tiếng Anh thì nó copy hết tiếng Việt sang, bạn vào sửa từng sản phẩm để dịch sang tiếng Anh là ok
