### ISSUE TITLE
Lỗi nhóm tin khi thêm, sửa sản phẩm

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#654]
[Tue, 13 Oct 2020 15:57:51 +0700] [demo.dev] [14.241.236.117] [Notice(8): Undefined offset: 44] [FILE: /modules/shops/admin/getgroup.php] [LINE: 70] [TRACE:]
#1  LINE: 175   FILE: /admin/index.php

**Comment by hqc210185** [comment]
Đã xử lý lỗi không hiện icon ở nhóm tin. 
Còn vấn đề ở trên không phát hiện thấy.
Có lẽ issue có thể close được
