### ISSUE TITLE
Lỗi cấu hình module

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/module-shops#659]
Ở dòng  modules\shops\admin\setting.php(35):
Không tồn tại Column not found: 1054 Unknown column 'title' in 'field list' in

**Comment by datdevs** [comment]
Lỗi này tồn tại trên nukeviet 4.5.00 sao không thấy devs nào phản hồi nhỉ ?

**Comment by tmsholdings** [comment]
bạn có thể fix lại câu truy vấn đó
$result = $db->query('SELECT g.group_id, d.title, g.group_type, g.exp_time FROM ' . NV_GROUPS_GLOBALTABLE . ' AS g LEFT JOIN ' . NV_GROUPSDETAIL_GLOBALTABLE . ' d ON ( g.group_id = d.group_id  ) WHERE g.act=1 AND (g.idsite = ' . $global_config['idsite'] . ' OR (g.idsite =0 )) ORDER BY g.idsite, g.weight');

**Comment by hoaquynhtim99** [comment]
@datdevs nukeviet 4.5.00 thì liên quan gì đến module shops bạn?

**Comment by datdevs** [comment]
> @datdevs nukeviet 4.5.00 thì liên quan gì đến module shops bạn?

`define('NV_GROUPS_GLOBALTABLE', $db_config['prefix'] . '_users_groups');`
`define('NV_GROUPSDETAIL_GLOBALTABLE', $db_config['prefix'] . '_users_groups_detail');`

4.5.00 sửa lại cấu trúc table cho users_groups, thêm table users_groups_detail, table users_groups không tồn tại title column chuyển column này sang table users_groups_detail nên module shops truy vấn không tìm thấy cột này, em nói có gì sai không, bác check lại đi.

**Comment by hoaquynhtim99** [comment]
Mình tưởng bạn báo lỗi NukeViet 4.5 mà chạy sang đây 😂, ơ cơ mà module này chưa có nâng cấp lên 4.5 mà đâu đã ai nâng cấp đâu nó lỗi là tất nhiên bạn.

**Comment by motcaiten** [comment]
@datdevs @tmsholdings https://github.com/nukeviet/module-shops/pull/663

**Comment by hqc210185** [comment]
có lẽ issue này đã được fix, cần close issue này .
