### ISSUE TITLE
Column match_type không hoạt động trong bảng Dữ liệu tùy biến

### ISSUE THREAD

**Issue by tinhcavn** [nukeviet/module-shops#665]
Column match_type không hoạt động trong bảng Dữ liệu tùy biến: **_admin_functions.php_** dòng 1225 bị nhầm **_column_**

![image](https://user-images.githubusercontent.com/72851340/131212969-001ee155-9a3b-4c18-be54-a43869a2d787.png)

Ngoài ra, hàm kiểm tra filed required cũng không hoạt động

Thứ tự filed sắp xếp ngẫu hứng, không theo trật tự, nên thêm ORDER BY vào câu lệnh sql

![image](https://user-images.githubusercontent.com/72851340/131213025-0d592ef7-6c61-4423-9fc3-1beedb73c5ae.png)

**Comment by hqc210185** [comment]
đang kiểm tra lại

**Comment by hqc210185** [comment]
đã kiểm tra và xử lý các vấn đề liên quan. Chờ kiểm tra
