### ISSUE TITLE
Lỗi khi coppy sản phẩm

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/module-shops#671]
Trên bản shop mới nhất cài trên nukeviet 4.6
Khi copy sản phẩm, sẽ inser đúp lên 2 lần
![screenshot_1646209482](https://user-images.githubusercontent.com/82592373/156323394-6f8b08fd-4196-47d4-987c-b32284763c3c.png)

**Comment by aptx1987** [comment]
thêm 1 sản phẩm cũng bị double luôn, dùng trên 4.5.02

**Comment by hqc210185** [comment]
tôi vừa cài lên 4.5.03 thấy không còn vấn đề đó nữa
