### ISSUE TITLE
Nhận báo đơn hàng qua email

### ISSUE THREAD

**Issue by ccu1tn** [nukeviet/module-shops#674]
Chào anh em. 

Hiện tại mình muốn cấu hình làm sao để mỗi khi có người đặt hàng thì có 1 email thông báo gửi đến email được không? 
Vì cứ phải vào xem đơn hàng mãi thấy hơi bất tiện. 

Chân trọng cảm ơn/

**Comment by motcaiten** [comment]
Hiện tại có rồi đó bạn. Bạn cần cấu hình SMTP để hệ thống gửi mail hoạt động là ok
