### ISSUE TITLE
Lỗi giá trong cart

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module-shops#676]
Nếu dùng câu hình "Sử dụng giá niêm yết - giá bán" thì khi cộng giá lại sẽ bị sai. 

Trong hình thì sản phẩm phía dưới sử dụng giảm giá theo cấu hình trên

![Screenshot 2022-06-13 113016](https://user-images.githubusercontent.com/8292355/173280011-05ea272a-4e7c-4d18-a8d3-134f346136d2.png)

**Comment by motcaiten** [comment]
fix [d092531](https://github.com/nukeviet/module-shops/pull/677/commits/d092531d25ff04d4e2f7eeeada66816e6dd88d66)

**Comment by hqc210185** [comment]
đang kiểm tra lại
