### ISSUE TITLE
LỖI SHOP NHẬP SẢN PHẨM

### ISSUE THREAD

**Issue by anvhceo** [nukeviet/module-shops#680]
{"error":1,"input":"catid","msg":"L\u1ed7i: S\u1ea3n ph\u1ea9m ch\u01b0a c\u00f3 lo\u1ea1i s\u1ea3n ph\u1ea9m"}

/admin/index.php?language=vi&nv=shops&op=content 

tình hình là lỗi shop ở khung thêm sản phẩm chỉ nhập tiêu đề xong, bấm tạo thì phát sinh ra lỗi này, mong ad chỉ giúp

**Comment by hqc210185** [comment]
![image](https://user-images.githubusercontent.com/8477589/224877906-fedc38c6-17b6-46fc-8343-af174cec0045.png)
Kiểm tra và đã thấy được fix rồi
