### ISSUE TITLE
Check lại xem các vấn đề sau

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#688]
- Link tìm kiếm sản phẩm đạng dạng alias-id/ chứ không phải dạng alias.html nên không xem được
- Chi tiết sản phẩm không có chỗ nào hiển thị khuyến mãi (quà tặng)

**Comment by hqc210185** [comment]
- Link tìm kiếm sản phẩm đạng dạng alias-id/ chứ không phải dạng alias.html nên không xem được: chưa hiểu yêu cầu
- Chi tiết sản phẩm không có chỗ nào hiển thị khuyến mãi (quà tặng): kiểm tra thấy quà tặng đã hiện ở trên là được rồi, không cần hiện ở chỗ "chi tiết sản phẩm" nữa

**Comment by hqc210185** [comment]
Đã xử lý xong
