### ISSUE TITLE
[Thắc mắc]Đây có phải lỗi không

### ISSUE THREAD

**Issue by thangvn** [nukeviet/module-shops#69]
Mình tạo 1 sitemap để upload lên GOOGLE,nhưng sau khi upload mình kiểm tra file xem có được không thì nó hiện ra như thế này

http://tenmienwebsitecuaminh.com/sitemap-vi.news.xml	
http://tenmienwebsitecuaminh.com/sitemap-vi.jquery.xml	
http://tenmienwebsitecuaminh.com/sitemap-vi.thong-tin.xml

Mình không thấy những file này trong thư mục gốc. Nó ở đâu ra ? File mình upload lên chỉ có tên là sitemap.xml , nó là file sitemapcủa module SHOP

**Comment by hongoctrien** [comment]
Những file này được hệ thống tự động tạo bạn ạ.
