### ISSUE TITLE
Lỗi hiển thị giá

### ISSUE THREAD

**Issue by hades-1997** [nukeviet/module-shops#690]
Đã tắt chức năng hiển thị giá ra ngoài nhưng lúc đăng sản phẩm vẫn bị ràng buộc nhập giá > 0

**Comment by hqc210185** [comment]
đang fix

**Comment by hqc210185** [comment]
tôi kiểm tra thấy bỏ tùy chọn "Cho phép hiển thị giá sản phẩm này" ở "Tính năng mở rộng" khi tạo sản phẩm thì có thể không cần nhập giá.

**Comment by hades-1997** [comment]
> tôi kiểm tra thấy bỏ tùy chọn "Cho phép hiển thị giá sản phẩm này" ở "Tính năng mở rộng" khi tạo sản phẩm thì có thể không cần nhập giá.

có cách nào để tùy chọn tính năng này luôn luôn bỏ tích khi thêm mới không ạ

**Comment by hqc210185** [comment]
Em vào file modules/shops/admin/content.php
Đến khoảng dòng 91 
```
$rowcontent = [
    'id' => 0,
    'listcatid' => $catid,
    'user_id' => $admin_info['admin_id'],
    'addtime' => NV_CURRENTTIME,
...
...
...
'allowed_save' => 1,
    'hitstotal' => 0,
    'hitscm' => 0,
    'hitslm' => 0,
    'showprice' => 1,
    'com_id' => 0,
    'title' => '',
    'alias' => '',
```
Em để ý thấy cấu hình " 'showprice' => 1," thì em chuyển nó thành  'showprice' => 0,
