### ISSUE TITLE
Lỗi tags

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#694]
Một số người báo bấm vào tags toàn về trang chủ

**Comment by kyphan01** [comment]
đang thực hiện

**Comment by hqc210185** [comment]
cái này anh xử lý xong rồi

**Comment by hqc210185** [comment]
https://github.com/nukeviet/module-shops/issues/644
Khi xử lý issue trên tiện thể anh đã xử lý vấn đề này cách đây 2 ngày

**Comment by hoaquynhtim99** [comment]
@kyphan01 em làm cái khác đi cái này xong rồi
