### ISSUE TITLE
Lỗi copy sản phẩm

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#696]
Khi copy sản phẩm, hệ thống tạo alias mới không trùng, tuy nhiên cố tình sửa alias trùng với một sản phẩm trước đó ấn lưu sẽ báo lỗi không cập nhật được nội dung

**Comment by hqc210185** [comment]
đang xử lý

**Comment by hqc210185** [comment]
đã xử lý xong
