### ISSUE TITLE
Tích hợp các đơn vị giao hàng giao hàng 

### ISSUE THREAD

**Issue by thanhtrung87** [nukeviet/module-shops#724]
Hiện tại module chưa tích hợp với đơn vị giao hàng cũng như phí giao hàng

**Comment by hoaquynhtim99** [comment]
Phần này trùng với issue này rồi bạn https://github.com/nukeviet/module-shops/issues/606 
Bạn xem thông tin ở đó nhé. Hiện tại không có nguồn lực để làm cái đó
