### ISSUE TITLE
Xem ảnh cỡ lớn bị lỗi trên mobile

### ISSUE THREAD

**Issue by RightPro** [nukeviet/module-shops#74]
Trên điện thoại trong phần trang chi tiết sản phẩm khi click xem ảnh cỡ lớn ảnh phóng to sẽ  bị đẩy xuống góc trái giao diện (mất nguyên 1 góc) và khi touch thì chỉ touch được với nền dưới của ảnh chứ không touch được trong phần ảnh.

**Comment by hongoctrien** [comment]
Mặc định khi kích thước màn hình nhỏ hơn ảnh, ảnh sẽ không tự co dãn theo màn hình mà vẫn dữ nguyên kích thước, muốn xem phần khác phải kéo chuột qua vị trí khác.

Bạn muốn ảnh tự co dãn theo độ phan giải, mở **modules/shops/theme.php**.
Tìm và xóa
```
{ handleOversize: \"drag\" }
```
