### ISSUE TITLE
Lỗi cài không cài đặt được module-shops

### ISSUE THREAD

**Issue by biorioza** [nukeviet/module-shops#75]
Thực hiện cài đặt thành công nhưng không có thông tin về module-shops trong mục thiết lập module mới để thiết lập thông tin cho module, kiểm tra trong bảng csdl nv4_setup_modules và nv4_vi_modules đều không thấy dữ liệu về module-shops

Môi trường thử Nghiệm
- Phiên bản NukeViet: 4.0.09
-Module-shop 4.0.0.9
- Hệ điều hành: windows 8.1 Enterprise N 64bit
- Trình duyệt web:Google Chrome  Phiên bản 37.0.2062.120 m
- Máy chủ web: xampp-win32-1.8.3-5-VC11

+ Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.5.15 mysqlnd 5.0.11-dev - 20120503

**Comment by hongoctrien** [comment]
Bạn tải lại code rồi cài lại nhé.
