### ISSUE TITLE
lỗi duplicate content 

### ISSUE THREAD

**Issue by thangvn** [nukeviet/module-shops#77]
Khi bật loại bỏ kí tự module shop trên URL thì link đã loại bỏ,nhưng bị tình trạng này

![noname](https://cloud.githubusercontent.com/assets/6823461/4386706/4b26ada2-43d3-11e4-86fe-955817a48133.jpg)

nếu click chữ Trang Nhất thì hiện ra danh sách các sản phẩm trong module SHOP , nếu click chữ SHOP thì cũng vẫn hiện ra như vậy.

Điều đó sẽ dẫn đến tình trạng có 2 đường link cùng 1 nội dung , ví dụ : http://tenwebsite và http://tenwebsite/shops /* với module SHOP là module mặc định trang chủ */

Vi phạm lỗi duplicate content.

Kiểm tra trên : LOCALHOST - WIN 7  - XAMPP SERVER

Phiên bản kiểm tra : 

Phiên bản đang sử dụng :	4.0.09 - được download ngày 23/9/2014

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/11c3c4d489b703eb863115459c285c53b1506db5
