### ISSUE TITLE
Lỗi hình ảnh: Kích thước của hình tại trang chủ không đúng với cài đặt trong Admin

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/module-shops#80]
Ảnh ở URL: /files/shops/nam-thang/ten-file.xxx không đúng với kích thước đã cấu hình trong phần cấu hình của modules.
Trong  /admin/index.php?language=vi&nv=shops&op=setting --> Kích thước của hình tại trang chủ --> cấu hình là 200 x 200 nhưng khi up ảnh lên  ở URL: /files/shops/nam-thang/ten-file.xxx thì tối đa chỉ là 100px mà thôi.
Như thế ảnh hiển thị ở trang chủ sẽ bị nhỏ quá. Niếu thiết kế giao diện cho ảnh lớn hơn sẽ bị mờ, xấu.

**Comment by hongoctrien** [comment]
Bạn thiết đặt kích thước ảnh thực tại **ACP/Quản lý file/Cấu hình Thumbnail**
Còn kích thước ở cấu hình module sẽ là kích thước thay đổi.
