### ISSUE TITLE
[góp ý] Nên có tính năng members cho shops

### ISSUE THREAD

**Issue by thangvn** [nukeviet/module-shops#81]
Mình góp ý module shop nên có thêm tinh năng cho nhiều thành viên quản lý giống module NEWS.Các thành viên có thể đăng tin sau khi đăng kí , quyền hạn do admin quản lý.

**Comment by hongoctrien** [comment]
@thangvn 
News và Shop hai mô hình nào khác nhau.

Shop dùng cho người bán hàng, chúng tôi sẽ phát triển các tính năng để quản lý bán hàng nhiều hơn là cộng tác, nên đề xuất của bạn trong thời gian tới chúng tôi chưa thực hiện ngay được, do phải ưu tiên viết những tính năng khác trước để sớm đưa nukeviet 4 ra mắt.
