### ISSUE TITLE
Không thể upload ảnh định dạng JPEG và Lỗi z-index khi xem ảnh lớn - SP chi tiết

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module-shops#82]
Hôm nay mình thử nghịch cái shop này thì phát sinh 2 thứ sau
01/ Hình ảnh đuôi mở rộng JPEG bị báo là không thể nhận diện và không upload được

![shop-01](https://cloud.githubusercontent.com/assets/6290970/4573086/65a71448-4f8e-11e4-9d2d-81a4b29b01e2.png)

Mình đã thử nhiều định dạng khác thì upload bình thường.

02/ Là khi xem hình ảnh lớn của sản phẩm tại trang chi tiết sản phẩm, thì phần menu đè lên hình của sản phẩm.
Hình như menu này cũng đè lên phần quản lý block khi bật kéo thả block trên trang chủ.
![shop-02](https://cloud.githubusercontent.com/assets/6290970/4573117/c37549e6-4f8e-11e4-8b2b-e86bef3850c4.PNG)

---------------------
Môi trường thử nghiệm : 
Windows 7 x32  - Ultimate
Máy chủ : 
Xampp 1.7.1
Php 5.2.9

**Comment by hongoctrien** [comment]
02, Đã [fix](https://github.com/hongoctrien/nukeviet/commit/66195aebdba7b7f43781ce802b812c797776acd8) chung cho NukeViet 4
