### ISSUE TITLE
Lỗi block search modules shops

### ISSUE THREAD

**Issue by lethanhdanh** [nukeviet/module-shops#83]
Mình có tạo block search của modules shop, khi search giá từ .... đến giá..... thì trang web hiển thị trang trăng (shop đã tạo sản phẩm và có nhiều giá)

**Comment by hongoctrien** [comment]
Cơ chế quản lý giá có thay đổi nên block này đang lỗi. Đội code ghi nhận và sẽ có phương án xử lý.
Cảm ơn bạn nhé.
