### ISSUE TITLE
Lỗi tính toán phần thống kê module

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#84]
![12-10-2014 10-01-03 sa](https://cloud.githubusercontent.com/assets/2421714/4604864/19ac0f28-51bc-11e4-8e8e-960470f45981.png)

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/module-shops/commit/eb2949884d6ceeecf272986f0c5fd2d47912a4dd)
