### ISSUE TITLE
Lỗi màu font giao diện trang chủ

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#85]
![12-10-2014 10-05-36 sa](https://cloud.githubusercontent.com/assets/2421714/4604875/caf68dc6-51bc-11e4-9cb7-d5793171ee4c.png)
Giao diện mặc định, chức năng tối ưu site đang kích hoạt!

**Comment by hongoctrien** [comment]
Mọi người cập nhật lại code mới của NukeViet 4 và Shops xem sao, mình test không thấy lỗi.

**Comment by hongoctrien** [comment]
@hoaquynhtim99 @thipdu 

Các bạn cho biết môi trường thử nghiệm để mình tiện kiểm tra:
- Hệ điều hành.
- Trình duyệt ...
