### ISSUE TITLE
Lỗi kiểu dữ liệu bảng transaction

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-shops#86]
Trường payment_amount có kiểu là int sẽ không lưu được những thanh toán bằng tiền USD (thường có số lẻ)

đồng thời trường payment và payment_id giới hạn ký tự quá ngắn dẫn đến không lưu được chuỗi dài hơn 22 ví dụ như paypal_express_checkout

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/hongoctrien/module-shops/commit/c757060aa0f71a60f84063a104fcd1b51654bf3e)
