### ISSUE TITLE
Nên tích hợp Rich Snippets Product của Google vào module shop

### ISSUE THREAD

**Issue by RightPro** [nukeviet/module-shops#88]
Hiện tại nukeviet đã tích hợp sẵn Rich Snippets Breakcump nhưng bên module shop thì chưa có Rich Snippets Products.
Rich Snippets này hỗ trợ rất tốt trong việc hiển thị kết quả tìm kiếm trên Google, mình thấy đội code nên tích hợp cho thêm vào.
Về phần mình hiện đã thử tích hợp vào bằng cách sửa file detail.tpl nhưng hiện vẫn chưa đạt (nó hiển thị mỗi giá lúc hiển thị kết quả tìm kiếm )

**Comment by hongoctrien** [comment]
[Updated](https://github.com/nukeviet/module-shops/commit/19fc6fda40aad53b6dda090d3887315e6f670132)
