### ISSUE TITLE
Lỗi truy vấn tìm kiếm giá tiền

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/module-shops#90]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 't1.product_discounts' in 'where clause'' in E:\server\htdocs\phobongbanmoi\modules\shops\funcs\search_result.php:154

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/hongoctrien/module-shops/commit/418f2ff66f25b9b14206e5c065fb512dcf899cbf)
