### ISSUE TITLE
Lỗi thêm sản phẩm bên loại sản phẩm thứ 2

### ISSUE THREAD

**Issue by RightPro** [nukeviet/module-shops#96]
Nếu chọn loại sản phẩm thứ 2(loại con của loại sản phẩm ví dụ như loại sp sách có loại con là Sách Giáo Khoa)
Khi vào mục loại sản phẩm > sách > sách giáo khoa ấn vào thêm sản phẩm là sẽ quay về trang thông tin module sản phẩm
Cấu hình test
OS: Win 7 ultimate sp1
Xampp v3.2.1
MySql 5.5.32 - MySQL Community Server (GPL)
PHP Version 5.4.16
NukeViet 4.0.0.9
Module shop 4.0.0.9

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/module-shops/commit/981960c64ac69baa2b4b4a488cef600a25bb6816)
